// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/on dojo/_base/html jimu/utils dojo/aspect dojo/keys".split(" "),function(b,c,a,d,g,e){return{a11y_init:function(){a.setAttr(this.domNode,"aria-label",this.nls._widgetLabel);a.setAttr(this.overviewMapDijit._maximizerDiv,"tabindex",0);"LaunchpadTheme"===window.getAppConfig().theme.name&&(this._a11y_isLaunchpadTheme=!0);this._a11y_isLaunchpadTheme?(this._a11y_index||(this._a11y_index=a.getAttr(this.domNode,"tabindex"),a.removeAttr(this.domNode,"tabindex")),this._a11y_index&&
a.setAttr(this.overviewMapDijit._controllerDiv,"tabindex",parseInt(this._a11y_index,10)),d.initFirstFocusNode(this.domNode,this.overviewMapDijit._maximizerDiv)):(a.setAttr(this.overviewMapDijit._controllerDiv,"tabindex",0),d.initFirstFocusNode(this.domNode,this.overviewMapDijit._controllerDiv));d.initLastFocusNode(this.domNode,this.overviewMapDijit._maximizerDiv)},a11y_initEvents:function(){this._a11y_RAW_DOM_NODE_HEIGHT=a.getStyle(this.domNode,"height");this._closedBy508Controller=this._openedBy508Enter=
!1;this._initToShow=!!this.config.overviewMap.visible;this.own(c(this.domNode,"keydown",b.hitch(this,function(f){var b=f.target;!1===this._initToShow&&f.keyCode===e.ENTER&&a.hasClass(b,this.baseClass)&&(this._openedBy508Enter=!0);!0===this._a11y_isLaunchpadTheme||f.keyCode!==e.TAB||a.hasClass(b,this.baseClass)||(f.preventDefault(),a.hasClass(b,"ovwController")?this.overviewMapDijit._maximizerDiv.focus():a.hasClass(b,"ovwMaximizer")&&this.overviewMapDijit._controllerDiv.focus())})));this.own(c(this.domNode,
"focus",b.hitch(this,function(){!0===this._closedBy508Controller||this._a11y_isLaunchpadTheme||!1===this._initToShow&&d.isInNavMode()&&!this._openedBy508Enter&&10>=a.getStyle(this.domNode,"height")&&this.overviewMapDijit.show()})));this.own(c(this.domNode,"blur",b.hitch(this,function(){!1===this._initToShow&&d.isInNavMode()&&!this._openedBy508Enter&&!0!==this._a11y_isLaunchpadTheme&&setTimeout(b.hitch(this,function(){a.isDescendant(document.activeElement,this.domNode)||this.overviewMapDijit.hide()}),
10)})));this.own(c(this.overviewMapDijit._controllerDiv,"keydown",b.hitch(this,function(a){a.keyCode===e.ENTER&&(this.overviewMapDijit.visible?(this.overviewMapDijit.hide(),this._openedBy508Enter=!1,this._closedBy508Controller=!0,!0!==this._a11y_isLaunchpadTheme?this.domNode.focus():this.overviewMapDijit._controllerDiv.focus()):(this.overviewMapDijit.show(),!1===this._initToShow&&(this._openedBy508Enter=!0,this._closedBy508Controller=!1),!0===this._a11y_isLaunchpadTheme&&this.overviewMapDijit._maximizerDiv.focus()))})));
this.own(c(this.overviewMapDijit._maximizerDiv,"keydown",b.hitch(this,function(a){a.keyCode===e.ENTER&&this.overviewMapDijit._maximizeHandler();!0===this._a11y_isLaunchpadTheme&&this.overviewMapDijit.visible&&a.keyCode===e.ESCAPE&&(this.overviewMapDijit.hide(),this.overviewMapDijit._controllerDiv.focus())})))},a11y_forLaunchpadThemeStyle:function(){this.own(g.after(this.overviewMapDijit,"_maximizeHandler",b.hitch(this,function(){var b=this.overviewMapDijit.overviewMap.container.parentElement||this.overviewMapDijit.overviewMap.container.parentNode,
c=b.parentElement||b.parentNode;this.overviewMapDijit._maximized?(a.addClass(b,"a11y_maximized"),a.addClass(c,"a11y_maximized")):(a.removeClass(b,"a11y_maximized"),a.removeClass(c,"a11y_maximized"))}),this))}}});