// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/NetworkTrace/setting/inputOutputSettings.html":'\x3cdiv\x3e\r\n    \x3cdiv\x3e\r\n        \x3cfieldset class\x3d"esriCTFieldset"\x3e\r\n            \x3clegend class\x3d"esriCTLegendTitle"\x3e${nls.inputOutputTab.inputSettingsLabel}\x3c/legend\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"inputTableNode"\x3e\r\n            \x3c/div\x3e\r\n        \x3c/fieldset\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv class\x3d"esriCTOutPutSettingsParent"\x3e\r\n        \x3cfieldset class\x3d"esriCTFieldset"\x3e\r\n            \x3clegend class\x3d"esriCTLegendTitle"\x3e${nls.inputOutputTab.outputSettingsLabel}\x3c/legend\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"outputTableNode"\x3e\r\n            \x3c/div\x3e\r\n        \x3c/fieldset\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/query dijit/registry dojo/dom-construct dojo/dom-style dojo/on ./SymbolChooserPopup jimu/symbolUtils esri/symbols/jsonUtils jimu/dijit/Popup dojo/sniff dojo/_base/html jimu/dijit/SimpleTable dojo/text!./inputOutputSettings.html dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/ValidationTextBox jimu/utils dijit/Editor esri/dijit/VisibleScaleRangeSlider ./FieldSelector jimu/dijit/Message dijit/form/Select dojo/dom-attr dijit/_editor/plugins/LinkDialog dijit/_editor/plugins/ViewSource dijit/_editor/plugins/FontChoice dojox/editor/plugins/Preview dijit/_editor/plugins/TextColor dojox/editor/plugins/ToolbarLineBreak dojox/editor/plugins/FindReplace dojox/editor/plugins/PasteFromWord dojox/editor/plugins/InsertAnchor dojox/editor/plugins/Blockquote dojox/editor/plugins/UploadImage jimu/dijit/EditorChooseImage jimu/dijit/EditorTextColor jimu/dijit/EditorBackgroundColor".split(" "),
function(y,g,l,h,t,e,m,q,z,A,r,B,C,D,u,E,F,G,H,v,n,I,w,J,K,x,L){return y([F,G,H],{templateString:E,baseClass:"jimu-widget-NetworkTrace-setting",_loadedPluginCSS:!1,_hasSkipLocationsInput:!1,startup:function(){this.inherited(arguments)},postCreate:function(){this._hasSkipLocationsInput=this._loadedPluginCSS=!1;this._createInputTable();this._createOutputTable()},onProjectSettingsChanged:function(b){l.forEach(this._outputTable.getRows(),g.hitch(this,function(a){var c=!0;b&&b.polygonLayerId&&b.pointLayerId&&
b.outputParamName&&(c=!1,a.config.paramName===b.outputParamName&&(c=!0));a&&a.layerSelector.set("disabled",c)}))},_createInputTable:function(){this._inputTable=new u({fields:[{name:"displayName",title:this.nls.common.name,type:"text",width:"15%"},{name:"type",title:this.nls.inputOutputTab.typeText,type:"empty",width:"25%"},{name:"toolTip",title:this.nls.inputOutputTab.inputTooltip,editable:!0,type:"text",width:"40%"},{name:"symbol",title:this.nls.inputOutputTab.symbol,type:"empty",width:"10%"}],selectable:!1});
this._inputTable.placeAt(this.inputTableNode);this._inputTable.startup();this.setInputSettings()},getInputSettings:function(){var b,a;b=[];l.forEach(this._inputTable.getRows(),g.hitch(this,function(c){var d={};c&&(d=this._inputTable.getRowData(c),a=this._getInputType(c.inputTypeDropdownObj),d={paramName:c.config.paramName,displayName:c.config.displayName,toolTip:d.toolTip,type:a,symbol:c.symbol},b.push(d))}));return b},setInputSettings:function(){this._inputTable.clear();this.inputConfig&&0<this.inputConfig.length&&
l.forEach(this.inputConfig,g.hitch(this,function(b){var a,c;c=this._inputTable.addRow(b);c.tr.config=b;b.type&&this.inputDataTypes.skip_locations===b.type&&(this._hasSkipLocationsInput=!0);if(a=h(".simple-table-cell",c.tr))this._addInputTypesDropDown(a[1],c.tr,b),this._addSymbolPicker(a[3],c.tr,b)}))},_createOutputTable:function(){this._outputTable=new u({fields:[{name:"visibility",title:this.nls.inputOutputTab.visibilityText,type:"checkbox",width:"10%"},{name:"displayName",title:this.nls.inputOutputTab.outputParametersText,
type:"text",width:"20%"},{name:"saveToLayer",title:"",type:"empty",width:"26%"},{name:"skipable",title:this.nls.inputOutputTab.skipText,type:"checkbox",width:"12%"},{name:"exportToCSV",title:this.nls.inputOutputTab.exportToCsvText,type:"checkbox",width:"12%"},{name:"symbol",title:this.nls.inputOutputTab.symbol,type:"empty",width:"10%"},{name:"settings",title:this.nls.inputOutputTab.settitngstext,type:"empty",width:"10%"}],selectable:!1});this._outputTable.placeAt(this.outputTableNode);this._outputTable.startup();
this._addSaveToLayerMainDiv();this._addHelpIconToHeader();this.setOutputSettings();this.onProjectSettingsChanged(this.projectSettings)},_addSaveToLayerMainDiv:function(){var b;if(b=h(".simple-table-thead tr",this.domNode)[1])if(b=b.children[2])b=e.create("div",{"class":"esriCTSaveToLayerMainDiv"},b),e.create("div",{"class":"esriCTSaveToLayerLabelDiv",innerHTML:this.nls.inputOutputTab.saveToLayerText,title:this.nls.inputOutputTab.saveToLayerText},b)},_getSaveToLayerInfo:function(b){var a={saveToLayerId:"",
guidField:"",parameterNameField:""};b&&b.get("value")&&(b=b._getSelectedOptionsAttr(),a.saveToLayerId=b.layerId,a.guidField=b.guidField,a.parameterNameField=b.parameterNameField);return a},getOutputSettings:function(){var b=[];l.forEach(this._outputTable.getRows(),g.hitch(this,function(a){var c={},d;a&&(d=this._outputTable.getRowData(a),c=this._getSaveToLayerInfo(a.layerSelector),c={visibility:d.visibility,paramName:a.config.paramName,type:"Result",panelText:a.config.panelText,toolTip:a.config.toolTip,
displayName:d.displayName,displayText:a.config.displayText,MinScale:a.config.MinScale,MaxScale:a.config.MaxScale,exportToCSV:d.exportToCSV,saveToLayer:c.saveToLayerId,guidField:c.guidField,parameternameField:c.parameterNameField,symbol:a.symbol},c.bypassDetails={skipable:d.skipable},b.push(c))}));return b},setOutputSettings:function(){this.outputConfig&&0<this.outputConfig.length&&l.forEach(this.outputConfig,g.hitch(this,function(b){var a,c,d;c=this._outputTable.addRow(b);a=h(".simple-table-cell",
c.tr);c.tr.config=b;"esriGeometryPoint"===b.data.defaultValue.geometryType&&this._hasSkipLocationsInput||(d=h(".skipable",c.tr),l.forEach(d,function(a){a=t.getEnclosingWidget(a.childNodes[0]);a.setValue(!1);a.setStatus(!1)}));a&&(this._addSaveToLayerDropDown(a[2],c.tr),this._addSymbolPicker(a[5],c.tr,b),this._addSettingsIcon(a[6],c.tr))}))},_validateLayerCapabilities:function(b){return b&&b.getEditCapabilities&&(b=b.getEditCapabilities(),b.canCreate&&b.canUpdate&&b.canDelete)?!0:!1},_validateLayerFields:function(b){var a,
c,d;d={projectidField:null,parameterNameField:null};c=a=!1;l.some(b,function(b){"esriFieldTypeGUID"===b.type&&b.editable&&"projectid"===b.name.toLowerCase()&&(d.projectidField=b.name,c=!0);"esriFieldTypeString"===b.type&&b.editable&&"parametername"===b.name.toLowerCase()&&(d.parameterNameField=b.name,a=!0);if(a&&c)return!0});a&&c||(d=null);return d},_createSaveToLayerOptions:function(b){var a,c,d=[];d.push({value:"",label:this.nls.projectSetting.selectLabel});if(this.map&&this.map.itemInfo&&this.map.itemInfo.itemData&&
this.map.itemInfo.itemData.operationalLayers)for(c=this.map.itemInfo.itemData.operationalLayers,a=0;a<c.length;a++){var e;c[a]&&c[a].layerObject&&c[a].layerType&&"ArcGISFeatureLayer"===c[a].layerType&&c[a].layerObject.fields&&b===c[a].layerObject.geometryType&&this._validateLayerCapabilities(c[a].layerObject)&&(e=this._validateLayerFields(c[a].layerObject.fields))&&(e={value:c[a].id,layerId:c[a].id,guidField:e.projectidField,parameterNameField:e.parameterNameField,label:c[a].title},d.push(e))}return d},
_addSaveToLayerDropDown:function(b,a){var c;b=e.create("div",{"class":"esriCTDropDownContainer"},b);c=this._createSaveToLayerOptions(a.config.data.defaultValue.geometryType);c=new x({options:c,"class":"esriCTLayerFieldSelector"});c.placeAt(b);c.startup();a.layerSelector=c;a.config&&a.config.saveToLayer&&c.set("value",a.config.saveToLayer)},_addSettingsIcon:function(b,a){b=e.create("div",{},b);b=e.create("div",{"class":"esriCTToleranceSettingsIcon",title:this.nls.inputOutputTab.settitngstext},e.create("div",
{},b));this.own(q(b,"click",g.hitch(this,function(){this._createOutputPanel(a)})))},_initEditorPluginsCSS:function(){var b,a;b=document.getElementsByTagName("head")[0];a=window.apiUrl+"dojox/editor/plugins/resources/css/TextColor.css";h('link[href\x3d"'+a+'"]',b)[0]||n.loadStyleLink("editor_plugins_resources_TextColor",a);a=window.apiUrl+"dojox/editor/plugins/resources/editorPlugins.css";h('link[href\x3d"'+a+'"]',b)[0]||n.loadStyleLink("editor_plugins_resources_editorPlugins",a);a=window.apiUrl+"dojox/editor/plugins/resources/css/PasteFromWord.css";
h('link[href\x3d"'+a+'"]',b)[0]||n.loadStyleLink("editor_plugins_resources_PasteFromWord",a)},_initEditor:function(){this._loadedPluginCSS||(this._loadedPluginCSS=!0,this._initEditorPluginsCSS());this._editorObj=new I({plugins:["bold","italic","underline",n.getEditorTextColor("networkTrace"),n.getEditorBackgroundColor("networkTrace"),"|","justifyLeft","justifyCenter","justifyRight","justifyFull","|","insertOrderedList","insertUnorderedList","indent","outdent"],extraPlugins:["|","createLink","unlink",
"pastefromword","|","undo","redo","|","toolbarlinebreak",{name:"dijit._editor.plugins.FontChoice",command:"fontName",custom:"Arial;Comic Sans MS;Courier New;Garamond;Tahoma;Times New Roman;Verdana".split(";")},"fontSize","formatBlock"],style:"font-family:Verdana;"},this.editorDescription);m.set(this._editorObj.domNode,{width:"100%",height:"100%"});this._editorObj.startup();if(8!==C("ie"))this._editorObj.resize({w:"100%",h:"100%"});else{var b=D.getMarginBox(this.editorDescription);this._editorObj.resize({w:b.w,
h:b.h})}this.own(q(this._editorObj,"focus",g.hitch(this,function(){this._editorObj.get("value")===this.nls.inputOutputTab.enterDisplayText&&this._editorObj.set("value","")})))},_createSlider:function(b,a,c){c&&c.saveToLayerId&&0===a.MinScale&&0===a.MaxScale?(a=this.map.getLayer(c.saveToLayerId),this._visibleScaleRangeSlider=new w({map:this.map,layer:a},e.create("div",{},b))):(this._visibleScaleRangeSlider=new w({map:this.map},e.create("div",{},b)),this._visibleScaleRangeSlider.set("minScale",a.MinScale),
this._visibleScaleRangeSlider.set("maxScale",a.MaxScale));this._visibleScaleRangeSlider.startup()},_createFieldSelector:function(b,a,c){(new J({fields:c,showOnlyNumericFields:!1,skipObjectIdField:!0,hideOnSelect:!0},e.create("div",{},b))).onSelect=g.hitch(this,function(b){a.get("value")===this.nls.inputOutputTab.enterDisplayText&&a.set("value","");b=a.get("value")+"{"+b.name+"}";a.set&&a.set("value",b)})},_createOutputPanel:function(b){var a,c="",c=b.config.displayName;a=e.create("div");var d=e.create("div",
{"class":"ParameterDiv esriCTtaskDataContainer",style:{"max-height":"395px"}},a),d=e.create("div",{"class":"section common-property"},d),f=e.create("div",{"class":"field esriCTOutputOutageField",title:this.nls.inputOutputTab.inputLabel},d);e.create("label",{innerHTML:this.nls.inputOutputTab.inputLabel,title:this.nls.inputOutputTab.inputLabel},f);this.labelTextbox=new v({required:!0,"class":"common-input esriCTLabelClass"},e.create("div",{},f));this.labelTextbox.set("value",b.config.panelText);e.create("div",
{"class":"esriCTHintField",innerHTML:this.nls.hintText.labelTextHint},f);f=e.create("div",{"class":"field esriCTOutputOutageField",title:this.nls.inputOutputTab.inputTooltip},d);e.create("label",{innerHTML:this.nls.inputOutputTab.inputTooltip,title:this.nls.inputOutputTab.inputTooltip},f);this.tooltipTextbox=new v({"class":"common-input esriCTTooltipDataClass"},e.create("div",{},f));this.tooltipTextbox.set("value",b.config.toolTip);f=e.create("div",{"class":"field esriCTOutputOutageField",title:this.nls.inputOutputTab.outputDisplay},
d);e.create("label",{innerHTML:this.nls.inputOutputTab.outputDisplay,title:this.nls.inputOutputTab.outputDisplay},f);var p=e.create("div",{"class":"edit-description-box"},f),h=e.create("div",{"class":"esriCTAddFieldContainer",title:this.nls.inputOutputTab.addFieldTitle},p);this.editorDescription=e.create("div",{},p);e.create("div",{"class":"esriCTHintField",innerHTML:this.nls.hintText.displayTextHint},f);this._initEditor();this._createFieldSelector(h,this._editorObj,b.config.data.defaultValue.fields);
this._editorObj.set("value",b.config.displayText);f=e.create("div",{"class":"field esriCTOutputOutageField",title:this.nls.inputOutputTab.setScale},d);e.create("label",{innerHTML:this.nls.inputOutputTab.setScale,title:this.nls.inputOutputTab.setScale},f);d=this._getSaveToLayerInfo(b.layerSelector);f=new e.create("div",{"class":"esriCTSliderContainer"},f);this._createSlider(f,b.config,d);var k=new B({titleLabel:c,width:875,maxHeight:800,autoHeight:!0,content:a,"class":this.baseClass,buttons:[{label:this.nls.common.ok,
onClick:g.hitch(this,function(){this.labelTextbox.isValid()?(b.config.panelText=this.labelTextbox.get("value"),b.config.toolTip=this.tooltipTextbox.get("value"),b.config.displayText=this._editorObj.get("value"),b.config.MinScale=this._visibleScaleRangeSlider.minScale,b.config.MaxScale=this._visibleScaleRangeSlider.maxScale,this._destroyEditorWidget(),k.close()):this.labelTextbox.focus()})},{label:this.nls.common.cancel,classNames:["jimu-btn-vacation"],onClick:g.hitch(this,function(){this._destroyEditorWidget();
k.close()})}],onClose:g.hitch(this,function(){this._destroyEditorWidget()})})},_getFallbackSymbol:function(b){var a;b||(b="esriGeometryPoint");switch(b){case "esriGeometryPoint":a={color:[0,0,128,128],outline:{color:[0,0,128,255],width:.75,type:"esriSLS",style:"esriSLSSolid"},size:18,type:"esriSMS",style:"esriSMSCircle"};break;case "esriGeometryPolygon":a={color:[155,187,89,129],outline:{color:[115,140,61,255],width:1.5,type:"esriSLS",style:"esriSLSSolid"},type:"esriSFS",style:"esriSFSSolid"};break;
case "esriGeometryPolyline":a={color:[155,187,89,255],type:"esriSLS",style:"esriSLSSolid",width:2.25}}return a},_addSymbolPicker:function(b,a,c){var d={},f,p="";f=c&&c.data&&c.data.defaultValue&&c.data.defaultValue.geometryType?c.data.defaultValue.geometryType:"esriGeometryPoint";c.displayName&&(p=c.displayName);d.symbol=a.symbol?r.fromJson(a.symbol):c&&c.symbol?r.fromJson(c.symbol):r.fromJson(this._getFallbackSymbol(f));var h={symbolChooserTitle:p,symbolParams:d,nls:this.nls,symbolType:"graphicLocationSymbol"},
k=e.create("div",{style:"height: 27px; overflow: hidden;"},b);this._showSelectedSymbol(k,d.symbol,a,f);this.own(q(k,"click",g.hitch(this,function(){h.symbolParams.symbol=r.fromJson(a.symbol);this._initSymbolChooserPopup(h,k,a,f)})))},_initSymbolChooserPopup:function(b,a,c,d){var e=new z(b);e.onOkClick=g.hitch(this,function(){var b=e.symbolChooser.getSymbol();this._showSelectedSymbol(a,b,c,d);e.popup.close()})},_showSelectedSymbol:function(b,a,c,d){e.empty(b);var f,h,l;if(a){26<a.height&&(f=g.clone(a.height),
a.height=26);26<a.width&&(h=g.clone(a.width),a.width=26);20<a.size&&(l=g.clone(a.size),a.size=20);var k=A.createSymbolNode(a);k||(k=e.create("div"));e.place(k,b);f&&(a.height=f);h&&(a.width=h);l&&(a.size=l);switch(d){case "esriGeometryPoint":m.set(b,"margin","0 24px");break;case "esriGeometryPolyline":m.set(k,"width","27px"),m.set(k,"overflow","hidden"),m.set(k,"margin","0 24px")}c.symbol=a.toJson()}},_addHelpIconToHeader:function(){var b,a,c;if(b=h(".simple-table-thead tr",this.domNode)[1])a=b.children[2],
a=a.childNodes[0],b.children[4]&&(c=b.children[4]);c&&c.childNodes&&c.childNodes[0]&&c.childNodes[0].hasAttribute("id")&&(b=t.byId(c.childNodes[0].id))&&(b.setLabel(this.nls.inputOutputTab.exportToCsvDisplayText),b.domNode&&b.domNode.children&&b.domNode.children[1]&&L.set(b.domNode.children[1],"title",this.nls.inputOutputTab.exportToCsvText));a=e.create("div",{"class":"esriCTSaveTolayerHelpIcon"},a);q(a,"click",g.hitch(this,function(){new K({message:this.nls.inputOutputTab.saveToLayerHelp})}))},_destroyEditorWidget:function(){this._editorObj&&
(this._editorObj.destroy(),this._editorObj=null)},_addInputTypesDropDown:function(b,a,c){var d;b=e.create("div",{"class":"esriCTDropDownContainer"},b);d=new x({options:[{label:"Flag",value:this.inputDataTypes.flags},{label:"Barrier",value:this.inputDataTypes.barriers},{label:"Skip",value:this.inputDataTypes.skip_locations}],"class":"esriCTLayerFieldSelector"});d.placeAt(b);d.startup();c.paramName.toLowerCase()===Object.keys(this.inputDataTypes)[0].toLowerCase()&&d.set("value",this.inputDataTypes.flags);
c.paramName.toLowerCase()===Object.keys(this.inputDataTypes)[1].toLowerCase()&&d.set("value",this.inputDataTypes.barriers);c.paramName.toLowerCase()===Object.keys(this.inputDataTypes)[2].toLowerCase()&&d.set("value",this.inputDataTypes.skip_locations);a.inputTypeDropdownObj=d;a.config&&a.config.type&&d.set("value",a.config.type)},_getInputType:function(b){var a;""!==b&&null!==b&&void 0!==b&&(a=b.get("value"));return a}})});