// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/on dojo/_base/html dojo/keys dojo/query esri/lang dijit/Tooltip dojo/dom-geometry jimu/utils".split(" "),function(g,m,h,t,q,v,x,w,k){var l={TabindexForSplash:1,TabindexForSkipLinks:101,TabindexRangeForController:1E4,TabindexRangeForWidget:200,_setTabindex:function(a,d){function n(b,c){b&&("undefined"!==typeof b.bottom&&(b.top=c.h-b.bottom-100,delete b.bottom),"undefined"!==typeof b.right&&(b.left=c.w-b.right-100,delete b.right))}function u(b,c,a){c=g.clone(c.position||
c.panel&&c.panel.position);a=g.clone(a.position||a.panel&&a.panel.position);n(c,b);n(a,b);return c.top===a.top?c.left-a.left:c.top-a.top}var f=[],p=[],r=!1,c=null;d?a.visitElement(function(b,c){c.isOnScreen&&(c=b.position||b.panel&&b.panel.position)&&!Array.isArray(b.widgets)&&"widgetOnScreen"===b.gid&&b.visible&&("browser"===c.relativeTo?(f.push(b),"Splash"===b.name&&(r=!0)):p.push(b))}):a.visitElement(function(b,a){a.isOnScreen&&(a=b.position||b.panel&&b.panel.position)&&("widgetOnScreen"===b.gid&&
b.visible||!b.visible&&b.panel)&&("browser"===a.relativeTo?("AttributeTable"===b.name?c=b:f.push(b),"Splash"===b.name&&(r=!0)):p.push(b))});a=w.getMarginBox(this.layoutId);var y=w.getMarginBox(this.mapId),f=f.sort(g.hitch(this,u,a)),p=p.sort(g.hitch(this,u,y));d?f.unshift(this.map):f.push(this.map);c&&p.push(c);var e=l.TabindexForSplash;r?f.every(function(b){return"Splash"===b.name?(b.tabIndex=e,!1):!0}):(a=q("#skipContainer")[0],h.setAttr(a,"tabindex",e+""),this.own(m(a,"focus",g.hitch(this,function(){k.focusOnFirstSkipLink()}))));
this._initSkipLinks(d,f,c);e+=l.TabindexRangeForWidget;d?(f.forEach(function(b){"Splash"!==b.name&&(b.tabIndex=e,e=b.isController?e+l.TabindexRangeForController:e+l.TabindexRangeForWidget)}),e=this._initGridLayoutPanels(e),this._initGridMapEvents(e)):(f.forEach(function(b){"Splash"!==b.name&&(b.inPanel?b.tabIndexJimu=e:"map"===b.id?b.container.tabIndex=e:b.tabIndex=e,e=b.isController?e+l.TabindexRangeForController:e+l.TabindexRangeForWidget)}),this._initAbsoluteMapEvents());d=q("#trapLinkNode")[0];
this.own(m(d,"focus",g.hitch(this,function(b){k.tryToFocusSplashWidget(b)||k.focusOnFirstSkipLink()})));e+=1E3;p.forEach(function(b){b.inPanel?b.tabIndexJimu=e:b.tabIndex=e;e=b.isController?e+l.TabindexRangeForController:e+l.TabindexRangeForWidget})},_initGridLayoutPanels:function(a){for(var d=q(".lm_item.lm_stack",this.layoutContainer),n=d.on("focus",g.hitch(this,function(a){n.remove();k.tryToFocusSplashWidget(a)||k.focusOnFirstSkipLink()})),l=0;l<=d.length-1;l++){var f=d[l];f.tabIndex=a-1;h.setAttr(f,
"role","application");this.own(m(f,"keydown",g.hitch(this,function(a,d){h.hasClass(d.target,"lm_stack")?d.keyCode===t.ENTER?(a=q(".jimu-widget",a)[0])&&(h.hasClass(a.parentNode,"map")?this.map.container.focus():k.focusFirstFocusNode(a)):d.keyCode!==t.TAB||d.shiftKey||a.nextSibling||a.parentNode.nextSibling||(d.preventDefault(),k.focusOnFirstSkipLink()):d.keyCode===t.ESCAPE&&a.focus()},f)))}return a},_initMapAttrs:function(a){a&&h.setAttr(this.map.container,"tabindex",a);h.setAttr(this.map.container,
"aria-label",window.jimuNls.common.mapArea);k.addTooltipByDomNode(x,this.map.container,window.jimuNls.common.mapArea)},_initGridMapEvents:function(a){this._initMapAttrs(a);this.own(m(this.map.container,"keydown",g.hitch(this,function(a){"map"===h.getAttr(a.target,"id")?a.shiftKey&&a.keyCode===t.TAB&&a.preventDefault():a.stopPropagation()})));this.own(m(this.map.container,"focus",g.hitch(this,function(a){k.isInNavMode()&&"map"===h.getAttr(a.target,"id")&&(a=document.getElementById("map_container"),
a.addEventListener("mouseover",function(){}),a.simulateEvent=new MouseEvent("mouseover",{view:window,bubbles:!0,cancelable:!0}),this.map.isKeyboardNavigationOrigin=this.map.isKeyboardNavigation,a.dispatchEvent(a.simulateEvent)&&this.map.enableKeyboardNavigation())})));this.own(m(this.map.container,"blur",g.hitch(this,function(a){k.isInNavMode()&&"map"===h.getAttr(a.target,"id")&&(document.getElementById("map_container").removeEventListener("mouseover",function(){}),this.map.isKeyboardNavigationOrigin||
this.map.disableKeyboardNavigation())})))},_initAbsoluteMapEvents:function(){this._initMapAttrs();h.setAttr(this.map.container,"role","application");this.own(m(this.map.container,"keydown",g.hitch(this,function(a){"map"===h.getAttr(a.target,"id")&&a.keyCode===t.ESCAPE&&k.trapToNextFocusContainer(this.map.container)})));window.isMoveFocusWhenInit=!0;this.own(m(this.map.container,"focus",g.hitch(this,function(a){k.isInNavMode()&&"map"===h.getAttr(a.target,"id")&&!this.widgetManager._resetFirstFocusNode()&&
(a=document.getElementById("map_container"),a.addEventListener("mouseover",function(){}),a.simulateEvent=new MouseEvent("mouseover",{view:window,bubbles:!0,cancelable:!0}),this.map.isKeyboardNavigationOrigin=this.map.isKeyboardNavigation,a.dispatchEvent(a.simulateEvent)&&this.map.enableKeyboardNavigation())})));this.own(m(this.map.container,"blur",g.hitch(this,function(a){k.isInNavMode()&&"map"===h.getAttr(a.target,"id")&&!this.widgetManager._resetFirstFocusNode()&&(document.getElementById("map_container").removeEventListener("mouseover",
function(){}),this.map.isKeyboardNavigationOrigin||this.map.disableKeyboardNavigation())})))},_initSkipLinks:function(a,d,n){var u=l.TabindexForSkipLinks,f=window.jimuNls.skips,p="",r=q("#skipContainer")[0];h.setAttr(r,"role","application");h.setAttr(r,"aria-label",f.skips);d.forEach(function(a){if("Splash"!==a.name){var c;if("map"===a.id)c=f.map;else if(a.panel&&a.widgets){if(0===a.widgets.length)return;c=a.isOnScreen?f.sidePanel:a.label}else{if(a.inPanel)return;c=v.substitute({value:a.label},f.skipTo)}p+=
'\x3cli\x3e\x3ca role\x3d"link" id\x3d"skip_'+a.id+'" aria-hidden\x3d"true" tabindex\x3d"'+u+'"\x3e'+c+"\x3c/a\x3e\x3c/li\x3e"}});n&&(d=v.substitute({value:n.label},f.skipTo),p+='\x3cli\x3e\x3ca role\x3d"link" id\x3d"skip_'+n.id+'" aria-hidden\x3d"true" tabindex\x3d"'+u+'"\x3e'+d+"\x3c/a\x3e\x3c/li\x3e");r.innerHTML="\x3cul\x3e"+p+"\x3c/ul\x3e";n=q("a",r);this.own(m(n,"focus",g.hitch(this,function(a){this.widgetManager._resetFirstFocusNode()||h.setAttr(a.target,"aria-hidden","false")})));this.own(m(n,
"blur",g.hitch(this,function(a){h.setAttr(a.target,"aria-hidden","true")})));this.own(m(n,"keydown",g.hitch(this,function(c){if(c.keyCode===t.ENTER){c=c.target.id.split("skip_")[1];var d=q("#"+c)[0];d||(d=q("#"+c+"_panel")[0]);d.focus()}else{var e;a&&(e=q(".lm_item.lm_stack",this.layoutContainer));!c.target.parentNode.previousSibling&&c.shiftKey&&c.keyCode===t.TAB?(c.preventDefault(),a?d=e[e.length-1]:(c=k.getFrameNodesByAsc(),d=c[c.length-1])):c.keyCode===t.ESCAPE&&(d=k.trapToNextFocusContainer(r),
a&&!d&&(d=e[0]));d&&d.focus()}})))}};return l});