// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/store/Memory dojo/query dojo/dom-class dojo/dom-style dojo/dom-geometry dijit/form/FilteringSelect dijit/form/_ComboBoxMenu ../../dijit/tooltips/TooltipUtil dojo/i18n!../../../nls/strings xstyle/css!./css/FilteringSelect.css".split(" "),function(c,e,k,f,l,m,n,p,g,q){var h=c(e,{filtered:!1,noneItem:null,get:function(a){return"None"==a?this.noneItem:this.inherited(arguments)},query:function(a,b){var d=this.inherited(arguments);this.filtered=d.length!=this.data.length;
return d}});e=c(p,{baseClass:"dijitComboBoxMenu",idProperty:"value",postCreate:function(){this.inherited(arguments);g.autoTooltip(this.domNode)},_createMenuItem:function(){var a=this.inherited(arguments);a.className+=" TrimWithEllipses";return a},selectItem:function(a){if(this.items){for(var b=-1,d=0;d<this.items.length;d++)if(this.items[d][this.idProperty]==a){b=d;break}if(!(0>b))for(a=this.containerNode.children,d=0;d<a.length;d++){var c=a[d];if("none"!=c.style.display&&c.getAttribute("item")==
b){this.selectLastNode();this.set("selected",c,!0);break}}}}});c=c(n,{forceWidth:!1,autoWidth:!1,selectOnClick:!0,idProperty:"value",labelProperty:"label",placeHolder:null,dropDownClass:e,options:null,_assignedStore:null,_isCreated:!1,postMixInProperties:function(){this.searchAttr=this.labelAttr=this.labelProperty;var a={};a[this.idProperty]="None";a[this.labelAttr]=this.placeHolder||q.None;this.set("store",new h({idProperty:this.idProperty,noneItem:a}));this.inherited(arguments)},_startSearch:function(){this.inherited(arguments);
this.dropDown.idProperty=this.idProperty;this.dropDown.labelProperty=this.labelProperty},postCreate:function(){this.inherited(arguments);g.autoTooltip(this.domNode);(this.options||this._assignedStore)&&this.setItems(this.options||this._assignedStore.data);f.add(this.domNode,"esriMapsAnalystXFilteringSelect");this._isCreated=!0},_onFocus:function(){this._updateTrimWithEllipses(!0);this.inherited(arguments)},_onBlur:function(){this.inherited(arguments);this._updateTrimWithEllipses(!1)},_updateTrimWithEllipses:function(a){var b=
k(".dijitInputInner",this.domNode)[0];if(b)f[a?"remove":"add"](b,"TrimWithEllipses")},_setStoreAttr:function(a){a instanceof h?(this.store=a,this.inherited(arguments)):(this._assignedStore=a,this._isCreated&&this.setItems(this._assignedStore.data))},_setOptionsAttr:function(a){this.options=a;this._isCreated&&this.setItems(this.options)},setItems:function(a,b){this.store.setData(a);this.closeDropDown();this.dropDown&&this.dropDown.clearResultList();a=this.get("value");b=b||"None";this.set("value",
b);b==a&&this.emit("Change");this._updateTrimWithEllipses(this.get("focused"))},_openResultList:function(a,b,d){var c=m.getContentBox(this.domNode).w;l.set(this.dropDown.domNode,"width",c+"px");this.inherited(arguments);this.store.filtered||this.dropDown.selectItem&&this.dropDown.selectItem(this.get("value"))},_setBlurValue:function(){var a=this.get("displayedValue");"undefined"==typeof this.item&&(this.item=null,this.set("displayedValue",a));this.value!=this._lastValueReported&&this._handleOnChange(this.value,
!0);this._refreshState();this.focusNode.removeAttribute("aria-activedescendant")},getSelectedItem:function(){var a=this;return this.store.data.filter(function(b){return b[a.idProperty]==a.get("value")})[0]}});c.NONE_ID="None";return c});