// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/dom-class dojo/on ../../utils/ObjectUtil esri/dijit/geoenrichment/utils/DomUtil".split(" "),function(l,k,f,m,p,n,r){var c=Object.assign({},r);c.select=function(a){return c.addTag(a,"selected")};c.unselect=function(a){return c.removeTag(a,"selected")};c.floatStart=function(a){return c.addTag(a,"esriMapsAnalystXFloatStart")};c.floatEnd=function(a){return c.addTag(a,"esriMapsAnalystXFloatEnd")};c.addSpacer=function(a,d){a=l.create("div",
{"class":"esriMapsAnalystXSpacer",innerHTML:"\x26nbsp;"},a);if(d)c[d](a);return a};c.getAndUpdateNumber=function(a,d){if(!a)return NaN;var c=a.get&&a.set;void 0===d&&(d=0);var b=n.parseNumber(c?a.get("value"):a.value,d);isNaN(b)||(c?a.set("value",n.formatNumber(b,d)):a.value=n.formatNumber(b,d));return b};c.getAndUpdateString=function(a){if(!a)return null;if(a.get&&a.set){var d=a.get("value").trim();a.set("value",d)}else d=a.value.trim(),a.value=d;return d};c.getScreenScaleFactor=function(){return c.getTextBox("",
{style:"width: 72pt; height: 72pt"}).w/96};c.positionAtCenter=function(a,d){if(a&&d){var c=k.position(a);d=k.position(d);c.w&&c.h&&d.w&&d.h&&f.set(a,{left:(d.w-c.w)/2+"px",top:(d.h-c.h)/2+"px"})}};c.showAroundOverlay=function(a,d){d=d||{};c.removeAroundOverlay(a);var q={w:"width",h:"height",l:"left",t:"top",r:"right",b:"bottom"},b=k.position(a);if(d.viewPortContainer){var g=k.position(d.viewPortContainer),t=b.x,e=b.y;b.x=Math.max(b.x,g.x);b.w-=b.x-t;b.y=Math.max(b.y,g.y);b.h-=b.y-e;b.w=Math.min(b.w,
g.x+g.w-b.x);b.h=Math.min(b.h,g.y+g.h-b.y)}a.__aroundOverlays=(d.placeInNode?[{l:0,t:-b.y,w:b.w,h:b.y},{l:b.w,t:-b.y,w:document.body.clientWidth-(b.x+b.w),h:document.body.clientHeight},{l:0,t:b.h,w:b.w,h:document.body.clientHeight-(b.y+b.h)},{l:-b.x,t:-b.y,w:b.x,h:document.body.clientHeight}]:[{l:b.x,t:0,w:b.w,h:b.y},{w:document.body.clientWidth-(b.x+b.w),r:0,t:0,b:0},{l:b.x,h:document.body.clientHeight-(b.y+b.h),w:b.w,b:0},{l:0,t:0,w:b.x,b:0}]).map(function(b){var c=l.create("div",{"class":d.overlayClass||
"esriMapsAnalystXNodeAroundOverlay"},d.placeInNode?a:document.body),g={position:"absolute"},e;for(e in q)void 0!==b[e]&&(g[q[e]]=Math.round(b[e])+"px");f.set(c,g);return c});b=function(){c.removeAroundOverlay(a)};d.removeOnClick&&(a.__aroundOverlaysRemoveHandle=p.once(document.body,"click",b));a.__aroundOverlaysResizeHandle=p(window,"resize",function(){c.showAroundOverlay(a,d)});var h;a.__aroundOverlaysSetIntervalHandle=setInterval(function(){if(h){var b=k.position(a);b.x==h.x&&b.y==h.y&&b.w==h.w&&
b.h==h.h||c.showAroundOverlay(a,d)}else h=k.position(a)},50);return{remove:b}};c.removeAroundOverlay=function(a){a.__aroundOverlays&&a.__aroundOverlays.forEach(function(a){l.destroy(a)});delete a.__aroundOverlays;a.__aroundOverlaysRemoveHandle&&a.__aroundOverlaysRemoveHandle.remove();delete a.__aroundOverlaysRemoveHandle;a.__aroundOverlaysResizeHandle&&a.__aroundOverlaysResizeHandle.remove();delete a.__aroundOverlaysResizeHandle;clearInterval(a.__aroundOverlaysSetIntervalHandle);delete a.__aroundOverlaysSetIntervalHandle};
c.getDocumentStyleDeclaration=function(a){function d(b){var c;try{c=b.rules||b.cssRules}catch(h){c=null}if(c)for(b=0;b<c.length;b++){var e=c[b];if(e.styleSheet){if(e=d(e.styleSheet))return e}else if(e.selectorText==a)return e.style}}for(var c=0;c<document.styleSheets.length;c++){var b=d(document.styleSheets[c]);if(b)return b}return null};c.getNodeFontFamily=function(a){return(a=f.get(a,"fontFamily")||f.getComputedStyle(a)["font-family"])?a.replace(/'|"/g,"").split(",")[0]:a};c.getNodeFontSize=function(a){return f.toPixelValue(a,
f.get(a,"fontSize"))};c.listenToNodeAdded=function(a,d,f){if(c.isNodeInLayout(a))d();else{a.__listenToNodeAddedHandle&&a.__listenToNodeAddedHandle.remove();var b=setInterval(function(){c.isNodeInLayout(a)&&(a.__listenToNodeAddedHandle&&a.__listenToNodeAddedHandle.remove(),d())},f||100);a.__listenToNodeAddedHandle={remove:function(){clearInterval(b);delete a.__listenToNodeAddedHandle}};return a.__listenToNodeAddedHandle}};c.isNodeVisible=function(a){return c.isChildOf(a,document.body,function(a){return!m.contains(a,
"dijitHidden")&&"hidden"!=f.get(a,"visibility")})};c.enableHyperlink=function(a,c){c?m.replace(a,"esriMapsAnalystXLink","esriMapsAnalystXLinkDisabled"):m.replace(a,"esriMapsAnalystXLinkDisabled","esriMapsAnalystXLink")};return c});