// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/dom-construct dojo/dom-style dojo/dom-geometry dojo/dom-class dojo/query dojo/on dojox/gfx dojo/sniff dojo/aspect dojox/uuid/generateRandomUuid dijit/Tooltip ../utils/DomUtil ../utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/domReady!".split(" "),function(m,p,r,w,G,l,H,I,A,x,t,v,J,B){function u(){g&&(g.isMultilineContainer?k.hideTooltipForNode(g):(clearInterval(g.__autoTooltipInLayoutCheckHandle),delete g.__autoTooltipInLayoutCheckHandle,t.hide(g)),g=null)}function C(a,
b){b=b||"";var d=m.create("div",{class:"esriMapsAnalystXValidationTooltip"+b},document.body);!b&&m.create("div",{class:"esriMapsAnalystXValidationTooltipTip"+b},d);m.create("div",{innerHTML:a,class:"esriMapsAnalystXValidationTooltipBody"+b},d);p.set(d,"position","fixed");return d}function D(a,b){function d(){a&&(document.body.removeChild(a),f.forEach(function(a){a.remove()}),a=f=null)}b=b.textbox||b;var c=r.getMarginBox(a),e=r.position(b);"rtl"===document.dir?p.set(a,{left:e.x-c.w+"px",top:e.y+e.h/
2-c.h/2+"px"}):p.set(a,{left:e.x+e.w+"px",top:e.y+e.h/2-c.h/2+"px"});var f=[l(document.body,"mousedown, keydown",d),l(b,"blur",d)];return{remove:d}}function E(a,b,d){function c(){var a=m.create("div",{class:"esriMapsAnalystXClosableTooltipTip"},f);w.add(a,"right"===d?"esriMapsAnalystXClosableTooltipTipRight":"esriMapsAnalystXClosableTooltipTipLeft")}function e(){g=m.create("div",{class:"esriMapsAnalystXClosableTooltipBody"},f);m.create("div",{innerHTML:a,class:"esriMapsAnalystXClosableTooltipLabel"},
g);h=m.create("div",{class:"esriMapsAnalystXClosableTooltipCloseButton esriMapsAnalystXCloseWindow esriMapsAnalystXCloseWindowWhite"},g)}b={class:"esriMapsAnalystXClosableTooltip "+(b||"")};b.id=x();var f=m.create("div",b,document.body),g,h;"right"!==d?(e(),c()):(c(),e());p.set(f,"position","fixed");return{tooltip:f,body:g,closeButton:h}}function F(a,b,d,c){var e=r.getMarginBox(a.tooltip),f=r.position(b);"rtl"===document.dir&&"right"!==c||"rtl"!==document.dir&&"right"===c?p.set(a.tooltip,{left:f.x+
f.w+"px",top:f.y+f.h/2-e.h/2+"px"}):p.set(a.tooltip,{left:f.x-e.w+"px",top:f.y+f.h/2-e.h/2+"px"});var g,h,n,q=function(){g&&clearTimeout(g);h&&clearInterval(h);n&&n.remove();a.tooltip.parentNode===document.body&&document.body.removeChild(a.tooltip)};h=setInterval(function(){v.isNodeInLayout(b)||q();v.isNodeVisible(b)?v.show(a.tooltip):v.hide(a.tooltip)},300);d&&(g=setTimeout(q,d));n=l(a.closeButton,"click",function(){q()});a.tooltip._removeFunc=q;return a.tooltip}var k={},y={};k.hideTooltipForNode=
B.hideTooltipForNode;k.setTooltipToNode=B.setTooltipToNode;k.createTooltip=function(a,b,d){var c={orientation:r.isBodyLtr(document)?"right":"left",offset:{x:15,y:0}};b&&(c.innerHTML=b);d&&(c=Object.assign(c,d));c.id=x();c.toMouseCursor&&(c.mouseEvent=J.getCursorPosition(),delete c.toMouseCursor);b=c.mouseEvent;delete c.mouseEvent;d=c.htmlFragment;delete c.htmlFragment;var e=c.widget;delete c.widget;var f=c.orientation;delete c.orientation;var g=c.offset;delete c.offset;var h=c.horizontalOffset;delete c.horizontalOffset;
var n=m.create("div",c,a?a.container:document.body);d?m.place(d,n):e&&e.placeAt(n);p.set(n,"position","fixed");var q=r.getMarginBox(n),k=function(a,b){var c=a.touches?event.touches[0].clientX:a.clientX;a=a.touches?event.touches[0].clientY:a.clientY;var e,d,h=g.x,k=g.y;"left"===f?0>c-q.w-h&&(e="right"):c+q.w+h>document.body.clientWidth&&(e="left");a+q.h+k>document.body.clientHeight&&(d="above");e=e||f;p.set(n,{left:b?b+"px":c+("left"===e?-q.w-h:h)+"px",top:a+("above"===d?-q.h-k:k)+"px"});n.style.display=
""};b&&k(b,h);c=[];c.push(l(a?a:document.body,a?"mouse-move, mousemove":"mousemove, touchmove",function(a){k(a,h)}));c.push(l(a?a:document.body,a?"mouse-out, mouseout":"mouseout, touchend",function(a){n.style.display="none"}));a={};a.handlers=c;a.tooltip=n;y[n.id]=a;return n};k.removeTooltip=function(a){if(a){a="string"===typeof a?a:a.id;var b=y[a];delete y[a];b&&(b.handlers.forEach(function(a){a.remove()}),m.destroy(b.tooltip))}};var z={};k.registerTooltipForSlider=function(a,b,d,c){var e={offsetX:0,
offsetY:0,class:"esriMapsAnalystXTooltip"};b&&(e=Object.assign(e,b));e.id=x();var f=m.create("div",e,document.body);f.style.display="none";p.set(f,"position","fixed");var g=!1,h=function(b,c){if(!g){g=!0;f.style.display="";f.innerHTML=c();var d=r.getMarginBox(f),h=r.position(b);p.set(f,{left:h.x+h.w/2-d.w/2+e.offsetX+"px",top:h.y-d.h-5+e.offsetY+"px"});var k=[];k.push(A.after(a,"onChange",function(){f.innerHTML=c();h=r.position(b);p.set(f,{left:h.x+h.w/2-d.w/2+"px",top:h.y-d.h-5+"px"})}));var n=function(){f.style.display=
"none";k.forEach(function(a){a.remove()});g=!1},m=!1;k.push(l(b,"mousedown, mouseDown, mouse-down",function(){m=!0;k.push(l(document,"mouseup, mouseUp, mouse-up",function(){n()}))}));k.push(l(b,"mouseout, mouseOut, mouse-out",function(){m||n()}))}};b=[];b.push(l(a.sliderHandle,"mouseover, mouseOver, mouse-over",function(){c&&a.isSliderDisabled&&a.isSliderDisabled()||h(a.sliderHandle,function(){var b=c?a.get("value")[0]:a.get("value");return d?d(b):b})}));c&&b.push(l(a.sliderHandleMax,"mouseover, mouseOver, mouse-over",
function(){a.isSliderDisabled&&a.isSliderDisabled()||h(a.sliderHandleMax,function(){return d?d(a.get("value")[1]):a.get("value")[1]})}));b.push(A.before(a,"destroy",function(){k.unregisterTooltipForSlider(a)}));a.tooltipId=f.id;var n={};n.tooltip=f;n.handlers=b;z[f.id]=n};k.unregisterTooltipForSlider=function(a){var b=z[a.tooltipId];b&&(b.handlers.forEach(function(a){a.remove()}),m.destroy(b.tooltip));delete z[a.tooltipId];delete a.tooltipId};var g=null;k.autoTooltip=function(a,b,d){"string"===typeof b&&
(b=b.split(" ").filter(function(a){return a&&!!a.trim().length}));b=b||[];b.push("TrimWithEllipses");d=d||[];d.push("esriMapsAnalystXInfoIcon");for(var c=0;c<b.length;c++)l(a,"."+b[c]+":mouseover, "+b[c]+":touchstart, ",function(a){this!==g&&this.offsetWidth<this.scrollWidth&&!this.noAutoTooltip&&(a=getComputedStyle(this).width,a=Number(a.substr(0,a.length-2)),0>a-Math.round(a)&&this.offsetWidth==this.scrollWidth-1||(u(),g=this,a=g.autoTooltip||g.textContent||g.value,g.title&&(a+=" ("+g.title+")"),
a&&t.show(a,g,["above","below"]),l.once(g,"mouseout, touchstart, touchout",function(){u()}),g.__autoTooltipInLayoutCheckHandle=setInterval(function(){v.isNodeInLayout(g)||u()},500)))});if(I("touch"))for(c=0;c<d.length;c++)l(a,"."+d[c]+":touchstart ",function(a){this!==g&&(g=this,g.title&&(t.show(g.title,g,["above","below"]),l.once(g,"touchstart, touchout",function(){t.hide(g);g=null})))})};k.addAutoTooltipsToTabContainer=function(a){G(".tabLabel",a.domNode).forEach(function(a){w.add(a,"TrimWithEllipses")});
k.autoTooltip(a)};k.setMultilineText=function(a,b,d,c){d=d||2;b=b.trim();c=c||["above","below"];w.remove(a,"TrimWithEllipses");a.style.overflow="hidden";a.innerHTML="";for(var e=b,f=!1;e;){d--;var l=m.create("div",null,a);l.style.overflow="hidden";l.style.whiteSpace="nowrap";for(var h=e;h;)if(l.textContent=h,l.offsetWidth<l.scrollWidth-1)h=(h=h.match(/^(.*[^\s]+)\s+[^\s]+$/))&&h[1]||"";else break;!h||!d&&h!==e?(l.textContent=e,e="",l.style.textOverflow="ellipsis",f=!0):e=e.substr(h.length).trim()}f&&
k.setTooltipToNode(a,function(){u();g=a;g.isMultilineContainer=!0;return b},{position:c})};k.showErrorTip=function(a,b){return D(C(b),a.domNode||a)};k.showNewStyleErrorTip=function(a,b,d){return D(C(b,"NewStyle"+(d?" esriMapsAnalystXWarningStyle":"")),a.domNode||a)};k.showAlertTooltip=function(a){a&&a.node&&a.message&&(t.show(a.message,a.node,a.position||["above","below"]),setTimeout(function(){t.hide(a.node)},a.timeout||5E3))};k.showClosableTooltip=function(a){var b=E(a.message,a.tooltipClass,a.position);
return F(b,a.component,a.timeout,a.position)};k.removeClosableTooltip=function(a){a&&a._removeFunc&&a._removeFunc()};k.showClosableTooltipOnVerticalBracket=function(a){var b=a.below||a.above,d=r.position(a.above,!0),c=r.position(b,!0),e="rtl"!==document.dir?"start"===a.direction:"end"===a.direction,f=d.x+d.w*(e?0:1),d=d.y,g=c.y+c.h,h=m.create("div",{class:"esriMapsAnalystFlexibleTooltip_tooltip esriMapsAnalystXNonSelectable"},document.body),k=m.create("div",{class:"esriMapsAnalystFlexibleTooltip_surfaceContainer"},
h),c={},f={top:d-2,left:f+(e?-3:3),height:g-d+4,width:10},q;for(q in f)c[q]=f[q]+"px";p.set(h,c);var t=H.createSurface(k,f.width,f.height);t.clear();t.createPolyline([{x:e?f.width:0,y:0},{x:e?0:f.width,y:0},{x:e?0:f.width,y:f.height},{x:e?f.width:0,y:f.height}]).setStroke({color:"#6E6E6E",width:6});a.component=h;var e=E(a.message,a.tooltipClass,a.position),u=function(){clickHandler&&clickHandler.remove();w&&clearInterval(w);t&&t.clear();m.destroy(k);m.destroy(h)},w=setInterval(function(){v.isNodeInLayout(b)||
u();v.isNodeVisible(b)?p.set(h,"visibility","visible"):p.set(h,"visibility","hidden")},300);a.timeout&&setTimeout(u,a.timeout);clickHandler=l(e.closeButton,"click",u);tooltip=F(e,a.component,a.timeout,a.position);var x=tooltip._removeFunc;tooltip._removeFunc=function(){x();u()};return tooltip};return k});