// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dijit/_WidgetBase dojo/_base/declare dojo/Evented dojo/_base/array dojo/_base/lang dojo/on dojo/query dojo/dom-construct dojo/dom-class dojo/dom-style dojo/dom-attr ./ChartLayout jimu/utils dojo/keys dijit/focus".split(" "),function(t,u,v,n,k,p,d,l,e,w,q,x,y,r,z){return u([t,v],{openPanels:[],chartArray:[],constructor:function(){},postCreate:function(){this.inherited(arguments)},initAccordionPane:function(){var a,b,f,c;(this.config.charts.highlightedChartIndex||0===this.config.charts.highlightedChartIndex)&&
-1===n.indexOf(this.openPanels,"Chart"+this.config.charts.highlightedChartIndex)&&this.openPanels.push("Chart"+this.config.charts.highlightedChartIndex);a=l.create("div",{"class":"esriCTAccordionWrapper"},this.node);this.chartArray=[];n.forEach(this.config.charts,k.hitch(this,function(c,d){var h,f,g,m;m="Chart"+d;g=l.create("div",{"class":"esriCTChartRow",chartIndex:m},a);h=y.sanitizeHTML(c.chartConfig.sectionTitle);h=l.create("div",{"class":"esriCTChartTitle",innerHTML:h,title:h,role:"button",tabindex:0,
"aria-label":h,"aria-expanded":"false"},g);f=l.create("div",{"class":"esriCTChartContent"},g);c.chartData&&c.selectedFeature?(b=new x({nls:this.nls,config:c},l.create("div",{},f)),this.own(p(b,"setFocusNodes",k.hitch(this,function(){this.emit("setFocusNodes")}))),b.onChartCreated=k.hitch(this,function(){this.openPanels.length?-1===this.openPanels.indexOf(m)&&e.add(f,"esriCTHidden"):0!==d&&e.add(f,"esriCTHidden")}),b.onChartResize=k.hitch(this,function(){this.openPanels.length&&this._setFocusOnChart()}),
this.chartArray.push(b),b.startup(),p(h,"click",k.hitch(this,function(a){this._expandChart(a,d)})),p(h,"keydown",k.hitch(this,function(a){a.keyCode!==r.ENTER&&a.keyCode!==r.SPACE||this._expandChart(a,d)}))):(this.chartArray.push(null),e.add(g,"esriCTDisabledRow"),e.add(f,"esriCTHidden"));-1!==this.openPanels.indexOf(m)&&this._toggleSelectedChart(h,!1);0!==d||this.openPanels.length||(this.config.charts.highlightedChartIndex=d,this._toggleSelectedChart(h,!1))}));f=d(".esriCTChartTitle",this.node);0<
f.length&&(c=f[0]);""!==c&&null!==c&&void 0!==c&&z.focus(c)},_setFocusOnChart:function(){var a,b;a=this.config.charts.highlightedChartIndex;a=d(".esriCTChartRow",this.node)[a];b=d(".esriCTResultsPanel")[0];a&&b&&(b.scrollTop=a.offsetTop-81);this.emit("setFocusNodes")},_toggleSelectedChart:function(a,b){var f,c,g;f=d(".esriCTChartContent",a.parentElement)[0];c=q.get(a.parentElement,"chartIndex");g=c.split("Chart")[1];b?(e.add(f,"esriCTHidden"),e.remove(a,"esriCTChartSelected"),-1!==this.openPanels.indexOf(c)&&
this.openPanels.splice(this.openPanels.indexOf(c),1),q.set(a,"aria-expanded","false")):(this.config.charts[g].chartData&&(e.remove(f,"esriCTHidden"),e.add(a,"esriCTChartSelected"),this.chartArray[g]&&this.chartArray[g].resizeChart(0),this.config.charts.highlightedChartIndex===parseInt(g,10)&&this._highlightChart(a,g),q.set(a,"aria-expanded","true")),-1===this.openPanels.indexOf(c)&&this.openPanels.push(c));this.emit("setFocusNodes")},_highlightChart:function(a,b){this.emit("chartSelected",b);d(".esriCTChartHighlighted").length&&
(e.remove(d(".esriCTChartHighlighted")[0],"esriCTSelectedChartBorder"),e.remove(d(".esriCTChartHighlighted")[0],"esriCTChartHighlighted"));e.add(a,"esriCTChartHighlighted");e.add(a,"esriCTSelectedChartBorder");w.set(a,"border-color",this.config.selectedThemeColor)},resizeContents:function(){n.forEach(this.chartArray,k.hitch(this,function(a,b){a&&a.config.chartData&&-1!==this.openPanels.indexOf("Chart"+b)&&a.resizeChart(300)}))},_expandChart:function(a,b){e.contains(a.currentTarget,"esriCTChartSelected")?
e.contains(a.currentTarget,"esriCTChartHighlighted")?this._toggleSelectedChart(a.currentTarget,!0):(this.config.charts.highlightedChartIndex=b,this._highlightChart(a.currentTarget,b)):(this.config.charts.highlightedChartIndex=b,this._toggleSelectedChart(a.currentTarget,!1))}})});