// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/RelatedTableCharts/ChartLayout.html":'\x3cdiv\x3e\r\n    \x3cdiv class\x3d"esriCTLayoutContent" tabindex\x3d"0" aria-labelledby\x3d"${id}title ${id}description"\x3e\r\n        \x3cdiv class\x3d"esriCTLabels"\x3e\r\n            \x3c!-- chart title --\x3e\r\n            \x3cdiv class\x3d"esriCTLayoutHeaderTitle" data-dojo-attach-point\x3d"layoutHeaderTitle" id\x3d"${id}title"\x3e\r\n            \x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"esriCTChartContainer" data-dojo-attach-point\x3d"chartContainer"\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv class\x3d"esriCTLegendContainer" data-dojo-attach-point\x3d"legendContainer"\x3e\r\n            \x3cdiv class\x3d"esriCTLegendNode" data-dojo-attach-point\x3d"legendNode"\x3e\r\n            \x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3c!-- chart description --\x3e\r\n        \x3cdiv class\x3d"esriCTChartDescription" data-dojo-attach-point\x3d"chartDescription" id\x3d"${id}description"\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("jimu/BaseWidgetSetting jimu/utils dojo/dom-attr dojo/dom-construct dojo/dom-style dojo/_base/declare dojo/_base/lang dijit/_WidgetsInTemplateMixin dojo/text!./ChartLayout.html dojox/charting/Chart dojox/charting/plot2d/Pie dojox/charting/action2d/Tooltip dojox/charting/action2d/Highlight dojox/charting/action2d/MoveSlice dojox/charting/plot2d/Spider dojox/charting/widget/SelectableLegend dojox/charting/action2d/Magnify dojo/_base/array dojox/charting/Theme dojo/Evented dojox/charting/plot2d/Bars dojox/charting/axis2d/Default dojox/charting/plot2d/Lines".split(" "),
function(v,w,m,h,g,x,k,y,z,n,A,p,q,B,C,D,u,r,t,E){return x([v,y,E],{baseClass:"jimu-widget-RelatedTableCharts-layout",templateString:z,postCreate:function(){this.inherited(arguments)},startup:function(){this._createChartLayout()},_createChartLayout:function(){this._setNodeValue(this.layoutHeaderTitle,this.config.chartConfig.chartTitle,!0);this._setNodeValue(this.chartDescription,this.config.chartConfig.description,!1);this._initChart()},resizeChart:function(a){this.chart&&setTimeout(k.hitch(this,
function(){"PieChart"!==this.config.chartConfig.chartType?this.chart.resize():this._initChart();this.onChartResize()}),a)},_setNodeValue:function(a,c,b){var d=c;this.config.isPreview||(d=this._getFieldValues(c,this.config.selectedFeature.attributes));d?(d=w.sanitizeHTML(d),m.set(a,"innerHTML",d),b&&m.set(a,"title",d)):g.set(a,"display","none")},_initChart:function(){switch(this.config.chartConfig.chartType){case "BarChart":this._createBarChart();break;case "PieChart":this._createPieChart();break;
case "PolarChart":this._createPolarChart();break;case "LineChart":this._createLineChart();break;default:m.set(this.chartContainer,"innerHTML",this.nls.errMsgNoFeaturesFound)}},_getBarChartContainerHeight:function(){var a=30;0<this.config.chartData.chartSeries.length&&(a=30*this.config.chartData.chartSeries.length);this.config.isPreview?150>=a&&(a+=150):150>=a&&(a+=100);return a+"px"},_createBarChart:function(){var a,c={},b={},c=40,d,f,e={};h.empty(this.chartContainer);c=this._getBarChartContainerHeight();
a=new n(h.create("div",{style:"overflow:hidden; width:100%; height:"+c},this.chartContainer));a.addPlot("default",{type:"Bars",gap:4,minBarSize:10,maxBarSize:15});b=g.get(this.chartDescription,"fontFamily");d=g.get(this.chartDescription,"fontSize");f=g.get(this.chartDescription,"color");c={labels:this.config.chartData.chartLabels,maxLabelCharCount:35,trailingSymbol:"...",natural:!0,majorTickStep:1,minorTicks:!1,fixUpper:!0,includeZero:!1,vertical:!0,titleFontColor:f,titleFont:"normal normal normal "+
d+" "+b,font:"normal normal normal 9px "+b};window.isRTL&&(c.leftBottom=!1,a.setDir("rtl"));b={fixLower:"major",fixUpper:"major",minorTicks:!1,includeZero:!0,titleFontColor:f,titleFont:"normal normal normal "+d+" "+b,font:"normal normal normal 9px "+b};this.config.isPreview?(b.titleGap=5,c.majorTick={length:0},b.majorTick={length:0},c.majorLabels=!1,b.majorLabels=!1,c.minorLabels=!1,b.minorLabels=!1,c.title=this.config.chartConfig.labelYAxis,b.title=this.config.chartConfig.labelXAxis,e.stroke={width:0}):
(new p(a,"default"),c.title=this._getFieldValues(this.config.chartConfig.labelYAxis,this.config.selectedFeature.attributes),b.title=this._getFieldValues(this.config.chartConfig.labelXAxis,this.config.selectedFeature.attributes),e.stroke={width:1});b.titleOrientation="away";a.addAxis("y",c);a.addAxis("x",b);this.config.chartData.selectedTheme&&a.setTheme(this.config.chartData.selectedTheme);this.config.chartData.fill&&(e.fill=this.config.chartData.fill);r.forEach(this.config.chartData.chartSeries,
function(b,c){b.x=c+1;b.y=b.y;a.addSeries(c+1,[b],e,{plot:"default"})},this);new q(a,"default");a.render();this.chart=a;this.onChartCreated()},_createLineChart:function(){var a,c,b,d,f,e,m,l;e={};e.marker=t.defaultMarkers.CIRCLE;e.markerStroke={width:1};h.empty(this.chartContainer);a=new n(h.create("div",{style:"overflow:hidden; width:100%; height:"+(this.config.isPreview?"300px":"270px")},this.chartContainer));b=g.get(this.chartDescription,"fontFamily");d=g.get(this.chartDescription,"fontSize");
f=g.get(this.chartDescription,"color");c={maxLabelCharCount:30,trailingSymbol:"...",natural:!0,vertical:!0,titleGap:0,titleFontColor:f,titleFont:"normal normal normal "+d+" "+b,max:this._calculateMajorTickStep(!0,!0),majorLabels:!0,minorTicks:!0,minorLabels:!0,microTicks:!1,fixLower:"major",fixUpper:"major",majorTickStep:this._calculateMajorTickStep(!0,!1)};this._setLineChartYaxisMin(c);this.config.isPreview||(c.font="normal normal bold 9px "+b);window.isRTL&&(c.leftBottom=!1,a.setDir("rtl"));b={labels:this.config.chartData.chartLabels[0],
maxLabelCharCount:35,trailingSymbol:"...",titleGap:0,titleFontColor:f,titleFont:"normal normal normal "+d+" "+b,font:"normal normal bold "+this._calculateXAxisLabelFontSize(this.config.chartData.chartLabels[0].length)+"px "+b,titleOrientation:"away",rotation:-90,minorLabels:!0,majorLabels:!0,minorTicks:!0,microTicks:!1,max:this.config.chartData.chartLabels[0].length+.5,min:.5};this.config.isPreview?(c.minorLabels=!1,c.majorLabels=!0,c.title=this.config.chartConfig.labelYAxis,b.minorLabels=!0,b.majorLabels=
!0,b.title=this.config.chartConfig.labelXAxis,b.max=11):(c.title=this._getFieldValues(this.config.chartConfig.labelYAxis,this.config.selectedFeature.attributes),b.title=this._getFieldValues(this.config.chartConfig.labelXAxis,this.config.selectedFeature.attributes));e.stroke={width:1};a.addPlot("default",{type:"Lines",markers:!0,styleFunc:k.hitch(this,function(a){return this.config.chartConfig.chartColor&&"ColorByFieldValue"===this.config.chartConfig.chartColor.colorType?(a=this.config.chartConfig.chartColor.colorInfo.layerFieldValues[a])?
{fill:a}:{fill:"#000000"}:this.config.isPreview?{fill:"#0000ff"}:{fill:"#000000"}})});a.addAxis("y",c);a.addAxis("x",b);this.config.chartData.selectedTheme&&a.setTheme(this.config.chartData.selectedTheme);this.config.chartData.fill&&(e.stroke.color=this.config.chartData.fill);l=Object.keys(t.defaultMarkers);l[3]&&l[5]&&this.swap(l,3,5);l[4]&&l[6]&&this.swap(l,4,6);m=l.length;r.forEach(this.config.chartData.chartSeries,k.hitch(this,function(b,c){var d;d=b[0]&&b[0].seriesName?b[0].seriesName:this.nls.ChartSetting.layoutSeriesLabel+
" "+c;if(this.config.chartConfig.chartColor&&"ColorByFieldValue"===this.config.chartConfig.chartColor.colorType||this.config.isPreview)e.stroke.color="#"+Math.floor(16777215*Math.random()).toString(16);this.config.chartData.fill&&(c<m||(c%=m),e.marker=t.defaultMarkers[l[c]]);a.addSeries(d,b,k.clone(e))}));new p(a,"default");new q(a,"default");new u(a,"default");a.render();this.chart=a;g.set(this.legendContainer,"display","block");1<this.config.chartData.chartSeries.length&&this._createChartLegend(a,
!0);this.onChartCreated()},swap:function(a,c,b){var d=a[c];a[c]=a[b];a[b]=d},_calculateXAxisLabelFontSize:function(a){switch(!0){case 20>a:return 9;case 20<=a:return 9;default:return 9}},_calculateMajorTickStep:function(a,c){var b;b=[];a&&this.config.chartData.chartSeries.forEach(k.hitch(this,function(a){a.forEach(k.hitch(this,function(a){c?b.push(a.y):b.push(Math.abs(a.y))}))}));if(0<b.length){a=Math.max.apply(null,b);if(c)return a+1;a/=20;a=Math.round(a)?Math.round(a):a}else a=null;return Math.abs(a)},
_createPieChart:function(){var a,c={};h.empty(this.chartContainer);a=h.create("div",{style:"width:100%; height:100%; overflow:auto"},this.chartContainer);a=new n(a);c={type:A,labels:!0,ticks:!0,fixed:!0,precision:0,labelWiring:"#ccc",labelStyle:"columns",htmlLabels:!0,startAngle:-10,maxLabelCharCount:20,trailingSymbol:"..."};"esriCTEmptyOption"===this.config.chartConfig.labelField&&(c.labels=!1);a.addPlot("default",c);this.config.isPreview||new p(a,"default");this.config.chartData.fill?a.addSeries(this.config.chartConfig.dataSeriesField,
this.config.chartData.chartSeries,{fill:this.config.chartData.fill},{plot:"default"}):a.addSeries(this.config.dataSeriesField,this.config.chartData.chartSeries,{plot:"default"});this.config.chartData.selectedTheme&&a.setTheme(this.config.chartData.selectedTheme);new B(a,"default");new q(a,"default");a.render();this.chart=a;this.onChartCreated()},_createPolarChart:function(){var a,c,b,d=.2,f=!1;this.chart&&this.chart.destroy();h.empty(this.chartContainer);g.set(this.chartContainer,"direction","inherit");
a=h.create("div",{style:"width:100%; height:100%; overflow:hidden"},this.chartContainer);b=g.get(this.chartDescription,"fontFamily");a=new n(a);this.config.chartConfig.showPolygonFill||(d=0);a.addPlot("default",{type:C,labelOffset:-10,divisions:5,seriesFillAlpha:d,markerSize:3,precision:0,spiderType:"polygon",axisFont:"normal normal normal 9px/25px "+b});this.config.chartData.selectedTheme?a.setTheme(this.config.chartData.selectedTheme):this.config.chartConfig.chartColor.colorInfo&&this.config.chartConfig.chartColor.colorInfo.layerField&&
(f=!0);for(d=0;d<this.config.chartData.chartSeries.length;d++)for(c in b=this.config.chartData.chartSeries[d],b)b.hasOwnProperty(c)&&(this.config.chartData.fill?a.addSeries(c,b[c],{fill:this.config.chartData.fill}):b[c].fill?a.addSeries(c,b[c],{fill:b[c].fill,legend:b[c].legendLabel}):a.addSeries(c,b[c]));this.config.isPreview||new p(a,"default");new q(a,"default");new u(a,"default",{duration:800,scale:1.5});a.render();this.chart=a;!this.config.isPreview&&f&&(g.set(this.legendContainer,"display",
"block"),this._createChartLegend(a,!0));this.onChartCreated()},_createChartLegend:function(a,c){setTimeout(k.hitch(this,function(){this.legend&&(this.legend.destroy(),this.legend=null);h.empty(this.legendNode);this.legend=new D({chart:a,horizontal:c},h.create("div",{},this.legendNode));this.emit("setFocusNodes")}),1500)},onChartCreated:function(){},onChartResize:function(){},_getFieldValues:function(a,c){var b="",d,f,e;a=a.replace(/(\n|\r|\r\n)/g,"\x3cbr\x3e");d=a.split("{");for(f=0;f<d.length;f++)if(0===
f)b+=d[f];else if(-1!==d[f].indexOf("}"))for(a=d[f].split("}"),e=0;e<a.length;e++)if(0===e){if(c[a[e]]||0===c[a[e]])b+=c[a[e]]}else b=1===e?b+a[e]:b+("}"+a[e]);else b+="{";return b},_setLineChartYaxisMin:function(a){var c,b,d;c=[];b=[];r.forEach(this.config.chartData.chartSeries,k.hitch(this,function(a){r.forEach(a,k.hitch(this,function(a){0<=a.y&&c.push(a.y);b.push(a.y)}))}));c.length===b.length?a.min=0:(d=Math.min.apply(null,b),a.min=d-1)}})});