// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/on dojo/has dojo/query dojo/Deferred dijit/_WidgetBase dijit/_TemplatedMixin esri/undoManager esri/OperationBase esri/tasks/RelationshipQuery esri/dijit/Popup esri/dijit/PopupMobile esri/graphicsUtils esri/dijit/PopupTemplate jimu/utils jimu/ConfigManager jimu/dijit/DropdownMenu jimu/LayerInfos/LayerInfos".split(" "),function(k,f,l,c,p,r,d,u,v,w,x,y,G,q,z,A,B,C,D,E,F){var g=k([v,w],{baseClass:"related-records-popup-projector",
templateString:"\x3cdiv\x3e\x3cdiv class\x3d'operation-box' data-dojo-attach-point\x3d'operationBox' style\x3d'display: none'\x3e\x3cdiv class\x3d'previos-btn feature-action' data-dojo-attach-point\x3d'previouBtn'data-dojo-attach-event\x3d'click:_onPreviouBtnClick'\x3e\x3c/div\x3e\x3cdiv class\x3d'operation-title' data-dojo-attach-point\x3d'operationTitle'\x3eabc\x3c/div\x3e\x3cdiv class\x3d'add-new-btn' data-dojo-attach-point\x3d'addNewBtn'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'content-box' data-dojo-attach-point\x3d'contentBox'\x3e\x3c/div\x3e\x3c/div\x3e",
popup:null,popupManager:null,undoManager:null,originalFeature:null,originalJimuLayerInfo:null,_temporaryData:null,postCreate:function(){this.undoManager=new x;this.layerInfosObj=F.getInstanceSync();var a=f.getObject("_wabProperties.referToFeatureLayerId",!1,this.originalFeature)||this.originalFeature.getLayer().id;this.originalJimuLayerInfo=this.layerInfosObj.getLayerInfoById(a);this._temporaryData={eventHandles:[],dijits:[]};window.isRTL?c.addClass(this.previouBtn,"icon-arrow-forward"):c.addClass(this.previouBtn,
"icon-arrow-back");a=this._createOperation({feature:this.originalFeature,oriJimuLayerInfo:this.originalJimuLayerInfo});this.showRelatedTables(a);this.popupUIController="esri.dijit.Popup"===this.popup.declaredClass?new g.PopupUIController(this):new g.PopupMobileUIController(this);this.popupUIController.addDomNode(this.domNode)},destroy:function(){this._clearPage();this.undoManager.destroy();this.popupUIController.destroy();this.inherited(arguments)},_getRelatedTableInfoArray:function(a){a=a.data.oriJimuLayerInfo;
var b=new u;a.getRelatedTableInfoArray().then(f.hitch(this,function(a){b.resolve(a)}));return b},_getRelatedRecordsByRelatedQuery:function(a){return a.oriJimuLayerInfo.getRelatedRecords(a.feature,a.destJimuLayerInfo,a.relationshipIndex)},_ignoreCaseToGetFieldObject:function(a,b){var e=null;b&&a&&a.fields&&l.some(a.fields,function(a){if(a.name.toLowerCase()===b.toLowerCase())return e=a,!0});return e},getLocaleDateTime:function(a){return C.localizeDate(new Date(a),{fullYear:!0,formatLength:"medium"})},
_getDisplayTitleOfRelatedRecord:function(a,b,e){var c=a.getInfoTemplate();return(a="popupTitle"===e&&c?"function"===typeof c.title?c.title(b):c.title:this._getDisplayTitleFromPopup(a,b,e))?a:""},_getDisplayTitleFromPopup:function(a,b,c){(a=this._getPopupTemplateWithOnlyDisplayField(a,c))?(b.setInfoTemplate(a),c=this.popupUIController.getDisplayTitle(b),b.setInfoTemplate(null)):c=b.attributes[c];return c},_getPopupTemplateWithOnlyDisplayField:function(a,b){a=a._getCustomPopupInfo(a.layerObject,[b]);
return new B(a)},_canShowRelatedData:function(a){var b=!0;(a=a.getPopupInfo())&&a.relatedRecordsInfo&&(b=!1!==a.relatedRecordsInfo.showRelatedRecords);return b},setPopupContent:function(a){this._clearPage();a.data.destJimuLayerInfo?a.data.relatedFeature||this.showRelatedRecords(a):this.showFeature(a);this.undoManager.peekUndo()?this.popupUIController.changeRefDomNode():this.popupUIController.revertRefDomNode()},showFeature:function(a){var b=a.data,c=b.oriJimuLayerInfo.layerObject,t=f.getObject("_wabProperties.originalLayerName",
!1,c)||b.oriJimuLayerInfo.title,c=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,c),h=this._getDisplayTitleOfRelatedRecord(b.oriJimuLayerInfo,b.feature,c);"popupTitle"!==c&&(h=t+": "+h);this._setOperationTitle(h);f.setObject("_wabProperties.popupInfo.operationDataForListRelatedRecords",null,b.oriJimuLayerInfo.layerObject);b.oriJimuLayerInfo.loadInfoTemplate().then(f.hitch(this,function(c){b.oriJimuLayerInfo.layerObject.infoTemplate||a.data.feature.setInfoTemplate(c);this.popupUIController.setFeature(a.data.feature);
b.oriJimuLayerInfo.layerObject.infoTemplate||a.data.feature.setInfoTemplate(null)}));this.showRelatedTables(a);this.popupManager.initPopupMenu([a.data.feature]);this.popupUIController.updateZoomToBtn([a.data.feature])},showRelatedRecords:function(a){var b=a.data,e=f.getObject("_wabProperties.originalLayerName",!1,b.destJimuLayerInfo.layerObject)||b.destJimuLayerInfo.title;this._setOperationTitle(e);this._clearPage();f.setObject("_wabProperties.popupInfo.operationDataForListRelatedRecords",b,b.destJimuLayerInfo.layerObject);
f.setObject("_wabProperties.popupInfo.originalFeature",this.originalFeature,b.destJimuLayerInfo.layerObject);f.setObject("_wabProperties.popupInfo.layerForActionWithEmptyFeatures",b.destJimuLayerInfo.layerObject,this.popup);this._getRelatedRecordsByRelatedQuery(b).then(f.hitch(this,function(e){0<e.length?this._setTitle(window.jimuNls.popup.relatedRecords):this._setTitle(window.jimuNls.popup.noRelatedRecotds,"font-normal");var h=this._showFieldSelector(b.destJimuLayerInfo);l.forEach(e,function(e,d){e._layer=
b.destJimuLayerInfo.layerObject;var t=this._getDisplayTitleOfRelatedRecord(b.destJimuLayerInfo,e,h);d=c.create("div",{"class":"item record-item "+(0===d%2?"oddLine":"evenLine"),innerHTML:t},this.contentBox);d.relatedRecord=e;d=p(d,"click",f.hitch(this,function(){this._addOperation(a);var c=this._createOperation({feature:e,oriJimuLayerInfo:b.destJimuLayerInfo,relationshipIndex:b.relationshipIndex});this.setPopupContent(c)}));this._temporaryData.eventHandles.push(d)},this);this.popupManager.initPopupMenu(e);
this.popupUIController.updateZoomToBtn(e)}));this.popupUIController.setContent(this.domNode)},showRelatedTables:function(a){this._canShowRelatedData(a.data.oriJimuLayerInfo)&&this._getRelatedTableInfoArray(a).then(f.hitch(this,function(b){0<b.length&&this._setTitle(window.jimuNls.popup.relatedTables);var e={};l.forEach(b,function(b,d){void 0===e[b.id]?e[b.id]=0:e[b.id]++;d=c.create("div",{"class":"item table-item "+(0===d%2?"oddLine":"evenLine"),innerHTML:b.title},this.contentBox);var h=e[b.id];d=
p(d,"click",f.hitch(this,function(){b.getLayerObject().then(f.hitch(this,function(){this._addOperation(a);var c=this._createOperation({feature:a.data.feature,oriJimuLayerInfo:a.data.oriJimuLayerInfo,destJimuLayerInfo:b,relationshipIndex:h});this.setPopupContent(c)}))}));this._temporaryData.eventHandles.push(d)},this)}))},_createOperation:function(a){return new g.Operation({feature:a.feature||null,oriJimuLayerInfo:a.oriJimuLayerInfo||null,destJimuLayerInfo:a.destJimuLayerInfo||null,relatedFeature:a.relatedFeature||
null,relationshipIndex:a.relationshipIndex||0},this)},_addOperation:function(a){this.undoManager.add(a)},_onPreviouBtnClick:function(){this.undoManager.undo()},_clearPage:function(){c.empty(this.contentBox);l.forEach(this._temporaryData.eventHandles,function(a){a&&a.remove&&a.remove()},this);this._temporaryData.eventHandles=[];l.forEach(this._temporaryData.dijits,function(a){a&&a.destroy&&a.destroy()},this);this._temporaryData.dijits=[]},_setTitle:function(a,b){a&&c.create("div",{"class":"title-box "+
(b?b:""),innerHTML:a},this.contentBox)},_setOperationTitle:function(a){c.setAttr(this.operationTitle,"innerHTML",a);c.setAttr(this.operationTitle,"title",a)},_showFieldSelector:function(a){var b="objecid",c=d(".title-box",this.contentBox)[0],g=a.layerObject,h=[];if(!c||!a)return b;var m=a.getPopupInfo();m&&m.title&&h.push({label:window.jimuNls.popup.saveAsPopupTitle,value:"popupTitle"});var k=[];m&&m.fieldInfos?l.forEach(m.fieldInfos,function(a){var b={};a.visible&&(b.name=a.fieldName,b.alias=a.label,
k.push(b))}):k=g.fields;l.forEach(k,function(a){"globalid"!==a.name.toLowerCase()&&"shape"!==a.name.toLowerCase()&&h.push({label:a.alias||a.name,value:a.name})});c=(new E({items:h})).placeAt(c);c.domNode.title=window.jimuNls.popup.chooseFieldTip;var q=f.getObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",!1,g),n=this._ignoreCaseToGetFieldObject(a.layerObject,a.layerObject.displayField||a.layerObject.objectIdField),r=D.getInstance().getAppConfig();q?b=q:"2.3"===r.configWabVersion&&
n&&n.name?b=n.name:m&&m.title?b="popupTitle":n&&n.name?b=n.name:0<h.length&&(b=h[0].value);b&&(c.setHighlightValue(b),f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,g));this._temporaryData.dijits.push(c);a=p(c,"click-item",f.hitch(this,function(a,b){d(".item.record-item",this.contentBox).forEach(f.hitch(this,function(c){f.setObject("_wabProperties.popupInfo.displayFieldOfRelatedRecordList",b,g);var d=this._getDisplayTitleOfRelatedRecord(a,c.relatedRecord,b);c.innerHTML=d}))},
a));this._temporaryData.eventHandles.push(a);return b}});g.Operation=k([y],{constructor:function(a,b){this.data=a;this.relatedRecordsPopupProjector=b},performUndo:function(){this.relatedRecordsPopupProjector.setPopupContent(this)}});g.PopupUIController=k([],{constructor:function(a){this.rrPopupProjector=a;this.popup=a.popup;this.initTempPopup();this._initTempPopupForDisplayTitle();this._initZoomToBtn();this._setScrollable()},initTempPopup:function(){this._tempPopup=new q({},c.create("div"))},_initTempPopupForDisplayTitle:function(){this._tempPopupForDisplayTitle=
new q({},c.create("div"));this._tempPopupForDisplayTitle.show()},destroy:function(){this._tempPopup.destroy();this._tempPopupForDisplayTitle.destroy();this._zoomToBtnClickHandle&&this._zoomToBtnClickHandle.remove&&this._zoomToBtnClickHandle.remove();this._zoomToBtnANode&&c.destroy(this._zoomToBtnANode);this.toucemoveScrollHandle&&this.toucemoveScrollHandle.remove&&this.toucemoveScrollHandle.remove()},addDomNode:function(a){setTimeout(f.hitch(this,function(){c.place(a,this._getRefDomNode(),"after")}),
1)},setFeature:function(a){this._tempPopup.setFeatures([a]);if(a=d(".esriViewPopup",this._tempPopup.domNode)[0])this.setContent(a),c.place(this.rrPopupProjector.domNode,a,"after"),this._unsetScrollable()},setContent:function(a){var b=d(".related-records-popup-projector").parent()[0];b&&b.removeChild(this.rrPopupProjector.domNode);this.popup.setContent(a);this._unsetScrollable()},_setScrollable:function(){var a=d(".contentPane",this.popup.domNode)[0];r("esri-touch")&&a&&(this.toucemoveScrollHandle=
p(a,"touchmove",f.hitch(this,function(b){b.preventDefault();d(".esriViewPopup",this.popup.domNode)[0]&&(b=a.firstChild,b instanceof Text&&(b=a.childNodes[1]),this.rrPopupProjector.domNode&&c.setStyle(this.rrPopupProjector.contentBox,{"-webkit-transition-property":"-webkit-transform","-webkit-transform":"translate("+b._currentX+"px, "+b._currentY+"px)"}))})))},_unsetScrollable:function(){c.setStyle(this.rrPopupProjector.contentBox,{"-webkit-transition-property":"none","-webkit-transform":"none"});
c.setStyle(this.rrPopupProjector.domNode,{"-webkit-transition-property":"none","-webkit-transform":"none"})},getDisplayTitle:function(a){this._tempPopupForDisplayTitle.setFeatures([a]);return(a=d("td.attrValue",this._tempPopupForDisplayTitle.domNode)[0])&&a.innerHTML},_getRefDomNode:function(){return this._getViewPopupDomNode()},_getViewPopupDomNode:function(){return d(".esriViewPopup",this.popup.domNode)[0]},_setPopupTitleInBody:function(){this.rrPopupProjector.undoManager.peekUndo()?this._tempPopup.set("titleInBody",
!1):this._tempPopup.set("titleInBody",!0)},_initZoomToBtn:function(){var a=d(".actionList",this.popup.domNode)[0];this._oldZoomToBtnANdoe=d(".action",a)[0];this._zoomToBtnANode=c.create("a",{"class":"action",style:"display: none",href:"javascript:void(0)"},a);this._zoomToBtn=c.create("span",{innerHTML:window.jimuNls.common.zoomTo},this._zoomToBtnANode);this._showOldZoomToBtn()},_hideZoomToBtn:function(){this._zoomToBtnANode&&c.setStyle(this._zoomToBtnANode,"display","none")},_showZoomToBtn:function(){this._zoomToBtnANode&&
c.setStyle(this._zoomToBtnANode,"display","inline-block")},_hideOldZoomToBtn:function(){this._oldZoomToBtnANdoe&&c.setStyle(this._oldZoomToBtnANdoe,"display","none")},_showOldZoomToBtn:function(){this._oldZoomToBtnANdoe&&c.setStyle(this._oldZoomToBtnANdoe,"display","inline-block")},updateZoomToBtn:function(a){this._hideOldZoomToBtn();!a||1>a.length||!a[0].geometry?this._hideZoomToBtn():(this._showZoomToBtn(),this._zoomToBtnClickHandle&&this._zoomToBtnClickHandle.remove&&this._zoomToBtnClickHandle.remove(),
this._zoomToBtnClickHandle=p(this._zoomToBtn,"click",f.hitch(this,function(){var b=null;try{b=A.graphicsExtent(a)}catch(e){console.error(e)}b&&(this.rrPopupProjector.popupManager.mapManager.map.setExtent(b),this.popup.hide())})))},changeRefDomNode:function(){c.setStyle(this.rrPopupProjector.operationBox,"display","block");c.addClass(this.rrPopupProjector.domNode,"second-page-mode");var a=this._getViewPopupDomNode();a&&c.addClass(a,"second-page-mode")},revertRefDomNode:function(){c.setStyle(this.rrPopupProjector.operationBox,
"display","none");c.removeClass(this.rrPopupProjector.domNode,"second-page-mode");this._hideZoomToBtn();this._showOldZoomToBtn()}});g.PopupMobileUIController=k([g.PopupUIController],{initTempPopup:function(){this._tempPopup=new z({},c.create("div"))},setFeature:function(a){this._tempPopup.setFeatures([a]);a=d(".esriMobileInfoView.esriMobilePopupInfoView",this._tempPopup.domNode)[0];if(a=d(".esriViewPopup",a)[0])this.setContent(a),c.place(this.rrPopupProjector.domNode,a,"after")},updateZoomToBtn:function(){},
_initZoomToBtn:function(){},_getRefDomNode:function(){return d(".esriMobilePopupInfoView .esriMobileInfoViewItem")[1]},_getViewPopupDomNode:function(){var a=d(".esriMobileInfoView.esriMobilePopupInfoView")[0];return d(".esriViewPopup",a)[0]}});return g});