// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/Deferred dojo/_base/lang dojo/_base/array dojo/topic esri/layers/FeatureLayer esri/layers/GraphicsLayer esri/geometry/geometryEngine esri/graphic esri/Color esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleFillSymbol".split(" "),function(w,r,d,h,k,g,x,m,n,p,t,u,v){var l=null,q=w(null,{constructor:function(){window.isBuilder?(k.subscribe("app/mapLoaded",d.hitch(this,this._onMapLoaded)),k.subscribe("app/mapChanged",d.hitch(this,this._onMapChanged))):
(k.subscribe("mapLoaded",d.hitch(this,this._onMapLoaded)),k.subscribe("mapChanged",d.hitch(this,this._onMapChanged)))},_displayLayers:{},setSelectionSymbol:function(a){var b=a.geometryType,e=new t(t.STYLE_CIRCLE,16,null,p.fromArray([0,255,255])),c=new u(u.STYLE_SOLID,p.fromArray([0,255,255]),2),f=new v(v.STYLE_SOLID,c,p.fromArray([0,255,255,.3]));"esriGeometryPoint"===b?a.setSelectionSymbol(e):"esriGeometryPolyline"===b?a.setSelectionSymbol(c):"esriGeometryPolygon"===b&&a.setSelectionSymbol(f)},updateSelectionByFeatures:function(a,
b,e){0<b.length&&(b=h.map(b,d.hitch(this,function(b){var c=null,c=0<=a.graphics.indexOf(b)?new n(b.toJson()):b;c.wabIsTemp=!0;return c})));a.getSelectionSymbol()||this.setSelectionSymbol(a);var c=new r;a._selectHandler({features:b},e,null,null,c);this._isLayerNeedDisplayLayer(a)&&(this._displayLayers[a.id]||(this._displayLayers[a.id]=this._createDisplayLayer(a)),this._updateDisplayLayer(a,b,e));return c},getDisplayLayer:function(a){return this._displayLayers[a]},setSelection:function(a,b){return this.updateSelectionByFeatures(a,
b,g.SELECTION_NEW)},addFeaturesToSelection:function(a,b){return this.updateSelectionByFeatures(a,b,g.SELECTION_ADD)},removeFeaturesFromSelection:function(a,b){return this.updateSelectionByFeatures(a,b,g.SELECTION_SUBTRACT)},clearSelection:function(a){var b=new r;this.clearDisplayLayer(a);a.clearSelection();b.resolve();return b},clearDisplayLayer:function(a){(a=this._displayLayers[a.id])&&a.clear()},getClientFeaturesByGeometry:function(a,b,e){return h.filter(a.graphics,d.hitch(this,function(a){return e?
m.contains(b,a.geometry):m.intersects(b,a.geometry)}))},getUnionGeometryBySelectedFeatures:function(a){var b=null;a=a.getSelectedFeatures();0<a.length&&(b=h.map(a,d.hitch(this,function(a){return a.geometry})),b=m.union(b));return b},_createDisplayLayer:function(a){var b=new x;b.fields=a.fields;b.id="displayLayer_of_"+a.id;this.map.addLayer(b);return b},_updateDisplayLayer:function(a,b,e){var c=this._displayLayers[a.id],f=a.getSelectionSymbol();a.hasWebGLSurface()?this._updateDisplayLayerWebGL(a,c,
f,b,e):(b=a.getSelectedFeatures(),this.clearDisplayLayer(a),h.forEach(b,d.hitch(this,function(a){a.setSymbol(null);a=new n(a.toJson());a.setSymbol(f);c.add(a)})))},_updateDisplayLayerWebGL:function(a,b,e,c,f){f===g.SELECTION_NEW&&(a._selectedFeaturesWebGL={});f===g.SELECTION_NEW||f===g.SELECTION_ADD?h.forEach(c,d.hitch(this,function(b){a._selectedFeaturesWebGL[b.attributes[a.objectIdField]]=b})):f===g.SELECTION_SUBTRACT&&h.forEach(c,d.hitch(this,function(b){b=b.attributes[a.objectIdField];b in a._selectedFeaturesWebGL&&
delete a._selectedFeaturesWebGL[b]}));this.clearDisplayLayer(a);for(var k in a._selectedFeaturesWebGL)c=new n(a._selectedFeaturesWebGL[k].toJson()),c.setSymbol(e),b.add(c)},_isLayerNeedDisplayLayer:function(a){return a.hasWebGLSurface()||!a.getMap()},_onMapLoaded:function(a){this.map=a},_onMapChanged:function(a){this.map=a}});q.getInstance=function(){l||(l=new q,window._selectionManager=l);return l};return q});