// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/keys jimu/utils esri/geometry/geometryEngine esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),function(Q,r,L,R,M,H,t,x,S,N,y,A,I,B,K,T,C,O,P,U,V,W,u){return Q("ClosestInfo",
null,{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,b,c){this.tab=a;this.container=b;this.parent=c;this.graphicsLayer=this.incident=null;this.map=c.map;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.config=c.config;this.parentNode=c.domNode;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,b,c,f){var n=new H;this.incidentCount=a.length;var g=this.parent.config.distanceSettings[this.parent.config.distanceUnits],
d=this.parent.config.maxDistance;b=[];for(var m=0;m<a.length;m++){var e=a[m].geometry;"4326"===e.spatialReference.wkid||e.spatialReference.isWebMercator()?b.push(B.geodesicBuffer(e,d,g)):b.push(B.buffer(e,d,g))}var h=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(h=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var l;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?
(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,b,c,f,h).then(function(a){n.resolve(a)})):(l=new C(this.summaryLayer.url),l.infoTemplate=this.tab.tabLayers[0].infoTemplate,h=[l],this.tab.tabLayers=h,y(l,"load",r.hitch(this,function(){this.summaryLayer=l;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,b,c,f,h).then(function(a){n.resolve(a)})})))):
this.loading||(l=new C(this.tab.tabLayers[0].url),this.loading=!0,y(l,"load",r.hitch(this,function(){this.summaryLayer=l;this.summaryFields=this._getFields(this.summaryLayer);for(var p=this.tab.tabLayers[0].url.split("MapServer/")[1],k=this.parent.map.itemInfo.itemData.operationalLayers,e=0;e<k.length;e++){var d=k[e];if(-1<this.tab.tabLayers[0].url.indexOf(d.url)&&"undefined"!==typeof d.layerObject&&d.layerObject.infoTemplates&&(d=d.layerObject.infoTemplates[p])){l.infoTemplate=d.infoTemplate;break}}h=
[l];this.tab.tabLayers=h;this.loading=!1;this._performQuery(a,b,c,f,h).then(function(a){n.resolve(a)})})))}this.mapServiceLayer||this._performQuery(a,b,c,f,h).then(function(a){n.resolve(a)});return n},_performQuery:function(a,b,c,f,n){var g=new H,d=[],m,e;this.summaryGeoms=b;if(0<b.length)for(a=0;a<b.length;a++)d=b[a],e=u.createDefArray(n,d,this.parent.opLayers,this.tab),m=0===a?d=e:d=m.concat(e);(new M(d)).then(r.hitch(this,function(a){for(var b=0,d=0;d<a.length;d++){var k=a[d][1];isNaN(k)?k&&k.features?
0<k.features.length&&(b+=1):k&&"undefined"!==typeof k.length&&0<k.length&&(b+=1):0<k&&(b+=1)}this.updateTabCount(b,c,f);g.resolve(b)}));return g},updateTabCount:function(a,b,c){this.featureCount=0===parseInt(a,10)?0:a;u.updateTabCount(this.featureCount,b,c,this.baseLabel,this.incidentCount)},updateForIncident:function(a,b,c,f,n,g){this.incidentCount=a.length;this.allFields="undefined"!==typeof n&&"undefined"!==typeof g?n?!0:g:!1;var d="undefined"!==typeof f,m;R.forEach(this.tab.tabLayers,r.hitch(this,
function(e){d&&(m=new H);if(e.url){var g=new C(e.url,{mode:C.MODE_ONDEMAND,infoTemplate:e.infoTemplate});y(g,"load",r.hitch(this,function(){this.tab.tabLayers=[g];d?this.processIncident(a,b,c,f).then(r.hitch(this,function(a){m.resolve(a)}),r.hitch(this,function(a){console.error(a);m.reject(a)})):this.processIncident(a,b,c,f)}))}else d?this.processIncident(a,b,c,f).then(r.hitch(this,function(a){m.resolve(a)}),r.hitch(this,function(a){console.error(a);m.reject(a)})):this.processIncident(a,b,c,f)}));
if(d)return m},processIncident:function(a,b,c,f){this.incidents=a;var n,g="undefined"!==typeof f;g?n=new H:(this.container.innerHTML="",t.add(this.container,"loading"));var d=[];f=this.parent.config.distanceSettings[this.parent.config.distanceUnits];for(var m=[],e=0;e<a.length;e++){var h=a[e].geometry,l;l="4326"===h.spatialReference.wkid||h.spatialReference.isWebMercator()?B.geodesicBuffer(h,b,f):B.buffer(h,b,f);m.push({geometry:h,buffer:l})}(this.graphicsLayer=c)&&this.graphicsLayer.clear();a=[];
b=this.tab.tabLayers[0];c=-1===[null,void 0,""].indexOf(b.id)?b.id:this.tab.layers;c=u.getFilter(c,this.parent.opLayers);var p=this._getFields(b);for(f=0;f<m.length;f++)e=new W,e.returnGeometry=!0,e.outSpatialReference=this.parent.map.spatialReference,e.geometry=m[f].buffer,e.where=c,e.outFields=["*"],"undefined"!==typeof b.queryFeatures&&a.push(b.queryFeatures(e));(new M(a)).then(r.hitch(this,function(a){for(var b=0;b<a.length;b++)if(a[b][0]){var c=a[b][1].features,e=[],f=m[b].geometry;if(c&&0<c.length){for(var k=
0;k<c.length;k++){for(var h=new K(c[k].toJson()),l=u.getDistance(f,h.geometry,this.parent.config.distanceUnits),t={DISTANCE:l},q=0;q<p.length;q++)t[p[q]]=h.attributes[p[q]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?h.attributes.DISTANCE=l:h.attributes=t;e.push(h)}e.sort(u.compareDistance);d.push(e[0])}}else a[b][1]&&a[b][1].message&&console.log(a[b][1].message);d.sort(u.compareDistance);g?this._processResults(d,!0).then(r.hitch(this,function(a){n.resolve(a)})):this._processResults(d)}),
r.hitch(this,function(a){console.error(a);n.reject(a)}));if(g)return n},_processResults:function(a,b){var c,f,n=a&&0<a.length;if(n&&"point"!==a[0].geometry.type)for(var g=a.length-1;0<=g;g--)"undefined"===typeof a[g].geometry.getExtent()&&a.splice(g,1);if(b)c=new H;else if(this.container.innerHTML="",t.remove(this.container,"loading"),n){f=x.create("div",{"class":"SAT_tabPanelContent"},this.container);g=x.create("div",{},f);t.add(g,"SATcolExport");t.add(g,this.parent.lightTheme?"lightThemeBorder":
"darkThemeBorder");var d=x.create("div",{title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSV,"class":"closestDownLoadCSVButton"},g);I.initFirstFocusNode(this.parentNode,d);t.add(d,"btnExport");y(d,"click",r.hitch(this,this._exportToCSV,a));y(d,"keydown",r.hitch(this,function(b){if(!b.shiftKey||b.keyCode!==A.TAB)if(b.keyCode===A.ENTER||b.keyCode===A.SPACE)this._exportToCSV(a,b),setTimeout(function(){d.focus()},500)}));d.focus()}var g=this.parent.nls[this.parent.config.distanceUnits],
m=[],e=220;if(n)for(var h=0;h<a.length;h++){var l=h+1,p=a[h],k=p.geometry,F=k;"point"!==k.type&&(F=k.getExtent().getCenter());var k=p.attributes,B;"point"===this.incidents[0].geometry.type&&(B=Math.round(100*k.DISTANCE)/100+" "+g+" ("+this.parent.nls.approximate+")");var D="",v=0,w=[];if("undefined"!==typeof this.displayFields)for(var C=0;C<this.displayFields.length;C++){var E=this.displayFields[C],G;a:for(G in k)if("DISTANCE"!==G&&3>v&&E.expression===G){var q=u.getFieldValue(G,k[G],this.specialFields,
this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,k,E),q="undefined"!==typeof q&&null!==q?I.stripHTML(q.toString()):"",z="undefined"!==typeof E.label&&""!==E.label?E.label:void 0,J=p._layer&&p._layer.fields?p._layer.fields:this.tab.tabLayers&&this.tab.tabLayers[0]?this.tab.tabLayers[0].fields:void 0;J&&"undefined"===typeof z&&(J=u.getField(J,G))&&(z=J.alias);if("undefined"===typeof z||z in[""," ",null,void 0])z=
G;u.isURL(q)?q='\x3ca href\x3d"'+q+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e":u.isEmail(q)&&(q='\x3ca href\x3d"mailto:'+q+'" style\x3d"color: inherit;"\x3e'+z+"\x3c/a\x3e");D+=E.validLabel?("undefined"!==typeof E.label&&""!==E.label?z+" ":"")+q+"\x3cbr/\x3e":q+"\x3cbr/\x3e";v+=1;w.push({value:-1<q.indexOf(",")?q.replace(",",""):q,label:z});break a}}m.push(w);b||(p=x.create("div",{},f),t.add(p,"SATcolRec"),t.add(p,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),
v=x.create("div",{},p),t.add(v,"SATcolRecBar"),w=x.create("div",{innerHTML:l,tabindex:"0",role:"button","aria-label":this.parent.nls.zoomToFeature+" "+l},v),t.add(w,"SATcolRecNum"),N.set(w,"backgroundColor",this.parent.config.activeColor),y(w,"click",r.hitch(this,this._zoomToLocation,F,null)),y(w,"keydown",r.hitch(this,this._zoomToLocation,F,!0)),I.initLastFocusNode(this.parentNode,w),B&&(w=x.create("div",{innerHTML:B},v),t.add(w,"SATcolDistance")),this.parent.config.enableRouting&&(v=x.create("div",
{"class":"directionsButton",title:this.parent.nls.get_directions,tabindex:"0","aria-label":this.parent.nls.get_directions,role:"button"},v),t.add(v,"SATcolDir"),y(v,"click",r.hitch(this,this._routeToIncident,F,null)),y(v,"keydown",r.hitch(this,this._routeToIncident,F,!0)),I.initLastFocusNode(this.parentNode,v)),D=x.create("div",{"class":"SATcolWrap",innerHTML:D},p),t.add(D,"SATcolInfo"),e+=S.position(p).w,D=new P(P.STYLE_SOLID,new L.fromRgb(this.parent.config.activeMapGraphicColor),1),D=new O(O.STYLE_CIRCLE,
24,D,new L.fromRgb(this.parent.config.activeMapGraphicColor)),p=new U,p.family="Arial",p.size="12px",l=new V(l,p,new T(this.parent.config.fontColor)),l.setOffset(0,-4),this.graphicsLayer.add(new K(F,D,k)),this.graphicsLayer.add(new K(F,l,k)))}if(!b&&n)N.set(f,"width",e);else if(n)return c.resolve({graphics:a,analysisResults:m,context:this}),c},_exportToCSV:function(a,b,c,f){a=u.exportToCSV(a,b,c,f,{type:"closest",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.tab.tabLayers[0],
opLayers:this.parent.opLayers,nlsValue:this.parent.nls.closest,nlsCount:this.parent.nls.count});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=I.getFeatureLayerDefinition(a);this.layerObject=a;a=u.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;this.displayFields=u.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a,b,
c){c.shiftKey&&c.keyCode===A.TAB?(c.stopPropagation(),c.cancelBubble=!0):b&&c.keyCode!==A.ENTER&&c.keyCode!==A.SPACE||this.parent.zoomToLocation(a)},_routeToIncident:function(a,b,c){b&&c.keyCode!==A.ENTER&&c.keyCode!==A.SPACE||this.parent.routeToIncident(a)}})});