// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/keys jimu/utils jimu/dijit/Message esri/graphic esri/layers/FeatureLayer esri/tasks/query ./analysisUtils".split(" "),function(C,D,z,u,v,p,q,r,x,y,w,A,E,t,B,n){return C("GroupedCountInfo",[D],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,popupFields:[],groupedResults:{},specialFields:null,dateFields:{},symbolField:null,
graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,featureCount:0,incidentCount:0,displayCount:!1,allFields:!1,constructor:function(a,d,b){this.tab=a;this.container=d;this.parent=b;this.config=b.config;this.graphicsLayer=null;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers;this.parentNode=b.domNode},queryTabCount:function(a,d,b,f){var g=new v;this.displayCount=f;this.incidentCount=a.length;var e=[this.tab.tabLayers[0]];
this.mapServiceLayer&&1<this.tab.tabLayers.length&&(e=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var c;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,d,b,f,e).then(function(a){g.resolve(a)})):
(c=new t(this.summaryLayer.url),c.infoTemplate=this.tab.tabLayers[0].infoTemplate,e=[c],this.tab.tabLayers=e,x(c,"load",p.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,d,b,f,e).then(function(a){g.resolve(a)})})))):this.loading||(c=new t(this.tab.tabLayers[0].url),this.loading=!0,x(c,"load",p.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);for(var l=this.tab.tabLayers[0].url.split("MapServer/")[1],
h=this.parent.map.itemInfo.itemData.operationalLayers,m=0;m<h.length;m++){var k=h[m];if(-1<this.tab.tabLayers[0].url.indexOf(k.url)&&"undefined"!==typeof k.layerObject)if(k.layerObject.infoTemplates){if(k=k.layerObject.infoTemplates[l]){c.infoTemplate=k.infoTemplate;break}}else if(k.layerObject.infoTemplate){c.infoTemplate=k.layerObject.infoTemplate;break}}e=[c];this.tab.tabLayers=e;this.loading=!1;this._performQuery(a,d,b,f,e).then(function(a){g.resolve(a)})})))}this.mapServiceLayer||this._performQuery(a,
d,b,f,e).then(function(a){g.resolve(a)});return g},_performQuery:function(a,d,b,f,g){var e=new v,c=[],l,h;0<d.length?h=n.getGeoms(d):0<a.length&&(h=n.getGeoms(a));this.summaryGeoms=h;if(0<h.length)for(a=0;a<h.length;a++)c=h[a],d=n.createDefArray(g,c,this.parent.opLayers,this.tab),l=0===a?c=d:c=l.concat(d);(new u(c)).then(p.hitch(this,function(a){for(var d=0,c=0;c<a.length;c++){var h=a[c][1];isNaN(h)?h&&h.features?d+=h.features.length:h&&"undefined"!==typeof h.length&&(d+=h.length):d+=h}this.updateTabCount(d,
b,f);this.queryOnLoad&&p.hitch(this,this._queryFeatures(this.summaryGeoms));e.resolve(d)}));return e},updateTabCount:function(a,d,b){this.displayCount=b;this.featureCount=a;n.updateTabCount(this.featureCount,d,b,this.baseLabel,this.incidentCount)},updateForIncident:function(a,d,b,f,g,e,c){this.incidentCount=a.length;this.allFields="undefined"!==typeof e&&"undefined"!==typeof c?e?!0:c:!1;var l="undefined"!==typeof g,h;this.tabNum=f;l?h=new v:(this.container.innerHTML="",q.add(this.container,"loading"));
this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};if(0<this.tab.tabLayers.length){var m=[];if(0<d.length)m=d;else for(d=0;d<a.length;d++)f=a[d].geometry?a[d].geometry:a[d],"polygon"===f.type&&m.push(f);var k;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],k=new t(this.summaryLayer.url),k.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=k,this.summaryFields=this._getFields(this.tab.tabLayers[0]),l?this._queryFeatures(m,
l).then(function(a){h.resolve(a)}):(this._initGraphicsLayer(b),p.hitch(this,this._queryFeatures(m)))):(k=new t(this.tab.tabLayers[0].url),x(k,"load",p.hitch(this,function(){this.summaryLayer=k;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,e=0;e<d.length;e++){var c=d[e];if(-1<this.tab.tabLayers[0].url.indexOf(c.url)&&"undefined"!==typeof c.layerObject&&c.layerObject.infoTemplates&&
(c=c.layerObject.infoTemplates[a])){k.infoTemplate=c.infoTemplate;break}}this.tab.tabLayers[1]=k;this.summaryLayer=this.tab.tabLayers[1];this.summaryFields=this._getFields(this.tab.tabLayers[1]);l?this._queryFeatures(m,l).then(function(a){h.resolve(a)}):(this._initGraphicsLayer(b),p.hitch(this,this._queryFeatures(m)))})));if(l)return h}},_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,
this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a,d){var b;d&&(b=new v);for(var f=[],g=-1===[null,void 0,""].indexOf(this.tab.tabLayers[0].id)?this.tab.tabLayers[0].id:this.tab.layers,g=n.getFilter(g,this.parent.opLayers),e=new B,c=0;c<a.length;c++)e.geometry=a[c],e.where=g,f.push(this.summaryLayer.queryIds(e));(new u(f)).then(p.hitch(this,
function(a){for(var c,e,f=0;f<a.length;f++)a[f][0]&&(c=a[f][1],e=c=0===f?c:e.concat(c));c?(this.summaryIds=c,0<this.summaryIds.length?d?this._queryFeaturesByIds(d).then(function(a){b.resolve(a)}):this._queryFeaturesByIds():d||this._processResults()):d||this._processResults()}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(d)return b},_queryFeaturesByIds:function(a){var d,b=[];a&&(d=new v);var f=this.summaryLayer.maxRecordCount||1E3,g=this.summaryIds.slice(0,f);this.summaryIds.splice(0,
f);var e=new B,c=-1===[null,void 0,""].indexOf(this.summaryLayer.id)?this.summaryLayer.id:this.tab.layers;e.where=n.getFilter(c,this.parent.opLayers);var l=!1;z.some(this.summaryFields,p.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return l=!0}));a&&(l=!0);this.summaryLayer.supportsAdvancedQueries&&(e.orderByFields=[this.summaryFields[0].field]);e.returnGeometry=l;e.outSpatialReference=this.parent.map.spatialReference;e.outFields=["*"];e.objectIds=g;for(b.push(this.summaryLayer.queryFeatures(e));0<
this.summaryIds.length;)g=this.summaryIds.slice(0,f),this.summaryIds.splice(0,f),e.objectIds=g,b.push(this.summaryLayer.queryFeatures(e));(new u(b)).then(p.hitch(this,function(b){this.summaryFeatures=[];for(var c=0;c<b.length;c++)if(b[c][0]){var e=b[c][1];e.features&&(this.summaryFeatures=this.summaryFeatures.concat(e.features))}a?this._processResults(a).then(p.hitch(this,function(a){this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing");d.resolve(a)})):(this._processResults(),
this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing")}),p.hitch(this,function(a){console.error(a);new A({message:a})}));if(a)return d},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var d=this.summaryFeatures[a];if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var b=n.getFieldValue(this.summaryFields[0].field,d.attributes[this.summaryFields[0].field],
this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,d.attributes),b="undefined"!==typeof b&&null!==b?w.stripHTML(b.toString()):"";b in this.groupedResults?this.groupedResults[b].features.push(d):this.groupedResults[b]={features:[d]}}}},_prepResults:function(){for(var a in this.groupedResults){var d=this.summaryFields[0];d.total=this.groupedResults[a].features.length;this.groupedResults[a].total=
d.total;this.groupedResults[a].type=d.type;this.groupedResults[a].label=d.alias}},_processResults:function(a){this._prepGroupedResults();this._prepResults();var d=this.groupedResults,b=0,f,g;if(a)g=new v;else{this.container.innerHTML="";q.remove(this.container,"loading");if(0===Object.keys(this.groupedResults).length){this.container.innerHTML=this.parent.nls.noFeaturesFound;return}var e=Object.keys(this.groupedResults).length+1;f=r.create("div",{style:"width:"+220*e+"px;"},this.container);q.add(f,
"SAT_tabPanelContent");e=r.create("div",{},f);q.add(e,"SATcolExport");q.add(e,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var c=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSVdownloadCSV,"class":"grpSummaryDownLoadCSVButton"},e);q.add(c,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);c.focus();w.initFirstFocusNode(this.parentNode,c);w.initLastFocusNode(this.parentNode,
c);x(c,"click",p.hitch(this,this._exportToCSV,d));x(c,"keydown",p.hitch(this,function(a){if(!a.shiftKey||a.keyCode!==y.TAB)if(a.keyCode===y.ENTER||a.keyCode===y.SPACE)this._exportToCSV(d,a),setTimeout(function(){c.focus()},500)}))}var l=Object.keys(d).sort(),e=[];this.displayCount&&e.push({total:this.featureCount,a:void 0,info:this.parent.nls.count,c:void 0});for(var h in l){var b=l[h],m=d[b],k=w.stripHTML(b.toString()),b=m.total;isNaN(b)&&(b=0);var b=w.localizeNumber(b),n="pre"===m.type?m.label.trim():
k,k="pre"===m.type?k:m.label.trim(),m=""!==m.label?"colGroupedSummary":"colSummary";if(a)e.push({total:b,a:n,info:""===k?n:k,c:m});else{var t=r.create("div",{"class":"SATcol"},f);q.add(t,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var u=r.create("div",{style:"max-height: 45px;"},t);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:n},u);r.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:k},u);r.create("div",
{"class":m,innerHTML:b},t)}}h=[];f=null!==this.graphicsLayer;!a&&f&&(this.graphicsLayer.clear(),this.tab.tabLayers[1]&&this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(l=0;l<this.summaryFeatures.length;l++)b=this.summaryFeatures[l],this.lyrSymbol?b.symbol=this.lyrSymbol:this.graphicsLayer?this.graphicsLayer.renderer&&(n=this.graphicsLayer.renderer.getSymbol(b),b.symbol=n):this.summaryLayer.renderer&&this.summaryLayer.renderer.getSymbol&&(b.symbol=this.summaryLayer.renderer.getSymbol(b)),
b=b.toJson?new E(b.toJson()):b,!a&&f?(this.graphicsLayer.add(b),this.tab.tabLayers[1].add(b)):h.push(b);!a&&f&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum}));if(a)return g.resolve({graphics:h,analysisResults:e,context:this}),g},_exportToCSV:function(a,d,b,f){a=n.exportToCSV(this.summaryFeatures,d,b,f,{type:"grouped",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,
layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.groupedSummary,nlsCount:this.parent.nls.count,summaryFields:this.summaryFields});this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=w.getFeatureLayerDefinition(a);this.layerObject=a;var d=n.getSkipFields(a),b,f=[];if("undefined"!==typeof this.tab.advStat){var g=this.tab.advStat.stats,e;for(e in g)0<g[e].length&&z.forEach(g[e],function(a){var c={field:a.expression,alias:a.label+
"",type:e,total:0};b=a.expression;f.push(c)})}g=n.getSpecialFields(a);this.dateFields=g.dateFields;this.specialFields=g.specialFields;this.typeIdField=g.typeIdField;this.types=g.types;if(this.allFields)for(g=0;g<a.fields.length;g++){var c=a.fields[g];-1===d.indexOf(c.name)&&b!==c.name&&f.push({field:c.name,alias:c.alias,type:c.type})}return f}})});