// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/query dojo/keys esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query esri/geometry/geometryEngine jimu/utils ./analysisUtils".split(" "),function(S,k,M,J,N,K,v,A,T,O,B,Y,E,P,U,C,Q,R,V,W,X,y,L,q){return S("ProximityInfo",
null,{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,e,f){this.tab=a;this.container=e;this.parent=f;this.graphicsLayer=this.incident=null;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.config=f.config;this.parentNode=f.domNode;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,e,f,h){var d=new K;this.incidentCount=a.length;var b=[this.tab.tabLayers[0]];this.mapServiceLayer&&
1<this.tab.tabLayers.length&&(b=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var c;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,e,f,h,b).then(function(a){d.resolve(a)})):(c=new C(this.summaryLayer.url),
c.infoTemplate=this.tab.tabLayers[0].infoTemplate,b=[c],this.tab.tabLayers=b,B(c,"load",k.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,e,f,h,b).then(function(a){d.resolve(a)})})))):this.loading||(c=new C(this.tab.tabLayers[0].url),this.loading=!0,B(c,"load",k.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);for(var b=this.tab.tabLayers[0].url.split("MapServer/")[1],k=this.parent.map.itemInfo.itemData.operationalLayers,
x=0;x<k.length;x++){var n=k[x];if(-1<this.tab.tabLayers[0].url.indexOf(n.url)&&"undefined"!==typeof n.layerObject&&n.layerObject.infoTemplates&&(n=n.layerObject.infoTemplates[b])){c.infoTemplate=n.infoTemplate;break}}this.tab.tabLayers=[c];this.loading=!1;this._performQuery(a,e,f,h,this.tab.tabLayers).then(function(a){d.resolve(a)})})))}this.mapServiceLayer||this._performQuery(a,e,f,h,b).then(function(a){d.resolve(a)});return d},_performQuery:function(a,e,f,h,d){var b=new K,c=[],g,m;0<e.length?m=
q.getGeoms(e):0<a.length&&(m=q.getGeoms(a));this.summaryGeoms=m;if(0<m.length)for(a=0;a<m.length;a++)c=m[a],e=q.createDefArray(d,c,this.parent.opLayers,this.tab),g=0===a?c=e:c=g.concat(e);(new N(c)).then(k.hitch(this,function(a){for(var c=0,e=0;e<a.length;e++){var d=a[e][1];isNaN(d)?d&&d.features?c+=d.features.length:d&&"undefined"!==typeof d.length&&(c+=d.length):c+=d}this.updateTabCount(c,f,h);b.resolve(c)}));return b},updateTabCount:function(a,e,f){this.featureCount=a;q.updateTabCount(this.featureCount,
e,f,this.baseLabel,this.incidentCount)},updateForIncident:function(a,e,f,h,d,b){this.incidentCount=a.length;this.allFields="undefined"!==typeof d&&"undefined"!==typeof b?d?!0:b:!1;var c="undefined"!==typeof h,g;J.forEach(this.tab.tabLayers,k.hitch(this,function(b){c&&(g=new K);if(b.url){var d=new C(b.url,{mode:C.MODE_ONDEMAND,infoTemplate:b.infoTemplate});B(d,"load",k.hitch(this,function(){this.tab.tabLayers=[d];c?this.processIncident(a,e,f,h).then(k.hitch(this,function(a){g.resolve(a)}),k.hitch(this,
function(a){console.error(a);g.reject(a)})):this.processIncident(a,e,f,h)}))}else c?this.processIncident(a,e,f,h).then(k.hitch(this,function(a){g.resolve(a)}),k.hitch(this,function(a){console.error(a);g.reject(a)})):this.processIncident(a,e,f,h)}));if(c)return g},processIncident:function(a,e,f,h){this.incidents=a;var d=[],b;if(0===e.length)for(var c=0;c<a.length;c++)b=a[c],b=b.geometry?b.geometry:b,"polygon"===b.type?(e.push(b),d.push({geometry:b,buffer:b})):d.push({geometry:void 0,buffer:void 0});
else for(c=0;c<a.length;c++){b=a[c];var g=e[c].geometry?e[c].geometry:e[c];b=b.geometry?b.geometry:b;d.push({geometry:b,buffer:g})}if(0!==e.length){for(a=0;a<d.length;a++)if(e=d[a].buffer,"undefined"!==typeof e)for(b=0;b<d.length;b++)if(b!==a&&(c=d[b].buffer,"undefined"!==typeof c&&y.overlaps(e,c))){d[a].buffer=y.difference(e,c);d[b].buffer=y.difference(c,e);c=y.union(c,e);c=y.difference(c,d[a].buffer);c=y.difference(c,d[b].buffer);if(Array.isArray(d[a].geometry)){if(Array.isArray(d[b].geometry))for(g=
0;g<d[b].geometry.length;g++)d[a].geometry.push(d[b].geometry[g]);else d[a].geometry.push(d[b].geometry);g=d[a].geometry}else if(g=[],g.push(d[a].geometry),Array.isArray(d[b].geometry))for(var m=0;m<d[b].geometry.length;m++)g.push(d[b].geometry[m]);else g.push(d[b].geometry);d.push({geometry:g,buffer:c})}var x,n="undefined"!==typeof h;n?x=new K:(this.container.innerHTML="",v.add(this.container,"loading"));var t=[];this.graphicsLayer=f;f=this.tab.tabLayers[0];var r=this._getFields(f);h=-1===[null,
void 0,""].indexOf(f.id)?f.id:this.tab.layers;h=q.getFilter(h,this.parent.opLayers);a=[];for(e=0;e<d.length;e++)b=new X,b.returnGeometry=!0,b.outSpatialReference=this.parent.map.spatialReference,b.geometry=d[e].buffer,b.where=h,b.outFields=["*"],"undefined"!==typeof f.queryFeatures&&a.push(f.queryFeatures(b));(new N(a)).then(k.hitch(this,function(a){for(var b=0;b<a.length;b++){var c=a[b][1];if(c&&c.features)for(var c=c.features,e=d[b].geometry,f=0;f<c.length;f++){var g=c[f],h=g.geometry,p;if(Array.isArray(e)){var m;
for(p=0;p<e.length;p++){var l=q.getDistance(e[p],h,this.parent.config.distanceUnits);if("undefined"===typeof m||l<m)m=l}p=m;h={DISTANCE:m}}else p=q.getDistance(e,h,this.parent.config.distanceUnits),h={DISTANCE:p};for(l=0;l<r.length;l++)h[r[l]]=g.attributes[r[l]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?g.attributes.DISTANCE=p:g.attributes=h;t.push(g)}}t.sort(q.compareDistance);if(n){var w={graphics:t,analysisResults:t.length,context:this};this._processResults(t,!0).then(k.hitch(this,
function(a){x.resolve(k.mixin(w,a))}))}else this._processResults(t)}),k.hitch(this,function(a){console.error(a);x.reject(a)}));if(n)return x}},_processResults:function(a,e){var f,h,d=a&&0<a.length;if(d&&"point"!==a[0].geometry.type)for(var b=a.length-1;0<=b;b--)"undefined"===typeof a[b].geometry.getExtent()&&a.splice(b,1);if(e)f=new K;else if(this.container.innerHTML="",v.remove(this.container,"loading"),this.graphicsLayer.clear(),d){h=A.create("div",{"class":"SAT_tabPanelContent"},this.container);
b=A.create("div",{},h);v.add(b,"SATcolExport");v.add(b,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var c=A.create("div",{title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSV,"class":"proximityDownLoadCSVButton"},b);v.add(c,"btnExport");c.focus();L.initFirstFocusNode(this.parentNode,c);B(c,"click",k.hitch(this,this._exportToCSV,a));B(c,"keydown",k.hitch(this,function(b){if(!b.shiftKey||b.keyCode!==E.TAB)if(b.keyCode===E.ENTER||b.keyCode===
E.SPACE)this._exportToCSV(a,b),setTimeout(function(){c.focus()},500)}))}var b=this.parent.nls[this.parent.config.distanceUnits],g;"undefined"!==typeof this.tab.advStat&&"undefined"!==typeof this.tab.advStat.stats&&"undefined"!==typeof this.tab.advStat.stats.outFields?g=this.tab.advStat.stats.outFields:(g=[],0<this.tab.tabLayers.length&&J.forEach(this.tab.tabLayers,k.hitch(this,function(a){"undefined"!==typeof a.popupInfo?J.forEach(a.popupInfo.fieldInfos,k.hitch(this,function(a){if(a.visible){var b=
{value:0};b.expression=a.fieldName;b.label=a.label;g.push(b)}})):a.infoTemplate?J.forEach(a.infoTemplate.info.fieldInfos,k.hitch(this,function(a){if(a.visible){var b={value:0};b.expression=a.fieldName;b.label=a.label;g.push(b)}})):J.forEach((a.layerObject?a.layerObject:a).fields,k.hitch(this,function(a){var b={value:0};b.expression=a.name;b.label=a.alias;g.push(b)}))})));var m=220,x=[];if(d)for(var n=0;n<a.length;n++){var t=n+1,r=a[n],w=r.geometry,G=w;"point"!==w.type&&(G=w.getExtent().getCenter());
var w=r.attributes,u=q.getDistanceLabel(w.DISTANCE,b,this.parent.nls.approximate),F="",H=0,z=[];if("undefined"!==typeof g){for(var y=0;y<g.length;y++){var p=g[y],I;for(I in w)if("DISTANCE"!==I&&3>H&&p.expression===I){var l=q.getFieldValue(I,w[I],this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types,this.layerObject&&this.layerObject.renderer?this.layerObject:this.layerDefinition,w,p),l="undefined"!==typeof l&&null!==l?L.stripHTML(l.toString()):"",D="undefined"!==typeof p.label&&
""!==p.label?p.label:void 0,C=r._layer&&r._layer.fields?r._layer.fields:this.tab.tabLayers&&this.tab.tabLayers[0]?this.tab.tabLayers[0].fields:void 0;C&&"undefined"===typeof D&&(C=q.getField(C,I))&&(D=C.alias);if("undefined"===typeof D||D in[""," ",null,void 0])D=I;q.isURL(l)?l='\x3ca href\x3d"'+l+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+D+"\x3c/a\x3e":q.isEmail(l)&&(l='\x3ca href\x3d"mailto:'+l+'" style\x3d"color: inherit;"\x3e'+D+"\x3c/a\x3e");F+=p.validLabel?("undefined"!==typeof p.label&&
""!==p.label?D+" ":"")+l+"\x3cbr/\x3e":l+"\x3cbr/\x3e";H+=1;z.push({label:D,value:l})}}z.push({label:this.parent.nls.distance,value:u});0<z.length&&x.push(z)}e||(r=A.create("div",{},h),v.add(r,"SATcolRec"),v.add(r,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),H=A.create("div",{},r),v.add(H,"SATcolRecBar"),z=A.create("div",{innerHTML:t,tabindex:"0",role:"button","aria-label":this.parent.nls.zoomToFeature+" "+t,isLastElement:a.length-1===n},H),v.add(z,"SATcolRecNum"),a.length-1===n&&
L.initLastFocusNode(this.parentNode,z),O.set(z,"backgroundColor",this.parent.config.activeColor),B(z,"click",k.hitch(this,this._zoomToLocation,G,null)),B(z,"keydown",k.hitch(this,this._zoomToLocation,G,!0)),"point"===this.incidents[0].geometry.type&&(u=A.create("div",{innerHTML:u},H),v.add(u,"SATcolDistance")),this.parent.config.enableRouting&&(u=A.create("div",{"class":"directionsButton",title:this.parent.nls.get_directions,tabindex:"0","aria-label":this.parent.nls.get_directions,role:"button"},
H),v.add(u,"SATcolDir"),B(u,"click",k.hitch(this,this._routeToIncident,G,null)),B(u,"keydown",k.hitch(this,this._routeToIncident,G,!0)),L.initLastFocusNode(this.parentNode,u)),F=A.create("div",{"class":"SATcolWrap",innerHTML:F},r),v.add(F,"SATcolInfo"),m+=T.position(r).w,F=new R(R.STYLE_SOLID,new M.fromString(this.parent.config.activeMapGraphicColor),1),F=new Q(Q.STYLE_CIRCLE,24,F,new M.fromString(this.parent.config.activeMapGraphicColor)),u=new V,u.family="Arial",u.size="12px",t=new W(t,u,new U(this.parent.config.fontColor)),
t.setOffset(0,-4),this.graphicsLayer.add(new P(G,F,w)),this.graphicsLayer.add(new P(G,t,w)))}if(!e&&d)O.set(h,"width",m+"px");else return f.resolve({reportResults:x}),f},_exportToCSV:function(a,e,f,h){a=q.exportToCSV(a,e,f,h,{type:"proximity",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.proximity,nlsCount:this.parent.nls.count,unit:this.parent.nls[this.parent.config.distanceUnits],approximateLabel:this.parent.nls.approximate});
this.summaryLayer=a.summaryLayer;return a.details},_getFields:function(a){this.layerDefinition=L.getFeatureLayerDefinition(a);this.layerObject=a;a=q.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;this.displayFields=q.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a,e,f){f.shiftKey&&f.keyCode===E.TAB||e&&f.keyCode!==E.ENTER&&f.keyCode!==E.SPACE||this.parent.zoomToLocation(a)},
_routeToIncident:function(a,e,f){e&&f.keyCode!==E.ENTER&&f.keyCode!==E.SPACE||this.parent.routeToIncident(a)}})});