// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/DeferredList dojo/Deferred dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/keys jimu/utils jimu/dijit/Message esri/graphic esri/layers/FeatureLayer esri/tasks/query esri/tasks/QueryTask ./analysisUtils".split(" "),function(C,D,y,z,t,n,q,r,u,v,w,A,E,x,B,F,p){return C("SummaryInfo",[D],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],tabNum:null,symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,
featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,allFields:!1,constructor:function(a,e,f){this.tab=a;this.container=e;this.parent=f;this.config=f.config;this.graphicsLayer=null;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers;this.parentNode=f.domNode},queryTabCount:function(a,e,f,b){var h=new t;this.incidentCount=a.length;var g=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(g=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&
this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var c;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,e,f,b,g).then(function(a){h.resolve(a)})):(c=new x(this.summaryLayer.url),c.infoTemplate=this.tab.tabLayers[0].infoTemplate,g=[c],this.tab.tabLayers=g,
u(c,"load",n.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,e,f,b,g).then(function(a){h.resolve(a)})})))):this.loading||(c=new x(this.tab.tabLayers[0].url),this.loading=!0,u(c,"load",n.hitch(this,function(){this.summaryLayer=c;this.summaryFields=this._getFields(this.summaryLayer);for(var k=this.tab.tabLayers[0].url.split("MapServer/")[1],d=this.parent.map.itemInfo.itemData.operationalLayers,m=0;m<d.length;m++){var l=d[m];if(-1<
this.tab.tabLayers[0].url.indexOf(l.url)&&"undefined"!==typeof l.layerObject)if(l.layerObject.infoTemplates){if(l=l.layerObject.infoTemplates[k]){c.infoTemplate=l.infoTemplate;break}}else if(l.layerObject.infoTemplate){c.infoTemplate=l.layerObject.infoTemplate;break}}g=[c];this.tab.tabLayers=g;this.loading=!1;this._performQuery(a,e,f,b,g).then(function(a){h.resolve(a)})})))}this.mapServiceLayer||this._performQuery(a,e,f,b,g).then(function(a){h.resolve(a)});return h},_performQuery:function(a,e,f,b,
h){var g=new t,c=[],k,d;0<e.length?d=p.getGeoms(e):0<a.length&&(d=p.getGeoms(a));this.summaryGeoms=d;if(0<d.length)for(a=0;a<d.length;a++)c=d[a],e=p.createDefArray(h,c,this.parent.opLayers,this.tab),k=0===a?c=e:c=k.concat(e);(new z(c)).then(n.hitch(this,function(a){for(var d=0,e=0;e<a.length;e++){var c=a[e][1];isNaN(c)?c&&c.features?d+=c.features.length:c&&"undefined"!==typeof c.length&&(d+=c.length):d+=c}this.updateTabCount(d,f,b);this.queryOnLoad&&n.hitch(this,this._queryFeatures(this.summaryGeoms));
g.resolve(d)}));return g},updateTabCount:function(a,e,f){this.featureCount=a;p.updateTabCount(this.featureCount,e,f,this.baseLabel,this.incidentCount)},updateForIncident:function(a,e,f,b,h,g,c){this.incidentCount=a.length;this.allFields="undefined"!==typeof g&&"undefined"!==typeof c?g?!0:c:!1;var k="undefined"!==typeof h,d;this.tabNum=b;k?d=new t:(this.container.innerHTML="",q.add(this.container,"loading"));this.summaryIds=[];this.summaryFeatures=[];if(0<this.tab.tabLayers.length){var m=this.summaryGeoms,
l;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],l=new x(this.summaryLayer.url),l.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=l,this.summaryFields=this._getFields(this.tab.tabLayers[0]),k?this._queryFeatures(m,k).then(function(a){d.resolve(a)}):(this._initGraphicsLayer(f),n.hitch(this,this._queryFeatures(m)))):(l=new x(this.tab.tabLayers[0].url),u(l,"load",n.hitch(this,function(){this.summaryLayer=l;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=
this.tab.tabLayers[0].url.split("MapServer/")[1],c=this.parent.map.itemInfo.itemData.operationalLayers,b=0;b<c.length;b++){var e=c[b];if(-1<this.tab.tabLayers[0].url.indexOf(e.url)&&"undefined"!==typeof e.layerObject&&e.layerObject.infoTemplates&&(e=e.layerObject.infoTemplates[a])){l.infoTemplate=e.infoTemplate;break}}this.tab.tabLayers[1]=l;this.summaryLayer=this.tab.tabLayers[1];this.summaryFields=this._getFields(this.tab.tabLayers[1]);k?this._queryFeatures(m,k).then(function(a){d.resolve(a)}):
(this._initGraphicsLayer(f),n.hitch(this,this._queryFeatures(m)))})));if(k)return d}},_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a,
e){var f;e&&(f=new t);for(var b=[],h=-1===[null,void 0,""].indexOf(this.tab.tabLayers[0].id)?this.tab.tabLayers[0].id:this.tab.layers,h=p.getFilter(h,this.parent.opLayers),g=new B,c=0;c<a.length;c++)g.geometry=a[c],g.where=h,b.push(this.summaryLayer.queryIds(g));(new z(b)).then(n.hitch(this,function(a){for(var d,c,b=0;b<a.length;b++)a[b][0]&&(d=a[b][1],c=d=0===b?d:c.concat(d));d?(this.summaryIds=d,0<this.summaryIds.length?e?this._queryFeaturesByIds(e).then(function(a){f.resolve(a)}):this._queryFeaturesByIds():
e||this._processResults()):e||this._processResults()}),n.hitch(this,function(a){console.error(a);new A({message:a})}));if(e)return f},_queryFeaturesByIds:function(a){var e,f=[];a&&(e=new t);var b=this.summaryLayer.maxRecordCount||1E3,h=this.summaryIds.slice(0,b);this.summaryIds.splice(0,b);var g=new B;g.where=p.getFilter(this.summaryLayer.id,this.parent.opLayers);var c=!1;y.some(this.summaryFields,n.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return c=!0}));a&&
(c=!0);g.returnGeometry=c;g.outSpatialReference=this.parent.map.spatialReference;g.outFields=["*"];g.objectIds=h;var k=new F(this.summaryLayer.url);for(f.push(k.execute(g));0<this.summaryIds.length;)h=this.summaryIds.slice(0,b),this.summaryIds.splice(0,b),g.objectIds=h,f.push(k.execute(g));(new z(f)).then(n.hitch(this,function(d){this.summaryFeatures=[];for(var b=0;b<d.length;b++)if(d[b][0]){var c=d[b][1];c.features&&(this.summaryFeatures=this.summaryFeatures.concat(c.features))}a?this._processResults(a).then(n.hitch(this,
function(a){this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing");e.resolve(a)})):(this._processResults(),this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing"));this.SA_SAT_download&&q.replace(this.SA_SAT_download,"download","processing")}),n.hitch(this,function(a){console.error(a);new A({message:a})}));if(a)return e},_prepResults:function(){for(var a=0;a<this.summaryFields.length;a++){var e=this.summaryFields[a],f=e.field,b=e.total;switch(e.type){case "count":b=
this.summaryFeatures.length;break;case "area":b=p.getArea(this.summaryFeatures,this.summaryGeoms,this.config.distanceSettings,this.config.distanceUnits,this.tab.advStat);break;case "length":b=p.getLength(this.summaryFeatures,this.summaryGeoms,this.config.distanceSettings,this.config.distanceUnits,this.tab.advStat);break;case "sum":b=p.getSum(this.summaryFeatures,f);break;case "avg":b=p.getSum(this.summaryFeatures,f)/this.summaryFeatures.length;break;case "min":b=p.getMin(this.summaryFeatures,f);break;
case "max":b=p.getMax(this.summaryFeatures,f)}e.total=b}},_processResults:function(a){this._prepResults();var e,f=this.summaryFields,b=0,h;if(a)e=new t;else{this.container.innerHTML="";q.remove(this.container,"loading");if(0===this.summaryFeatures.length){this.container.innerHTML=this.parent.nls.noFeaturesFound;return}h=r.create("div",{style:"width:"+220*(f.length+1)+"px;"},this.container);q.add(h,"SAT_tabPanelContent");var g=r.create("div",{},h);q.add(g,"SATcolExport");q.add(g,this.parent.lightTheme?
"lightThemeBorder":"darkThemeBorder");var c=r.create("div",{"data-dojo-attach-point":"SA_SAT_download",title:this.parent.nls.downloadCSV,tabindex:"0",role:"button","aria-label":this.parent.nls.downloadCSV,"class":"summaryDownLoadCSVButton"},g);w.initFirstFocusNode(this.parentNode,c);w.initLastFocusNode(this.parentNode,c);q.add(c,[this.parent.isBlackTheme?"btnExportBlack":"btnExport","download"]);c.focus();u(c,"click",n.hitch(this,this._exportToCSV,f));u(c,"keydown",n.hitch(this,function(a){if(!a.shiftKey||
a.keyCode!==v.TAB)if(a.keyCode===v.TAB&&c.focus(),a.keyCode===v.ENTER||a.keyCode===v.SPACE)this._exportToCSV(f,a),setTimeout(function(){c.focus()},500)}))}for(var g=[],k=0;k<f.length;k++){var d=f[k],m=w.stripHTML(d.alias?d.alias:"")+"\x3cbr/\x3e",d=p.formatNumber(d.total,d),b=d.total,d=d.num;if(a)g.push({num:d,info:m,total:b});else{b=r.create("div",{"class":"SATcol"},h);q.add(b,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder");var l=r.create("div",{style:"max-height: 60px;"},b);r.create("div",
{"class":" SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:m},l);r.create("div",{"class":" colSummary",innerHTML:d},b)}}h=[];k=null!==this.graphicsLayer;!a&&k&&(this.graphicsLayer.clear(),this.tab.tabLayers[1].clear());if(this.summaryFeatures)for(m=0;m<this.summaryFeatures.length;m++)d=this.summaryFeatures[m],this.lyrSymbol?d.symbol=this.lyrSymbol:k&&this.graphicsLayer.renderer?(b=this.graphicsLayer.renderer.getSymbol(d),d.symbol=b):this.summaryLayer.renderer&&this.summaryLayer.renderer.getSymbol&&
(d.symbol=this.summaryLayer.renderer.getSymbol(d)),d=d.toJson?new E(d.toJson()):d,!a&&k?(this.graphicsLayer.add(d),this.tab.tabLayers[1].add(d)):h.push(d);!a&&k&&(this.graphicsLayer.setVisibility(!0),this.parent._toggleTabLayersNew(this.tabNum),this.tab.restore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum}));if(a)return e.resolve({graphics:h,analysisResults:g,context:this}),e},_exportToCSV:function(a,e,f,b){a=p.exportToCSV(this.summaryFeatures,e,f,b,{type:"summary",baseLabel:this.baseLabel,
csvAllFields:this.parent.config.csvAllFields,layer:this.summaryLayer,opLayers:this.parent.opLayers,nlsValue:this.parent.nls.summary,nlsCount:this.parent.nls.count,summaryFields:this.summaryFields,calcFields:this.calcFields});this.summaryLayer=a.summaryLayer;return a.details},_getFieldInfoByFieldInfo:function(a,e,f){return this._getFieldInfo(a[e],e,f)},_getFieldInfoByName:function(a,e){var f=["count","area","length","tabCount"],b;for(b in a)if(-1===f.indexOf(b))return this._getFieldInfo(a[b],b,e)},
_getFieldInfo:function(a,e,f){for(var b=0;b<a.length;b++){var h=a[b];if(h.expression&&h.expression===f)return{field:{field:h.expression,alias:h.label,type:e,modify:h.modify,round:h.round,roundPlaces:h.roundPlaces,truncate:h.truncate,truncatePlaces:h.truncatePlaces,total:0},index:b}}},_getFields:function(a){this.layerDefinition=w.getFeatureLayerDefinition(a);this.layerObject=a;var e=p.getSkipFields(a),f=[];if("undefined"!==typeof this.tab.advStat){var b=n.clone(this.tab.advStat.stats);this.tab.advStat.fieldOrder&&
y.forEach(this.tab.advStat.fieldOrder,n.hitch(this,function(a){if((a=a&&a.hasOwnProperty("fieldName")?this._getFieldInfoByFieldInfo(b,a.fieldType,a.fieldName):this._getFieldInfoByName(b,a))&&a.field){var c=b[a.field.type];c.splice(a.index,1);0===c.length&&delete b[a.field.type];f.push(a.field)}}));for(var h in b)0<b[h].length&&y.forEach(b[h],function(a){f.push({field:a.expression,alias:a.label,type:h,modify:a.modify,round:a.round,roundPlaces:a.roundPlaces,truncate:a.truncate,truncatePlaces:a.truncatePlaces,
total:0})})}else{var g;if(a.infoTemplate)g=a.infoTemplate.info.fieldInfos;else if(-1<this.tab.tabLayers[0].url.indexOf("MapServer")){var c=this.tab.tabLayers[0].url.split("MapServer/")[1],k=this.parent.map.itemInfo.itemData.operationalLayers;g=null;for(var d=0;d<k.length;d++){var m=k[d];if(m.layerObject.infoTemplates&&(m=m.layerObject.infoTemplates[c])){g=m.infoTemplate.info.fieldInfos;break}}}else g=a.fields;g||(g=a.fields);for(c=0;c<g.length;c++)if(k=g[c],"undefined"!==typeof a.fields){var d=a.fields[c].type,
l;k.name===a.objectIdField||"esriFieldTypeDouble"!==d&&"esriFieldTypeInteger"!==d&&"esriFieldTypeSmallInteger"!==d||("undefined"!==typeof k.visible?k.visible&&(l={field:k.fieldName,alias:k.label,type:"sum",total:0}):l={field:k.name,alias:k.alias,type:"sum",total:0},l&&-1===e.indexOf(l.field)&&f.push(l),l=null)}}this.calcFields=n.clone(f);if(this.allFields)for(g=0;g<a.fields.length;g++){l=a.fields[g];c=!0;k=0;b:for(;k<f.length;k++)if(l.name===f[k].field){c=!1;break b}-1===e.indexOf(l.name)&&c&&f.push({field:l.name,
alias:l.alias,type:l.type})}a=p.getSpecialFields(a);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;return f}})});