// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Screening/shapefile/shapefile.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"esriCTUploadShapefileText"\x3e\r\n    ${label}\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"esriCTUploadShapefileButtonDiv"\x3e\r\n    \x3cform enctype\x3d"multipart/form-data" method\x3d"post" data-dojo-attach-point\x3d"uploadForm"\x3e\r\n      \x3cdiv class\x3d\'jimu-btn jimu-float-trailing jimu-trailing-margin1 esriCTUploadShapefileButton\'\r\n        title\x3d"${nls.shapefileWidget.uploadShapefileButtonText}" data-dojo-attach-point\x3d"uploadShapefileButton"\r\n        role\x3d"button" aria-label\x3d"${nls.shapefileWidget.uploadShapefileButtonText}" tabindex\x3d"0"\x3e\r\n        ${nls.shapefileWidget.uploadShapefileButtonText}\r\n      \x3c/div\x3e\r\n      \x3cinput title\x3d"${nls.shapefileWidget.uploadShapefileButtonText}" data-dojo-attach-point\x3d"shapefileInput"\r\n        type\x3d"file" name\x3d"file" accept\x3d".zip" tabindex\x3d"-1" class\x3d"esriCTHidden" /\x3e\r\n    \x3c/form\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/text!./shapefile.html dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/on dojo/json dojo/Evented esri/layers/FeatureLayer esri/request jimu/BaseWidget jimu/dijit/Message dijit/focus dojo/keys dojo/_base/event jimu/utils".split(" "),function(h,k,l,b,c,m,n,p,q,r,t,d,e,f,g){return h([r,l,n],{baseClass:"jimu-widget-screening-shapefile",templateString:k,_uploadFormChange:null,nls:null,config:null,map:null,constructor:function(a){this.map=this.config=this.nls=this._uploadFormChange=
null;b.mixin(this,a)},postCreate:function(){this._attachEventsToUploadShapefileButton();this._attachFileInputOnChangeEvent()},_attachEventsToUploadShapefileButton:function(){this.own(c(this.uploadShapefileButton,"click",b.hitch(this,function(a){f.stop(a);this.shapefileInput.click()})));this.own(c(this.uploadShapefileButton,"keydown",b.hitch(this,function(a){if(a.keyCode===e.ENTER||a.keyCode===e.SPACE)f.stop(a),this.shapefileInput.click();a.keyCode!==e.ESCAPE||this.isSingleTabSelected||(f.stop(a),
this.emit("focusLastSelectedTab"))})))},_attachFileInputOnChangeEvent:function(){var a;this._uploadFormChange&&this._uploadFormChange.remove();this._uploadFormChange=this.own(c.pausable(this.uploadForm,"change",b.hitch(this,function(b){this.loadingIndicator.show();a={filename:b.target.value.toLowerCase()};this._generateFeatureCollection(a)})))},_generateFeatureCollection:function(a){a=a.filename.split(".");a=a[0].replace("c:\\fakepath\\","");this._requestFeatureCollection({params:{name:a,targetSR:this.map.spatialReference,
maxRecordCount:this.config.maxFeaturesForAnalysis}})},_requestFeatureCollection:function(a){var c,d;a={filetype:"shapefile",publishParameters:m.stringify(a.params),f:"json"};q({url:this.config.generateFeatureCollectionURL,content:a,form:this.uploadForm,handleAs:"json",load:b.hitch(this,function(a){a.error?(this.loadingIndicator.hide(),this._showMessage(this.nls.shapefileWidget.unableToUploadShapefileMessage)):(c=a.featureCollection.layers[0],this._uploadFormChange[0].pause(),d=new p(c),this.shapefileInput.value=
"",this._uploadFormChange[0].resume(),this.emit("onShapefileUpload",d),this.loadingIndicator.hide())}),error:b.hitch(this,function(a){this._uploadFormChange[0].pause();this.shapefileInput.value="";this._uploadFormChange[0].resume();this.loadingIndicator.hide();400===a.code?a.details&&0<a.details.length?this._showMessage(this.nls.shapefileWidget.unableToUploadShapefileMessage+" "+a.details[0]):this._showMessage(this.nls.shapefileWidget.unableToUploadShapefileMessage+" "+a.message):this._showMessage(this.nls.shapefileWidget.unableToUploadShapefileMessage+
" "+a.message)})})},_showMessage:function(a){(new t({message:a})).message=a},focusFirstNodeOfSelectedTab:function(){this._focusOutCurrentNode();d.focus(this.uploadShapefileButton)},setFirstFocusNode:function(a){g.initFirstFocusNode(a,this.uploadShapefileButton)},_focusOutCurrentNode:function(){d.curNode&&d.curNode.blur()},setLastFocusNode:function(a){g.initLastFocusNode(a,this.uploadShapefileButton)}})});