// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/html dojo/on dojo/aspect dojo/keys dijit/focus dojo/topic jimu/utils jimu/LayoutManager".split(" "),function(q,n,f,k,e,r,c,l,p,d,t){return q(null,{_layoutManager:null,_focusedTab:null,focusToDisplay:!1,hasBeenActivated:!1,postCreate:function(){this.inherited(arguments);this._layoutManager=t.getInstance();this.focusToDisplay=!0;this.hasBeenActivated=this.config.initiallyExpand;this.own(e(this.domNode,"keydown",f.hitch(this,function(a){k.hasClass(a.target,
this.baseClass)&&a.keyCode===c.ENTER&&(this.focusToDisplay=!1,this.hasBeenActivated=!0,this.showing||(this.widgetManager.activateWidget(this),this._switchTable()))})));this.own(e(this.domNode,"focus",f.hitch(this,function(){d.isInNavMode()&&this.focusToDisplay&&!this.showing&&(this.widgetManager.activateWidget(this),this._switchTable())})));this.own(e(this.domNode,"blur",f.hitch(this,function(){d.isInNavMode()&&this.focusToDisplay&&this.showing&&(this.hasBeenActivated||this._switchTable());this.focusToDisplay=
!0;this.showing||(this.hasBeenActivated=!1)})));this.own(p.subscribe(this.id+"_table_created",f.hitch(this,function(a){this._applyA11y2Grid(a&&a.grid,a&&a.context)})),p.subscribe(this.id+"_toolbar_created",f.hitch(this,function(a){this._applyA11y2Toolbar(a&&a.toolbar,a&&a.context)})))},applyA11y:function(){this._isOnlyTable()&&k.removeAttr(this.domNode,"tabindex");this.switchBtn&&this.own(e(this.switchBtn,"keydown",f.hitch(this,function(a){a.keyCode===c.ENTER&&(this._switchTable(),this.focusToDisplay=
this.showing,this.__focus2WidgetNode())})));this.tabContainer&&this.tabContainer.hasChildren()?this._applyA11y2TabContainer(this.tabContainer):this.NoTableMessageDiv&&(k.setAttr(this.NoTableMessageDiv,{tabindex:"0"}),d.initFirstFocusNode(this.domNode,this.NoTableMessageDiv),d.initLastFocusNode(this.domNode,this.NoTableMessageDiv),this.own(e(this.NoTableMessageDiv,"keydown",f.hitch(this,function(a){a.keyCode===c.ESCAPE&&this.__escape2WidgetSwitch(a)}))),this._isOnlyTable()&&l.focus(this.NoTableMessageDiv))},
_applyA11y2TabContainer:function(a){if(a){var b=this,m=function(g){g&&(n.forEach(a.tablist.getChildren(),function(a){!a.active&&a.closeButton&&a.id!==g.id&&k.setAttr(a.closeNode,"tabindex",-1)}),k.setAttr(g.closeNode,"tabindex",0))},u=a.tablist.onkeydown;a.tablist.onkeydown=function(a,m){var h=null,f=!1;switch(a.keyCode){case c.LEFT_ARROW:case c.UP_ARROW:a._djpage||(h=!1);break;case c.PAGE_UP:a.ctrlKey&&(h=!1);break;case c.RIGHT_ARROW:case c.DOWN_ARROW:a._djpage||(h=!0);break;case c.PAGE_DOWN:a.ctrlKey&&
(h=!0);break;case c.HOME:for(var g=this.getChildren(),d=0;d<g.length;d++){var e=g[d];if(!e.disabled){l.focus(e.focusNode);b._focusedTab=e;break}}a.stopPropagation();a.preventDefault();break;case c.END:g=this.getChildren();for(d=g.length-1;0<=d;d--)if(e=g[d],!e.disabled){l.focus(e.focusNode);b._focusedTab=e;break}a.stopPropagation();a.preventDefault();break;case c.DELETE:case 87:this._currentChild.closable&&(a.keyCode==c.DELETE||a.ctrlKey)&&(a.stopPropagation(),a.preventDefault());break;case c.ENTER:case c.SPACE:b.tabForwardStep=
0;break;case c.ESCAPE:"Close"===a.target.title?b._focusedTab&&l.focus(b._focusedTab.focusNode):b.__escape2WidgetSwitch(a);a.stopPropagation();a.preventDefault();break;case c.TAB:if(b.isLoading()){a.stopPropagation();a.preventDefault();return}break;default:f=!0}if(null!==h){this.isLeftToRight()||this.tabPosition&&!/top|bottom/.test(this.tabPosition)||(h=!h);var g=this.getChildren(),d=n.indexOf(g,this.pane2button(b._focusedTab?b._focusedTab.page&&b._focusedTab.page.id:this._currentChild.id)),e=g[d],
k;do d=(d+(h?1:g.length-1))%g.length,k=g[d];while(k.disabled&&k!==e);b._focusedTab=k;l.focus(b._focusedTab.focusNode);a.stopPropagation();a.preventDefault()}f&&u.apply(this,arguments)};if(a.hasChildren()){n.forEach(a.getChildren(),f.hitch(this,function(a){a.controlButton.checked||k.setAttr(a.controlButton.focusNode,"aria-selected","false");a.closable&&k.setAttr(a.controlButton.closeNode,"role","button")}));var h=a.tablist.getChildren()[0];this._focusedTab=h;d.initFirstFocusNode(this.domNode,h.focusNode);
h.closeNode&&m(h);!this._isOnlyTable()||"LaunchpadTheme"!==this.appConfig.theme.name&&"BillboardTheme"!==this.appConfig.theme.name||l.focus(h)}this.own(r.after(a,"selectChild",function(){var a=f.getObject("controlButton",!1,this.selectedChildWidget);a&&(d.initFirstFocusNode(b.domNode,a.focusNode),a.closeNode&&m(a));b._focusedTab=a}),e(a.tablist,"blur",f.hitch(this,function(){this._focusedTab=null})))}},_applyA11y2Toolbar:function(a,b){a&&(f.mixin(a,{_onLeftArrow:function(){},_onRightArrow:function(){}}),
this.own(e(a,"keydown",f.hitch(this,function(b){if(b.keyCode===c.TAB){if(b.shiftKey){if(b.target.id===a._getFirstFocusableChild().id)return}else if(b.target.id===a._getLastFocusableChild().id)return;b.shiftKey?a.focusPrev():a.focusNext();b.stopPropagation();b.preventDefault()}else b.keyCode===c.ESCAPE&&this.__escape2ActiveTab(b)}))),b&&b.toggleColumnsMenuItem&&this.own(e(b.toggleColumnsMenuItem,"click",f.hitch(this,function(a){d.isInNavMode()&&this.__applyA11y2GridHiderMenu(this._activeTable&&this._activeTable.grid)}))))},
_applyA11y2Grid:function(a,b){if(a&&a.hiderToggleNode&&a.hiderMenuNode){var m=a.hiderToggleNode,l=a.hiderMenuNode;d.initLastFocusNode(this.domNode,m);a._customEvtHandlersInitialized||(this.own(e(a,"keydown",f.hitch(this,function(a){a.keyCode===c.ESCAPE&&this.__escape2ActiveTab(a)})),e(m,"keydown",f.hitch(this,function(b){if(b.keyCode===c.SPACE||b.keyCode===c.ENTER)a._toggleColumnHiderMenu(),this.__applyA11y2GridHiderMenu(a),b.stopPropagation(),b.preventDefault()})),e(l,"keydown",f.hitch(this,function(b){b.keyCode===
c.ESCAPE&&(m.focus(),a._hiderMenuOpened&&a._toggleColumnHiderMenu(b),b.stopPropagation(),b.preventDefault())}))),a._customEvtHandlersInitialized=!0);this._focusedTab&&this._focusedTab.checked&&b&&k.setAttr(this._focusedTab.focusNode,"aria-labelledby",this._focusedTab.focusNode.id+" "+this.id+"_"+b.id+"_footer")}},__escape2WidgetSwitch:function(a){this.switchBtn?this.switchBtn.focus():d.isDomFocusable(this.domNode)?this.__focus2WidgetNode():this._controllerDiv&&this._controllerDiv.focus();if(this.closeable&&
this._isOnlyTable()&&this.widgetManager){var b;n.some(this._layoutManager&&this._layoutManager.layoutManager&&this._layoutManager.layoutManager.onScreenWidgetIcons,f.hitch(this,function(a){if(a&&a.widgetConfig&&a.widgetConfig.id===this.id)return b=a,!0}));b?b.domNode.focus():this.widgetManager.closeWidget(this)}a&&(a.stopPropagation(),a.preventDefault())},__focus2WidgetNode:function(){this.domNode.focus()},__escape2ActiveTab:function(a){d.focusFirstFocusNode(this.domNode);a&&(a.stopPropagation(),
a.preventDefault())},__applyA11y2GridHiderMenu:function(a){if(a&&a._hiderMenuOpened&&(a=a.hiderMenuNode,a.children&&0<a.children.length)){var b=a.children[0],c=a.children[a.children.length-1],e=b.querySelector("input");d.initFirstFocusNode(a,b.querySelector("input"));d.initLastFocusNode(a,c.querySelector("input"));e&&e.focus()}}})});