// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred dojo/promise/all jimu/portalUtils jimu/portalUrlUtils jimu/Role esri/request esri/kernel esri/lang ./PortalAnalysis".split(" "),function(q,d,l,f,r,m,g,t,n,u,p,v){var h=null,k=q([],{userRole:null,userPortalUrl:null,portalAnalysis:null,portalSelf:null,portalUrl:null,licenseDef:null,licenseLevel:null,federatedServers:null,constructor:function(a){this.portalUrl=a},_clearLoadedInfo:function(){this.portalUrl=this.portalSelf=this.portalAnalysis=
this.userPortalUrl=this.userRole=null},loadPrivileges:function(a){a&&this.portalUrl!==a&&(this._clearLoadedInfo(),this.portalUrl=a);if(this._privilegeLoaded())return a=new f,a.resolve(!0),a;a=m.getPortal(this.portalUrl);var b=new f;(a.haveSignIn()?this._loadUserInfo(a):this._signIn(a)).then(d.hitch(this,function(a){a&&this.isPortal()?this.checkAnalysisLicense().then(function(){b.resolve(a)}):b.resolve(a)}));return b},_signIn:function(a){return a.loadSelfInfo().then(d.hitch(this,function(a){var b=
m.getPortal(a.portalHostname);return null===b?!1:b.signIn().then(d.hitch(this,function(a){return this._loadUserInfo(b,a)}),function(){return!1})}),function(){return!1})},_registerOrgCredential:function(a,b){b=g.getStandardPortalUrl(b);a=d.clone(a.toJson());b+="/sharing/rest";a.server=b;a.resources=[b];u.id.registerToken(a)},_loadUserInfo:function(a,b){var e=a.loadSelfInfo();a=a.getHelpMap();return r([e,a]).then(d.hitch(this,function(a){var c=a[0];a=a[1]&&a[1].helpMap;var e={};a&&(e.helpMap=a.v&&a.m?
a:{v:"1.0",m:a});this.userPortalUrl=c.urlKey?c.urlKey+"."+c.customBaseUrl:this.portalUrl;return c&&c.user?(this.userRole=new t({id:c.user.roleId?c.user.roleId:c.user.role,role:c.user.role}),c.user.privileges&&this.userRole.setPrivileges(c.user.privileges),this.portalSelf=d.mixin(c,e),b&&this._registerOrgCredential(b,this.userPortalUrl),this.portalAnalysis=new v(this.userRole,this.portalSelf),!0):!1}),function(){return!1})},_privilegeLoaded:function(){return null!==this.portalSelf},getUser:function(){return this._privilegeLoaded()?
this.portalSelf.user:null},isAdmin:function(){return this._privilegeLoaded()?this.userRole.isAdmin():!1},getUserPortal:function(){return this._privilegeLoaded()?this.userPortalUrl:null},isPortal:function(){return null!==this.portalSelf&&!0===this.portalSelf.isPortal},canPerformAnalysis:function(){return null!==this.portalAnalysis&&this.portalAnalysis.canPerformAnalysis()},canPerformSpatialAnalytics:function(){return null!==this.portalAnalysis&&this.portalAnalysis.canPerformSpatialAnalytics()},canPerformGeoAnalytics:function(){return null!==
this.portalAnalysis&&this.portalAnalysis.canPerformGeoAnalytics()},canPerformRasterAnalysis:function(){return null!==this.portalAnalysis&&this.portalAnalysis.canPerformRasterAnalysis()},canPerformGeoEnrichment:function(){return null!==this.portalAnalysis&&this.portalAnalysis._canPerformGeoEnrichment()},hasPrivileges:function(a){var b=a,e=!1;d.isArray(a)&&0<=a.indexOf("svradvanced")&&(e=!0,b=l.filter(a,function(a){return"svradvanced"!==a}));return e&&this.isPortal()?this.isAdvanceLicense()&&null!==
this.portalAnalysis&&this.portalAnalysis.hasPrivileges(b):null!==this.portalAnalysis&&this.portalAnalysis.hasPrivileges(b)},isAdvanceLicense:function(){return"svradvanced"===this.licenseLevel},getFederatedServers:function(){var a=new f;if(this.isPortal()&&this.userRole&&!this.federatedServers){var b=g.getSharingUrl(this.portalUrl)+"/portals/"+this.portalSelf.id+"/servers";n({url:b,content:{f:"json"}}).then(d.hitch(this,function(b){this.federatedServers=b.servers;a.resolve(this.federatedServers)}),
d.hitch(this,function(b){console.log("cannot load federated servers",b);this.federatedServers=[];a.resolve([])}))}else a.resolve(this.federatedServers);return a},getLicense:function(a){var b=new f,e;if(0===a.length)return b.resolve(null),b;a=l.filter(a,function(a){return"HOSTING_SERVER"===a.serverRole},this);0<a.length&&(e=a[0]);a=g.getSharingUrl(this.portalUrl);n({url:a+"/portals/"+this.portalSelf.id+"/servers/"+e.id,content:{f:"json"}}).then(d.hitch(this,function(a){var c=d.mixin({},a);a=p.isDefined(a.edition)||
p.isDefined(a.level)?null:"svradvanced";this.licenseLevel=c.edition?c.edition.name:a;b.resolve({licenseInfo:c,licenseLevel:this.licenseLevel})}),d.hitch(this,function(a){console.log("cannot load hostingServer info",a);b.resolve({})}));return b},checkAnalysisLicense:function(){var a=new f;this.licenseDef?this.licenseDef.isResolved()?a.resolve("svradvanced"===this.licenseLevel):this.licenseDef.then(d.hitch(this,function(){a.resolve("svradvanced"===this.licenseLevel)})):(this.licenseDef=this.getFederatedServers().then(d.hitch(this,
function(a){return this.getLicense(a)})),this.licenseDef.then(d.hitch(this,function(){return a.resolve("svradvanced"===this.licenseLevel)})));return a}});k.getInstance=function(a){null===h&&(h=new k(a));return h};return k});