// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Query/RelatedRecordsResult.html":'\x3cdiv\x3e\r\n  \x3cdiv role\x3d"button" tabindex\x3d"0" class\x3d"popup-menu-button related-records-action-button not-visible" data-dojo-attach-point\x3d"btnAction" data-dojo-attach-event\x3d"click:_onBtnMenuClicked,keydown:_onBtnMenuKeydown"\x3e\x3c/div\x3e\r\n  \x3cdiv tabindex\x3d"0" class\x3d"noresult-tip not-visible" data-dojo-attach-point\x3d"noResultTip" data-dojo-attach-event\x3d"keydown:_onNoResultTipKeydown"\x3e${nls.noResult}\x3c/div\x3e\r\n  \x3cdiv class\x3d"content not-visible" data-dojo-attach-point\x3d"content" data-dojo-attach-event\x3d"click:_onContentClicked,keydown:_onContentKeydown"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/query dojo/keys dojo/Evented dojo/_base/html dojo/_base/lang dojo/_base/array dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./RelatedRecordsResult.html esri/dijit/PopupRenderer esri/layers/FeatureLayer esri/renderers/SimpleRenderer jimu/utils jimu/symbolUtils jimu/BaseFeatureAction jimu/dijit/Popup jimu/dijit/FeatureActionPopupMenu jimu/dijit/SymbolChooser jimu/FeatureActionManager".split(" "),function(l,g,r,c,f,h,t,u,v,w,x,y,p,q,k,
m,z,A,B,C,D){return t([u,v,w,r],{baseClass:"related-records-result",templateString:x,popupMenu:null,featureActionManager:null,featureSet:null,layer:null,map:null,layerDefinition:null,nls:null,config:null,postCreate:function(){this.inherited(arguments);this.popupMenu=B.getInstance();this.featureActionManager=D.getInstance();this.btnAction.title=window.jimuNls.featureActions.featureActions;if("Table"!==this.layerDefinition.type){this.layer=new p({layerDefinition:{type:this.layerDefinition.type,geometryType:this.layerDefinition.geometryType,
fields:this.layerDefinition.fields,typeIdField:this.layerDefinition.typeIdField,types:this.layerDefinition.types}});var a=k.getTypeByGeometryType(this.layerDefinition.geometryType),b=null;"point"===a?b=m.getDefaultMarkerSymbol():"polyline"===a?b=m.getDefaultLineSymbol():"polygon"===a&&(b=m.getDefaultFillSymbol());b&&(a=new q(b),this.layer.setRenderer(a));this.map.addLayer(this.layer)}else this.layer=new p({layerDefinition:{type:this.layerDefinition.type,fields:this.layerDefinition.fields,typeIdField:this.layerDefinition.typeIdField,
types:this.layerDefinition.types}})},destroy:function(){this.layer&&this.map.removeLayer(this.layer);this.layer=null;this.inherited(arguments)},setResult:function(a,b){this.layer&&this.layer.clear();this.featureSet=b;if(0<b.features.length){h.forEach(b.features,f.hitch(this,function(b,d){this.layer&&this.layer.add(b);this._createItem(a,b,d)}));var d=l(".item-title",this.content);this.lastFocusItem=d[d.length-1];c.removeClass(this.btnAction,"not-visible");c.addClass(this.noResultTip,"not-visible");
c.removeClass(this.content,"not-visible");b.geometryType&&k.zoomToFeatureSet(this.map,b)}else c.addClass(this.btnAction,"not-visible"),c.removeClass(this.noResultTip,"not-visible"),c.addClass(this.content,"not-visible"),this.lastFocusItem=this.noResultTip},_onNoResultTipKeydown:function(a){a.keyCode!==g.TAB||a.shiftKey||(a.preventDefault(),this.emit("focus-result-header"))},getLayer:function(){return this.layer},showLayer:function(){this.layer&&this.layer.show()},hideLayer:function(){this.layer&&
this.layer.hide()},_createItem:function(a,b,d){var e=a.getTitle(b)||"",n="";d===this.featureSet.features.length-1&&(n='data-isLastItem\x3d"true"');d=c.toDom('\x3cdiv class\x3d"item"\x3e\x3cdiv class\x3d"item-title" '+n+' role\x3d"button" tabindex\x3d"0"\x3e'+e+'\x3c/div\x3e\x3cdiv class\x3d"item-content" '+n+' tabindex\x3d"0"\x3e\x3c/div\x3e\x3c/div\x3e');e=l(".item-content",d)[0];a=new y({template:a,graphic:b,chartTheme:a.chartTheme});c.place(a.domNode,e);a.startup();c.place(d,this.content)},_onContentClicked:function(a){a=
a.target||a.srcElement;var b=null;if(b=c.hasClass(a,"item-title")?a:k.getAncestorDom(a,function(a){return c.hasClass(a,"item-title")},this.content)){var d=b.parentNode;c.toggleClass(d,"selected");var e=c.hasClass(d,"selected");l(".item",this.content).removeClass("selected");e&&c.addClass(d,"selected");"true"===c.getAttr(a,"data-isLastItem")&&(this.lastFocusItem=e?b.nextElementSibling:b)}},_onContentKeydown:function(a){if(a.keyCode===g.ENTER||a.keyCode===g.SPACE)this._onContentClicked(a);else if(a.keyCode===
g.TAB&&!a.shiftKey&&"true"===c.getAttr(a.target,"data-isLastItem")){var b=c.hasClass(a.target.parentNode,"selected");if(!b||b&&c.hasClass(a.target,"item-content"))a.preventDefault(),this.emit("focus-result-header")}},_onBtnBackClicked:function(){this.emit("back")},_onBtnMenuClicked:function(a){if(this.featureSet){var b=c.position(a.target||a.srcElement);this.featureActionManager.getSupportedActions(this.featureSet).then(f.hitch(this,function(a){h.forEach(a,f.hitch(this,function(a){a.data=this.featureSet}));
if(!this.config.enableExport){var c=["ExportToCSV","ExportToFeatureCollection","ExportToGeoJSON","SaveToMyContent"];a=h.filter(a,f.hitch(this,function(a){return 0>c.indexOf(a.name)}))}a=h.filter(a,f.hitch(this,function(a){return"CreateLayer"!==a.name}));var d=this._getSymbolAction();d&&a.push(d);this.popupMenu.setActions(a);this.popupMenu._setFocusedNodeBeforeOpen();this.popupMenu.show(b)}))}},_onBtnMenuKeydown:function(a){a.keyCode!==g.ENTER&&a.keyCode!==g.SPACE||this._onBtnMenuClicked(a)},_getSymbolAction:function(){var a=
null;"Table"!==this.layerDefinition.type&&this.layer&&this.layer.renderer&&this.config.canModifySymbol&&((a=this.featureSet&&this.featureSet.features)||(a=[]),a=new z({name:"ChangeSymbol",label:this.nls.changeSymbol,data:a,iconClass:"icon-edit-symbol",iconFormat:"svg",map:this.map,onExecute:f.hitch(this,this._showSymbolChooser)}));return a},_showSymbolChooser:function(){if(this.layer){var a=this.layer.renderer,b={};(a=a.defaultSymbol||a.symbol)?b.symbol=a:(a=k.getSymbolTypeByGeometryType(this.layer.geometryType),
b.type=a);var c=new C(b),e=new A({width:380,autoHeight:!0,titleLabel:this.nls.changeSymbol,content:c,onClose:f.hitch(this,function(){c.destroy();e=c=null}),buttons:[{label:window.jimuNls.common.ok,onClick:f.hitch(this,function(){var a=c.getSymbol(),a=new q(a);this.layer.setRenderer(a);this.layer.redraw();e.close()})},{label:window.jimuNls.common.cancel,onClick:f.hitch(this,function(){e.close()})}]})}}})});