// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/Deferred dojo/when dojo/promise/all jimu/portalUtils esri/lang esri/request jimu/utils esri/dijit/PopupTemplate esri/graphic esri/geometry/Extent".split(" "),function(e,h,k,q,l,r,m,n,t,u,v,w){var p={map:null,layerInfosObj:null,appConfig:null,_esriLocatorRegExp:/geocode(.){0,3}\.arcgis.com\/arcgis\/rest\/services\/World\/GeocodeServer/g,setMap:function(a){this.map=a},setLayerInfosObj:function(a){this.layerInfosObj=a},setAppConfig:function(a){this.appConfig=
a},getConfigInfo:function(a){if(a&&a.sources&&0<a.sources.length){var b=null;return this.searchLayer(this.map)&&a.upgradeFromGeocoder?(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,b=h.map(b.layers,e.hitch(this,function(a,b){b.hintText=a;return this._getQueryTypeGeocoder(b)},b.hintText)),l(b).then(e.hitch(this,function(b){a.sources=[].concat(b).concat(a.sources);return a}))):a}return q(this._getSoucesFromPortalAndWebmap()).then(e.hitch(this,function(a){return{allPlaceholder:"",
showInfoWindowOnSelect:!0,sources:a}}))},_getSoucesFromPortalAndWebmap:function(){var a=[],b=null;this.searchLayer(this.map)&&(b=this.map.itemInfo.itemData.applicationProperties.viewing.search,h.forEach(b.layers,e.hitch(this,function(b,f){f.hintText=b;a.push(this._getQueryTypeGeocoder(f))},b.hintText)));return r.getPortalSelfInfo(this.appConfig.portalUrl).then(e.hitch(this,function(b){if((b=b.helperServices&&b.helperServices.geocode)&&0<b.length)for(var d=0,c=b.length;d<c;d++){var g=b[d];g&&a.push(this._processSingleLine(g))}return l(a).then(e.hitch(this,
function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d];c&&(c&&"query"===c.type||(c={name:c.name||this._getGeocodeName(c.url),url:c.url,singleLineFieldName:c.singleLineFieldName,placeholder:"Find address or place",maxResults:6,searchInCurrentMapExtent:!1,type:"locator"},c.enableLocalSearch=this._isEsriLocator(c.url),c.localSearchMinScale=3E5,c.localSearchDistance=5E4),b.push(c))}return b}))}))},_getQueryTypeGeocoder:function(a){var b=this.map.getLayer(a.id),d=null,f=null,c=null,c=m.isDefined(a.subLayer)?
a.id+"_"+a.subLayer:a.id,d=this.layerInfosObj.traversal(function(a){return a.id===c?(f=a,!0):!1});return b&&d&&f?(d=m.isDefined(a.subLayer)?f.url||b.url+"/"+a.subLayer:f.url||b.url,{name:f.title,layerId:c,url:d,placeholder:a.hintText,searchFields:[a.field.name],displayField:a.field.name,exactMatch:a.field.exactMatch||!1,maxResults:6,searchInCurrentMapExtent:!1,type:"query"}):null},_isEsriLocator:function(a){this._esriLocatorRegExp.lastIndex=0;return this._esriLocatorRegExp.test(a)},_processSingleLine:function(a){if(a.singleLineFieldName)return a;
if(this._isEsriLocator(a.url))return a.singleLineFieldName="SingleLine",a;var b=new k;n({url:a.url,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(e.hitch(this,function(d){d.singleLineAddressField&&d.singleLineAddressField.name?(a.singleLineFieldName=d.singleLineAddressField.name,b.resolve(a)):(console.warn(a.url+"has no singleLineFieldName"),b.resolve(null))}),e.hitch(this,function(a){console.error(a);b.resolve(null)}));return b.promise},_getGeocodeName:function(a){if("string"!==
typeof a)return"geocoder";a=a.split("/");return a[a.length-2]||"geocoder"},getGeocoderName:function(a){return this._getGeocodeName(a)},hasAppSearchInfo:function(a){return a.itemInfo&&a.itemInfo.itemData&&a.itemInfo.itemData.applicationProperties&&a.itemInfo.itemData.applicationProperties.viewing&&a.itemInfo.itemData.applicationProperties.viewing.search},searchLayer:function(a){if(!this.hasAppSearchInfo(a))return!1;a=a.itemInfo.itemData.applicationProperties.viewing.search;return a.enabled&&0!==a.layers.length?
!0:!1},getSingleLineAddressName:function(a){var b=new k;n({url:a,content:{f:"json"},handleAs:"json",callbackParamName:"callback"}).then(e.hitch(this,function(a){a&&a.singleLineAddressField&&a.singleLineAddressField.name?b.resolve(a.singleLineAddressField.name):b.resolve(null)}),e.hitch(this,function(a){console.error(a);b.reject()}));return b},version:{isConfigBefore63:function(a){var b=!1;a&&a.geocoderOptions&&(b=!0);return b},upgradeConfig:function(a){a.geocoderOptions&&delete a.geocoderOptions},
getVersionState:function(){}},config:{onLayerInfosFilterChanged:function(a,b){h.some(a,e.hitch(this,function(a){b.searchOptions&&b.searchOptions.sources&&0<b.searchOptions.sources.length&&h.forEach(b.searchOptions.sources,function(b){b._featureLayerId===a.id&&b.featureLayer.setDefinitionExpression(a.getFilter())})}))},getInfoTemplate:function(a,b,d){var f=new k;d=d.getLayerInfoById(b.layerId);var c;if(d)f=d.loadInfoTemplate();else{var e=[];h.filter(a.fields,function(a){"shape"!==a.name.toLowerCase()&&
e.push(a.name)});(a=t.getDefaultPopupInfo(a,b.name+": {"+b.displayField+"}",e))&&(c=new u(a));f.resolve(c)}return f},getWayPoints:function(a,b){if(b)return a.defaultLocations;b=[];for(var d=0,e=a.defaultLocations.length;d<e;d++){var c;c=a.defaultLocations[d];if("object"===typeof c&&c.feature&&c.name){p.config._toPointGeometry(c);var g={},g=c.feature.attributes;c.name&&(g.Name=c.name);c=new v(c.feature,null,g);b.push(c)}else"string"===typeof c?b.push(c):b.push("")}return b},_toPointGeometry:function(a){var b=
a.feature.geometry;if(b)if(b.getCentroid)a.feature.geometry=b.getCentroid();else if(b.getExtent){if(b=b.getExtent())a.feature.geometry=b.getCenter()}else b.x||b.y||(b=b.cache._extent,"undefined"!==typeof b.xmin&&"undefined"!==typeof b.ymin&&"undefined"!==typeof b.xmax&&"undefined"!==typeof b.ymax&&"undefined"!==typeof b.spatialReference&&(b=new w(b.xmin,b.ymin,b.xmax,b.ymax,b.spatialReference),a.feature.geometry=b.getCenter()));return a}}};return p});