// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("require exports ../../baUtil/array dojo/store/util/SimpleQueryEngine ./ObjectUtil esri/dijit/geoenrichment/utils/ArrayUtil".split(" "),function(v,w,n,t,m,p){function r(a,b){a.some(function(c,d){b.func(c,d,b,a);if(b.stop)return!0});return b}function u(a){var b=a.split(" "),c=b[1];a={};switch(b[0]){case "max":a.result=-Infinity;b=function(a,b,f){f.result=Math.max(f.result,m.getObject(a,c))};break;case "min":a.result=Infinity;b=function(a,b,f){f.result=Math.min(f.result,m.getObject(a,c))};break;
case "sum":a.result=0;b=function(a,b,f){f.result+=m.getObject(a,c)};break;case "random":a.result=void 0;b=function(a,b,c,g){c.result=g[Math.round((g.length-1)*Math.random())];c.stop=!0};break;default:throw Error("Unsupported query.");}a.func=b;return a}var q={getSorting:function(a,b){if(!a)return m.compare;if("function"===typeof a)return a;var c;c=Array.isArray(a)?a:a.sort||[a];var d={};"string"===typeof b&&(b=[b]);Array.isArray(b)?b.forEach(function(a){d[a]=m.compareNames}):b&&(d=b);return function(a,
b){for(var e=void 0,f=0;e=c[f];f++){var h=a[e.attribute],l=b[e.attribute];if(h=(d[e.attribute]||(d["*"]?d["*"].bind(null,e.attribute):m.compare))(h,l,!1,!1,a,b))return e.descending?-h:h}return 0}},sort:function(a,b,c){return a.sort(q.getSorting(b,c))},sortIndices:function(a,b,c){a=n.map(a,function(a,b){return{value:a,index:b}});var d=q.getSorting(b,c);a.sort(function(a,b){return d(a.value,b.value)});return n.map(a,function(a){return a.index})},getQueryEngine:function(a,b){return function(c,d){d&&
d.sort&&(d=Object.assign({},d),d.sort=q.getSorting(d.sort,a));return(b||t)(c,d)}},objectToArray:function(a,b){void 0===b&&(b=null);var c=[],d=b?function(c){return a[c]?a[c][b]:void 0}:function(b){return a[b]},e;for(e in a){var f=d(e);"undefined"!==typeof f&&c.push(f)}return c},arrayToObject:function(a,b){var c={},d=p.composeIdentityFunction(b);n.forEach(a,function(a){c[d(a)]=a});return c},composeIdentityFunction:p.composeIdentityFunction,removeDuplicates:p.removeDuplicates,splitArrayToBunches:p.splitArrayToBunches,
contains:function(a,b){return-1!==n.indexOfLoose(a,b)},remove:function(a,b){b=n.indexOfLoose(a,b);-1!==b&&a.splice(b,1);return-1!==b},merge:function(a,b){a=a||[];null!=b&&Array.prototype.push.apply(a,b);return a},listToArray:function(a,b){if(null==a)return[];void 0===b&&(b=",");a="string"===typeof a?a.split(b):a.slice();for(b=0;b<a.length;b++)"string"===typeof a[b]&&(a[b]=a[b].trim());return a},reorderArray:function(a,b){var c=a.length,d=0,e=Array(c),f={},g={},k;for(k in b){var h=Math.round(k);if(0<=
h&&h<c&&!f[h]){var l=Math.round(b[k]);0<=l&&l<c&&!g[l]&&(e[l]=a[h],f[h]=1,g[l]=1,d++)}}d!==c&&(e=e.filter(function(a,b){return g[b]}),a.forEach(function(a,b){!f[b]&&e.push(a)}));return e},mapIndices:function(a,b,c,d){d=null==d?null:d;if(1===a)c.call(d,0,Math.floor(b/2));else{b=(b-1)/(a-1);for(var e=0;e<a;e++)c.call(d,e,Math.floor(.5+e*b))}},moveElement:function(a,b,c,d){var e=Array.isArray(b)?b:[b];if(-1!==e.indexOf(c))return a.slice();var f=[];a.forEach(function(a){-1===e.indexOf(a)&&(a==c?"before"===
d?(e.forEach(function(a){f.push(a)}),f.push(c)):"after"===d&&(f.push(c),e.forEach(function(a){f.push(a)})):f.push(a))});return f},min:function(a,b){var c=a.length;switch(c){case 0:return null;case 1:return a[0];default:for(var d=a[0],e=b(d),f=0,g=1;g<c;g++){var k=b(a[g]);e>k&&(d=a[g],e=k,f=g)}return{key:f,value:d,comparisonValue:e}}},max:function(a,b){var c=a.length;switch(c){case 0:return null;case 1:return a[0];default:for(var d=a[0],e=b(d),f=0,g=1;g<c;g++){var k=b(a[g]);e<k&&(d=a[g],e=k,f=g)}return{key:f,
value:d,comparisonValue:e}}},query:function(a,b){if("object"===typeof b)return r(a,b);if("string"===typeof b)return b=u(b),r(a,b).result},everyEqualProperty:function(a,b){if(2>a.length)return!0;var c;return!a.some(function(a,e){if(0===e)c=a[b];else if(c!==a[b])return!0})}};return q});