// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Evented jimu/BaseWidget dojo/_base/html dojo/_base/array dojo/on dijit/TooltipDialog jimu/dijit/formSelect dojo/dom-construct dijit/popup jimu/dijit/Message jimu/CSVUtils ./extractDataTask ./createReplica dojo/dom-class jimu/utils dijit/focus dojo/keys dojo/_base/event".split(" "),function(r,e,t,u,v,h,g,w,x,l,q,y,z,A,B,C,D,p,m,n){return r([u,t],{baseClass:"jimu-widget-screening",_popup:null,downloadOptions:[],isTooltipDialogOpened:!1,downLoadStatus:{},
constructor:function(a){this._popup=null;this.downloadOptions=[];this.isTooltipDialogOpened=!1;this.downLoadStatus={};e.mixin(this,a)},startup:function(){this._popup=new w({"class":"esriCTDownloadSettingsDialog "+this.baseClass,style:{width:"300px"}});"DartTheme"===this.appConfig.theme.name&&C.add(this._popup.domNode,"dart-panel");this._popup.startup();this.own(g(document.body,"click",e.hitch(this,function(a){this.isPartOfPopup(a.target||a.srcElement)||this.closePopup()})));this.own(g(window,"resize",
e.hitch(this,function(){this.closePopup()})));this._createSettingsDialog()},checkFileForDownload:function(){var a,b,d,c;a=b=d=!1;"extractDataTask"===this.config.downloadSettings.type&&(a=b=d=!0);c=this._getFilteredDownloadLayers();h.forEach(c,e.hitch(this,function(c){c.allowDownload&&this.downloadFeatureDetailsObj[c.id]&&0<this.downloadFeatureDetailsObj[c.id].length&&(0<=c.downloadingFileOption.indexOf("csv")&&(a=!0),0<=c.downloadingFileOption.indexOf("shapefile")&&(b=!0),0<=c.downloadingFileOption.indexOf("filegdb")&&
(d=!0))}));this.downLoadStatus={isCSVAvailable:a,isShapeFileAvailable:b,isFileGDBAvailable:d}},_createSettingsDialog:function(){var a,b;a=l.create("div",{"class":"esriCTDownloadSettingsContainer"},null);l.create("div",{"class":"esriCTEllipsis esriCTDownloadSettingLabel",innerHTML:this.nls.reportsTab.downloadLabelText},a);this.downloadFormatSelect=new x({"aria-label":this.nls.reportsTab.downloadLabelText});this.own(g(this.downloadFormatSelect,"keydown",e.hitch(this,function(a){a.keyCode===m.ESCAPE&&
(n.stop(a),this.closePopup(),this.emit("setFocusOnDownloadReportButton"))})));this._getOptionsFordownloadFormat();this.downloadFormatSelect.placeAt(a);b=l.create("button",{innerHTML:this.nls.reportsTab.downloadBtnText,"class":"esriCTEllipsis jimu-btn esriCTDownloadSettingsBtn",tabindex:0,"aria-label":this.nls.reportsTab.downloadBtnText,role:"button"},l.create("div",{"class":"esriCTDownloadSettingsBtnContainer"},a));this.own(g(b,"click",e.hitch(this,function(a){n.stop(a);this.closePopup();this.emit("setFocusOnDownloadReportButton");
this.isAndroidDevice?this._startDownload():this._chooseFileTypeToDownload()})));this.own(g(b,"keydown",e.hitch(this,function(a){if(a.keyCode===m.ENTER||a.keyCode===m.SPACE)n.stop(a),this.closePopup(),this.emit("setFocusOnDownloadReportButton"),this.isAndroidDevice?this._startDownload():this._chooseFileTypeToDownload();a.keyCode===m.ESCAPE&&(n.stop(a),this.closePopup(),this.emit("setFocusOnDownloadReportButton"))})));this._popup.setContent(a)},_loadOptionsForDropDown:function(a,b){var d=[],c;h.forEach(b,
e.hitch(this,function(a){c={value:a,label:this.nls.reportsTab[a]};d.push(c)}));a.addOption(d)},_getOptionsFordownloadFormat:function(){var a;if("extractDataTask"===this.config.downloadSettings.type)a=["csv","filegdb","shapefile"];else{var b;b=[];a=["csv"];b=this._getFilteredDownloadLayers();h.forEach(b,e.hitch(this,function(b){var c;c=["csv"];if(b.allowDownload){var d,f;d=this.filterLayerObj[b.id].capabilities;f=this.filterLayerObj[b.id].version;1<d.split("Sync").length&&10.4<=f&&(-1===c.indexOf("filegdb")&&
c.push("filegdb"),-1===a.indexOf("filegdb")&&a.push("filegdb"),D.isHostedService(b.url)&&(-1===c.indexOf("shapefile")&&c.push("shapefile"),-1===a.indexOf("shapefile")&&a.push("shapefile")));b.downloadingFileOption=c}}))}this._loadOptionsForDropDown(this.downloadFormatSelect,a)},openPopup:function(){q.open({popup:this._popup,x:this.position.pageX,y:this.position.pageY});this.isTooltipDialogOpened=!0},closePopup:function(){this._popup&&(q.close(this._popup),this.isTooltipDialogOpened=!1)},isPartOfPopup:function(a){var b;
b=this._popup.domNode;return a===b||v.isDescendant(a,b)},_chooseFileTypeToDownload:function(){switch(this.downloadFormatSelect.get("value")){case "csv":this.downLoadStatus.isCSVAvailable?this._exportToCSV():this.emit("showMessage",this.nls.reportsTab.noFeaturesFound);break;case "filegdb":this.downLoadStatus.isFileGDBAvailable?"syncEnable"===this.config.downloadSettings.type?this._exportFileUsingCreateReplica("filegdb"):"extractDataTask"===this.config.downloadSettings.type&&this.isPointOrLineAOI?this.emit("showMessage",
this.nls.reportsTab.unableToDownloadFileGDBText):this._exportFileUsingExtractDataTask("filegdb"):this.emit("showMessage",this.nls.reportsTab.noFeaturesFound);break;case "shapefile":this.downLoadStatus.isShapeFileAvailable?"syncEnable"===this.config.downloadSettings.type?this._exportFileUsingCreateReplica("shapefile"):"extractDataTask"===this.config.downloadSettings.type&&this.isPointOrLineAOI?this.emit("showMessage",this.nls.reportsTab.unableToDownloadShapefileText):this._exportFileUsingExtractDataTask("shapefile"):
this.emit("showMessage",this.nls.reportsTab.noFeaturesFound)}},_startDownload:function(){var a=new y({titleLabel:this.nls.reportsTab.downloadReportConfirmTitle,message:this.nls.reportsTab.downloadReportConfirmMessage,autoHeight:!0,buttons:[{label:this.nls.common.yes,onClick:e.hitch(this,function(){this._chooseFileTypeToDownload();a.close()})},{label:this.nls.common.no}]})},_exportToCSV:function(){var a,b,d={},c,k,f=[],f=this.config.downloadSettings.layers;this.shapeFileLayerDetails&&(f=f.concat(this.shapeFileLayerDetails));
f=this._getFilteredDownloadLayers();h.forEach(f,e.hitch(this,function(f){d={};k=!1;k="extractDataTask"===this.config.downloadSettings.type?!0:f.allowDownload;a=f.isShapeFile?f.layer:this.filterLayerObj[f.id];b=this._getLayerData(a,this.downloadFeatureDetailsObj[f.id]);b=dojo.mixin({},b);b=this._removeAnalysisUnitFromCSV(b);this._addAnalysisDataToCSVData(b,f.id);c=this._getInfoTemplate(a);0<b.graphicsArray.length&&k&&(d.datas=b.graphicsArray,d.fromClient=!1,d.withGeometry="esriGeometryPoint"===a.geometryType,
d.outFields=b.outFields,d.formatNumber=!1,d.formatDate=!0,d.formatCodedValue=!0,d.popupInfo=c,z.exportCSVFromFeatureLayer(a.name||"CSV_FILE",a,d))}))},_removeAnalysisUnitFromCSV:function(a){var b;b=a.outFields;h.forEach(b,function(a,c){"CSVMeasurementUnit"===a.name&&b.splice(c,1)});return a},_getInfoTemplate:function(a){var b,d,c;if(a.infoTemplate)return a.infoTemplate.info;b=a.id.split("_");b[b.length-1]===a.layerId.toString()&&(b.pop(),d=b.join("_"));d&&(c=this.map.getLayer(d));return c&&c.infoTemplates&&
c.infoTemplates.hasOwnProperty(a.layerId)?c.infoTemplates[a.layerId].infoTemplate.info:null},_getLayerData:function(a,b){var d=[];h.forEach(b,e.hitch(this,function(a){a.attributes.geometry=a.geometry;d.push(a.attributes)}));return"esriGeometryPoint"===a.geometryType?(a=this._formatPointLayerData(d,a),{graphicsArray:a.layerGraphics,outFields:a._outFields}):{graphicsArray:d,outFields:a.fields}},_formatPointLayerData:function(a,b){var d={};a=e.clone(a);b=b.fields;h.forEach(a,function(a){var b=a.geometry;
b&&"point"===b.type&&("x"in a?a._x=b.x:a.x=b.x,"y"in a?a._y=b.y:a.y=b.y);delete a.geometry});b=e.clone(b);var c="",c=-1!==b.indexOf("x")?"_x":"x";b.push({name:c,alias:c,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});c=-1!==b.indexOf("y")?"_y":"y";b.push({name:c,alias:c,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});d.layerGraphics=a;d._outFields=b;return d},_exportFileUsingExtractDataTask:function(a){this.loadingIndicator.show();a=new A({map:this.map,
aoi:this.aoi,fileFormat:a,url:this.config.downloadSettings.extractDataTaskURL});a.startup();this.own(g(a,"onGPTaskSuccess",e.hitch(this,function(a){this._downloadDataFile(a);this.loadingIndicator.hide()})));this.own(g(a,"onGPTaskFailed",e.hitch(this,function(){this.emit("showMessage",this.nls.reportsTab.extractDataTaskFailedMessage);this.loadingIndicator.hide()})))},_exportFileUsingCreateReplica:function(a){this.loadingIndicator.show();a=new B({map:this.map,config:this.config,aoi:this.aoi,fileFormat:a,
filterLayerObj:this.filterLayerObj,nls:this.nls,downloadFeatureDetailsObj:this.downloadFeatureDetailsObj,loadingIndicator:this.loadingIndicator});this.own(g(a,"onRequestSucceeded",e.hitch(this,function(a){this._downloadDataFile(a);this.loadingIndicator.hide()})));this.own(g(a,"onRequestFailed",e.hitch(this,function(){this.loadingIndicator.hide()})));this.own(g(a,"createReplicaComplete",e.hitch(this,function(a){a&&this.emit("showMessage",a);this.loadingIndicator.hide()})));this.own(g(a,"showErrMessage",
e.hitch(this,function(a){this.emit("showMessage",a)})));a.startup()},_downloadDataFile:function(a){var b,d,c,k,f,g,h;for(f in this.filterLayerObj)if(this.filterLayerObj.hasOwnProperty(f)&&(c=this.filterLayerObj[f],c.credential&&c.credential.token&&(k=a.split("replicafiles"),g=c.url,h=k[0].toLowerCase(),h=h.replace(/(^\w+:|^)\/\//,""),0<k.length&&-1<g.toLowerCase().indexOf(h.toLowerCase())))){a=a+"?token\x3d"+c.credential.token;break}b=l.create("iframe",{"class":"esriCTHidden",src:a},this.iframeNode);
d=setInterval(e.hitch(this,function(){var a=b.contentDocument||b.contentWindow.document;if("complete"===a.readyState||"interactive"===a.readyState)l.destroy(b),clearInterval(d)}),4E3)},_addAnalysisDataToCSVData:function(a,b){var d,c,e,f;c=a.graphicsArray.length;if(0<c){for(d=0;d<c;d++)if(f=a.graphicsArray[d],e=this._getFeatureAnalysisData(b,d))f.CSVMeasurementUnit=e.analysisResultValue;e&&this._addGeometryUnitToFields(a,e)}},_addGeometryUnitToFields:function(a,b){a.outFields.push({alias:b.analysisResultKey+
"("+b.analysisUnit+")",name:"CSVMeasurementUnit",type:"esriFieldTypeDouble"})},_getFeatureAnalysisData:function(a,b){var d,c,e,f={};e="";for(d in this.printData)if(c=this.printData[d],-1!==d.indexOf(a)&&"esriGeometryPoint"!==c.geometryType){if("esriGeometryPolyline"===c.geometryType)return e=this._getAnalysisUnitForGeometry(this.lengthUnits,c.geometryType),a=this.lengthUnits+"UnitInfo",a=this._lowerCaseFirstLetter(a),f.analysisResultValue=c[a][b],f.analysisResultKey=this._getAnalysisResultKey(c.geometryType),
f.analysisUnit=e,f;if("esriGeometryPolygon"===c.geometryType)return e=this._getAnalysisUnitForGeometry(this.areaUnits,c.geometryType),a=this.areaUnits+"UnitInfo",a=this._lowerCaseFirstLetter(a),f.analysisResultValue=c[a][b],f.analysisResultKey=this._getAnalysisResultKey(c.geometryType),f.analysisUnit=e,f}},_getAnalysisResultKey:function(a){if("esriGeometryPolygon"===a)return this.nls.reportsTab.featureCSVAreaText;if("esriGeometryPolyline"===a)return this.nls.reportsTab.featureCSVLengthText},_getAnalysisUnitForGeometry:function(a,
b){var d;switch(a){case "Feet":case "SquareFeet":d="esriGeometryPolygon"===b?this.nls.units.squareFeetAbbr:this.nls.units.feetAbbr;break;case "Miles":case "Acres":d="esriGeometryPolygon"===b?this.nls.units.acresAbbr:this.nls.units.milesAbbr;break;case "Meters":case "SquareMeters":d="esriGeometryPolygon"===b?this.nls.units.squareMetersAbbr:this.nls.units.metersAbbr;break;case "Kilometers":case "SquareKilometers":d="esriGeometryPolygon"===b?this.nls.units.squareKilometerAbbr:this.nls.units.kilometersAbbr;
break;case "Hectares":d="esriGeometryPolygon"===b?this.nls.reportsTab.hectaresAbbr:this.nls.units.kilometersAbbr}return d},_getFilteredDownloadLayers:function(){var a=[],a=[],a=this.config.downloadSettings.layers;return a=a.filter(e.hitch(this,function(a){return this.filterLayerObj.hasOwnProperty(a.id)?!0:!1}))},setFocusOnFormatDropdown:function(){this._focusOutCurrentNode();p.focus(this.downloadFormatSelect)},_lowerCaseFirstLetter:function(a){return a.charAt(0).toLowerCase()+a.slice(1)},_focusOutCurrentNode:function(){p.curNode&&
p.curNode.blur()}})});