// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Directions/setting/SearchConfig/SearchConfig.html":'\x3cdiv\x3e\r\n  \x3cdiv class\x3d"search-config"\x3e\r\n    \x3cdiv class\x3d"dropdown-button" role\x3d"button"\x3e\r\n      \x3cdiv class\x3d"button"\x3e\r\n        \x3cspan class\x3d"button-text"\x3e${nls.add}\x3c/span\x3e\r\n      \x3c/div\x3e\r\n      \x3cul class\x3d"dropdown-menu" role\x3d"menu" data-dojo-attach-event\x3d"click:_onMenuItemClick"\x3e\r\n        \x3cli class\x3d"dropdown-item" type\x3d"query"\x3e${nls.searchableLayer}\x3c/li\x3e\r\n        \x3cli class\x3d"dropdown-item" type\x3d"locator"\x3e${nls.geocoder}\x3c/li\x3e\r\n      \x3c/ul\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"sources"\x3e\r\n      \x3cdiv class\x3d"source-list jimu-float-leading"\x3e\r\n        \x3cdiv class\x3d"source-list-table" data-dojo-attach-point\x3d"sourceList"\x3e\x3c/div\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv class\x3d"source-setting jimu-float-trailing" data-dojo-attach-point\x3d"sourceSettingNode"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/on dojo/_base/html dojo/query dojo/_base/array dojo/Evented dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!./SearchConfig.html ./QuerySourceSetting ./LocatorSourceSetting jimu/LayerInfos/LayerInfos jimu/dijit/LoadingShelter dojo/Deferred ../../searchUtil dojo/when jimu/dijit/Message jimu/dijit/SimpleTable jimu/dijit/RadioBtn".split(" "),function(p,d,e,k,g,h,q,r,t,u,v,l,m,w,x,y,f,z,A,B){return p([r,t,u,q],{templateString:v,
postMixInProperties:function(){this.inherited(arguments);d.mixin(this.nls,window.jimuNls.common)},postCreate:function(){this.inherited(arguments);this.sourceList=new B({autoHeight:!1,selectable:!0,fields:[{name:"name",title:this.nls.name,width:"auto",type:"text",editable:!1},{name:"type",hidden:!0,type:"text",editable:!1},{name:"actions",title:"",width:"70px",type:"actions",actions:["up","down","delete"]}]},this.sourceList);k.setStyle(this.sourceList.domNode,"height","100%");this.sourceList.startup();
this.own(e(this.sourceList,"row-select",d.hitch(this,this._onSourceItemSelected)));this.own(e(this.sourceList,"row-delete",d.hitch(this,this._onSourceItemRemoved)));this.own(e(this.sourceList,"row-edit",d.hitch(this,this._onSourceItemChanged)));this.shelter=new x({hidden:!0})},startup:function(){this.inherited(arguments);this.shelter.show();w.getInstance(this.map,this.map.itemInfo).then(d.hitch(this,function(a){this.layerInfosObj=a;f.setMap(this.map);f.setLayerInfosObj(this.layerInfosObj);f.setAppConfig(this.appConfig);
this._upgradeConfig().then(d.hitch(this,function(){z(f.getConfigInfo(this.config.searchOptions)).then(d.hitch(this,function(a){this.domNode&&(this.setConfig(a),this.shelter.hide())}))}))}))},setConfig:function(a){h.forEach(a.sources,d.hitch(this,function(a,b){var c=this.sourceList.addRow({name:a.name||"",type:a.type});c&&c.success?(this._setRelatedConfig(c.tr,a),0===b&&setTimeout(d.hitch(this,function(){this.sourceList.selectRow(c.tr)}),100)):console.error("add row failed ",c)}))},getConfig:function(a){this._currentSourceSetting&&
this._closeSourceSetting(!0===a?!0:!1);var c={},b=this.sourceList.getRows(),n=[];h.forEach(b,d.hitch(this,function(b){var c=this._getRelatedConfig(b);a&&(delete c._definition,this._removeRelatedConfig(b));n.push(c)}));c.sources=n;return c},destroy:function(){f.setMap(null);f.setLayerInfosObj(null);f.setAppConfig(null);this.inherited(arguments)},validate:function(){return!0},_onMenuItemClick:function(a){this._currentSourceSetting&&!this._currentSourceSetting.isValidConfig()?this._currentSourceSetting.showValidationTip():
(a=a&&a.target&&k.getAttr(a.target,"type"),"locator"===a?this._addNewLocator():"query"===a&&this._addNewQuerySource())},_addNewLocator:function(){this._createNewLocatorSourceSettingFromMenuItem({},{})},_addNewQuerySource:function(){this._createNewQuerySourceSettingFromMenuItem({},{})},_setRelatedConfig:function(a,c){g(a).data("config",d.clone(c))},_getRelatedConfig:function(a){return g(a).data("config")[0]},_removeRelatedConfig:function(a){return g(a).removeData("config")},_createNewLocatorSourceSettingFromMenuItem:function(a,
c){var b=new m({nls:this.nls,map:this.map});b.setDefinition(c);a={url:a.url||"",name:a.name||"",singleLineFieldName:a.singleLineFieldName||"",placeholder:a.placeholder||"",countryCode:a.countryCode||"",maxSuggestions:a.maxSuggestions,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"locator",maxLocations:a.maxLocations,autoComplete:a.autoComplete,searchDelay:a.searchDelay,minCharacters:a.minCharacters,_isUpgrade:a._isUpgrade};this._upgradeGeocoderConfig(a);b.setConfig(a);b._openLocatorChooser();
b.own(e(b,"select-locator-url-ok",d.hitch(this,function(a){(a=this.sourceList.addRow({name:a.name||"New Geocoder",type:"locator"},this.sourceList.getRows().length))&&a.success&&(this._currentSourceSetting&&this._closeSourceSetting(),b.setRelatedTr(a.tr),b.placeAt(this.sourceSettingNode),this.sourceList.selectRow(a.tr),this._currentSourceSetting=b,this._checkConfig())})));b.own(e(b,"reselect-locator-url-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,
{name:a.name,type:"locator"});this._checkConfig()})));b.own(e(b,"select-locator-url-cancel",d.hitch(this,function(){this._currentSourceSetting!==b&&(b.destroy(),b=null)})))},_createNewLocatorSourceSettingFromSourceList:function(a,c,b){this._currentSourceSetting&&this._closeSourceSetting();this._currentSourceSetting=new m({nls:this.nls,map:this.map});this._currentSourceSetting.setDefinition(c);c={url:a.url||"",name:a.name||"",singleLineFieldName:a.singleLineFieldName||"",placeholder:a.placeholder||
"",countryCode:a.countryCode||"",maxSuggestions:a.maxSuggestions,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,enableLocalSearch:!!a.enableLocalSearch,localSearchMinScale:a.localSearchMinScale,localSearchDistance:a.localSearchDistance,type:"locator",maxLocations:a.maxLocations,autoComplete:a.autoComplete,searchDelay:a.searchDelay,minCharacters:a.minCharacters,_isUpgrade:a._isUpgrade};this._upgradeGeocoderConfig(c);this._currentSourceSetting.setConfig(c);this._currentSourceSetting.setRelatedTr(b);
this._currentSourceSetting.placeAt(this.sourceSettingNode);this._currentSourceSetting._processlocalSearchTable(!!a.enableLocalSearch);this._currentSourceSetting.own(e(this._currentSourceSetting,"reselect-locator-url-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name,type:"locator"});this._checkConfig()})))},_closeSourceSetting:function(a){var c=this._currentSourceSetting.getRelatedTr(),b=this._currentSourceSetting.getConfig();b._definition=
this._currentSourceSetting.getDefinition();this._setRelatedConfig(c,b);this.sourceList.editRow(c,{name:b.name});"undefined"!==typeof a&&!0!==a||this._currentSourceSetting.destroy()},_createNewQuerySourceSettingFromMenuItem:function(a,c){var b=new l({nls:this.nls,map:this.map,appConfig:this.appConfig});b.setDefinition(c);a={url:a.url,name:a.name||"",layerId:a.layerId,placeholder:a.placeholder||"",searchFields:a.searchFields||[],displayField:a.displayField||c.displayField||"",exactMatch:!!a.exactMatch,
maxSuggestions:a.maxSuggestions,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"query",maxLocations:a.maxLocations,autoComplete:a.autoComplete,searchDelay:a.searchDelay,minCharacters:a.minCharacters,_isUpgrade:a._isUpgrade};this._upgradeGeocoderConfig(a);b.setConfig(a);b._openQuerySourceChooser();b.own(e(b,"select-query-source-ok",d.hitch(this,function(a){(a=this.sourceList.addRow({name:a.name,type:"query"},0))&&a.success&&(this._currentSourceSetting&&this._closeSourceSetting(),b.setRelatedTr(a.tr),
b.placeAt(this.sourceSettingNode),this.sourceList.selectRow(a.tr),this._currentSourceSetting=b)})));b.own(e(b,"reselect-query-source-ok",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})));b.own(e(b,"select-query-source-cancel",d.hitch(this,function(){this._currentSourceSetting!==b&&(b.destroy(),b=null)})))},_createNewQuerySourceSettingFromSourceList:function(a,c,b){this._currentSourceSetting&&this._closeSourceSetting();this._currentSourceSetting=
new l({nls:this.nls,map:this.map,appConfig:this.appConfig});this._currentSourceSetting.placeAt(this.sourceSettingNode);this._currentSourceSetting.setDefinition(c);a={url:a.url,name:a.name||"",layerId:a.layerId,placeholder:a.placeholder||"",searchFields:a.searchFields||[],displayField:a.displayField||c.displayField||"",exactMatch:!!a.exactMatch,maxSuggestions:a.maxSuggestions,searchInCurrentMapExtent:!!a.searchInCurrentMapExtent,type:"query",maxLocations:a.maxLocations,autoComplete:a.autoComplete,
searchDelay:a.searchDelay,minCharacters:a.minCharacters,_isUpgrade:a._isUpgrade};this._upgradeGeocoderConfig(a);this._currentSourceSetting.setConfig(a);this._currentSourceSetting.setRelatedTr(b);this._currentSourceSetting.own(e(this._currentSourceSetting,"reselect-query-source",d.hitch(this,function(a){var b=this._currentSourceSetting.getRelatedTr();this.sourceList.editRow(b,{name:a.name})})))},_onSourceItemRemoved:function(a){this._checkConfig();this._currentSourceSetting&&this._currentSourceSetting.getRelatedTr()===
a&&(this._currentSourceSetting.destroy(),this._currentSourceSetting=null)},_onSourceItemChanged:function(){this._checkConfig()},_checkConfig:function(){!1===this._hasGeoLocator()?this.emit("isConfigValid","false"):this.emit("isConfigValid","true")},_hasGeoLocator:function(){var a=!1,c=this.sourceList.getData();h.some(c,d.hitch(this,function(b){if(b&&"locator"===b.type)return a=!0}));return a},_onSourceItemSelected:function(a){var c=this._getRelatedConfig(a),b=this._currentSourceSetting&&this._currentSourceSetting.tr;
c&&a!==b&&(this._currentSourceSetting&&!this._currentSourceSetting.isValidConfig()?(this._currentSourceSetting.showValidationTip(),this.sourceList.selectRow(b)):"query"===c.type?this._createNewQuerySourceSettingFromSourceList(c,c._definition||{},a):"locator"===c.type&&this._createNewLocatorSourceSettingFromSourceList(c,c._definition||{},a))},_upgradeConfig:function(){var a=new y,c=[],b="";if(f.version.isConfigBefore63(this.config)&&(c=this.config.geocoderOptions&&this.config.geocoderOptions.geocoders)&&
0<c.length){var e=c[0];e&&e.url&&(b=e.url)}b?f.getSingleLineAddressName(b).then(d.hitch(this,function(c){if(c){var d=[];d.push({type:"locator",url:b,name:f.getGeocoderName(b),placeholder:e.placeholder||"",singleLineFieldName:c});this.config.searchOptions={};this.config.searchOptions.sources=d;a.resolve()}else null===c&&(a.resolve(null),new A({message:this.nls.locatorWarning}))}),d.hitch(this,function(){a.resolve(null)})):a.resolve(null);return a},_upgradeGeocoderConfig:function(a){this.config.geocoderOptions&&
(a._oldConfig={},this.config.geocoderOptions.geocoders[0]&&(a._oldConfig.placeholder=this.config.geocoderOptions.geocoders[0].placeholder||""),a._oldConfig.autoComplete=this.config.geocoderOptions.autoComplete,a._oldConfig.maxLocations=this.config.geocoderOptions.maxLocations,a._oldConfig.minCharacters=this.config.geocoderOptions.minCharacters,a._oldConfig.searchDelay=this.config.geocoderOptions.searchDelay)}})});