// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"esri/dijit/LocateButton":function(){define("require dojo/Evented dojo/_base/declare dojo/_base/lang dojo/has ../kernel ../config dijit/_WidgetBase dijit/a11yclick dijit/_TemplatedMixin dojo/on dojo/Deferred dojo/text!./templates/LocateButton.html dojo/i18n!../nls/jsapi dojo/dom-class dojo/dom-style dojo/dom-attr ../geometry/webMercatorUtils ../geometry/Point ../SpatialReference ../graphic ../symbols/PictureMarkerSymbol ../tasks/ProjectParameters".split(" "),function(g,n,q,b,k,l,p,
r,h,f,c,d,x,m,t,w,v,y,z,A,B,C,D){g=q("esri.dijit.LocateButton",[r,f,n],{templateString:x,options:{theme:"LocateButton",map:null,visible:!0,highlightLocation:!0,symbol:new C(g.toUrl("./images/sdk_gps_location.png"),28,28),infoTemplate:null,scale:null,useTracking:!1,clearOnTrackingStop:!1,setScale:!0,centerAt:!0,timeout:15E3,graphicsLayer:null,geolocationOptions:{maximumAge:0,timeout:15E3,enableHighAccuracy:!0}},constructor:function(a,e){a=b.mixin({},this.options,a);this.domNode=e;this._i18n=m;e=navigator.geolocation;
var u=window.hasOwnProperty("isSecureContext"),u=u&&window.isSecureContext||!u&&"https:"===window.location.protocol;u&&e||(a.visible=!1);e||console.log("LocateButton::navigator.geolocation unsupported.");u||console.log("LocateButton::navigator.geolocation requires a secure origin.");this.set("map",a.map);this.set("theme",a.theme);this.set("visible",a.visible);this.set("scale",a.scale);this.set("highlightLocation",a.highlightLocation);this.set("symbol",a.symbol);this.set("infoTemplate",a.infoTemplate);
this.set("geolocationOptions",a.geolocationOptions);this.set("useTracking",a.useTracking);this.set("setScale",a.setScale);this.set("centerAt",a.centerAt);this.set("timeout",a.timeout);this.set("graphicsLayer",a.graphicsLayer);this.set("clearOnTrackingStop",a.clearOnTrackingStop);this.watch("theme",this._updateThemeWatch);this.watch("visible",this._visible);this.watch("tracking",this._locate);this.watch("useTracking",b.hitch(this,function(){this.get("tracking")&&!this.get("useTracking")&&this._stopTracking();
this._setTitle()}));this._css={container:"locateContainer",locate:"zoomLocateButton",loading:"loading",tracking:"tracking"}},postCreate:function(){this.inherited(arguments);this.own(c(this._locateNode,h,b.hitch(this,this.locate)))},startup:function(){this.inherited(arguments);this.get("map")||(this.set("visible",!1),console.log("LocateButton::map required"));if(this.get("map").loaded)this._init();else c.once(this.get("map"),"load",b.hitch(this,function(){this._init()}))},destroy:function(){this.clear();
this._graphicsEvent&&this._graphicsEvent.remove();this._removeWatchPosition();this.inherited(arguments)},clear:function(){var a=this.get("highlightGraphic"),e=this.get("graphicsLayer");a&&(e?e.remove(a):this.get("map").graphics.remove(a),this.set("highlightGraphic",null))},locate:function(){this.get("useTracking")&&this.set("tracking",!this.get("tracking"));return this._locate()},show:function(){this.set("visible",!0)},hide:function(){this.set("visible",!1)},_setTitle:function(){this.get("useTracking")?
this.get("tracking")?v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.stopTracking):v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.tracking):v.set(this._locateNode,"title",this._i18n.widgets.locateButton.locate.title)},_removeWatchPosition:function(){this.get("watchId")&&(navigator.geolocation.clearWatch(this.get("watchId")),this.set("watchId",null));this._removePrivateVars()},_stopTracking:function(){t.remove(this._locateNode,this._css.tracking);this._removeWatchPosition();
this.get("clearOnTrackingStop")&&this.clear();this._hideLoading()},_positionToObject:function(a){return a?{coords:b.mixin({},a.coords),timestamp:a.timestamp}:{}},_startTracking:function(){t.add(this._locateNode,this._css.tracking);this._removeWatchPosition();var a=navigator.geolocation.watchPosition(b.hitch(this,function(a){a=this._positionToObject(a);this._setPosition(a).then(b.hitch(this,function(a){this._locateEvent(a)}),b.hitch(this,function(a){a||(a=Error("LocateButton::Error setting the position."));
this._locateError(a)}))}),b.hitch(this,function(a){this.set("tracking",!1);a||(a=Error("LocateButton::Could not get tracking position."));this._locateError(a)}),this.get("geolocationOptions"));this.set("watchId",a)},_removePrivateVars:function(){this._scale=this._position=this._graphic=null},_getCurrentPosition:function(){var a=new d;this._removePrivateVars();var e=setTimeout(b.hitch(this,function(){clearTimeout(e);a.reject(Error("LocateButton::time expired for getting location."))}),this.get("timeout"));
navigator.geolocation.getCurrentPosition(b.hitch(this,function(d){d=this._positionToObject(d);clearTimeout(e);this._setPosition(d).then(b.hitch(this,function(e){a.resolve(e)}),b.hitch(this,function(e){e||(e=Error("LocateButton::Error setting map position."));a.reject(e)}))}),b.hitch(this,function(e){e||(e=Error("LocateButton::Could not get current position."));a.reject(e)}),this.get("geolocationOptions"));return a.promise},_locate:function(){var a=new d;this._showLoading();if(navigator.geolocation)this.get("useTracking")?
this.get("tracking")?(this._startTracking(),a.resolve({tracking:!0})):(this._stopTracking(),a.resolve({tracking:!1})):this._getCurrentPosition().then(b.hitch(this,function(e){this._locateEvent(e);a.resolve(e)}),b.hitch(this,function(e){e||(e=Error("LocateButton::Could not get current position."));this._locateError(e);a.reject(e)}));else{var e=Error("LocateButton::geolocation unsupported");this._locateError(e);a.reject(e)}this._setTitle();return a.promise},_projectPoint:function(a){var e=new d,m=this.get("map").spatialReference,
c=m.wkid;m.isWebMercator()?(a=y.geographicToWebMercator(a),e.resolve(a)):p.defaults.geometryService&&4326!==c?(c=new D,c.geometries=[a],c.outSR=m,p.defaults.geometryService.project(c).then(b.hitch(this,function(a){a&&a.length?e.resolve(a[0]):e.reject(Error("LocateButton::Point was not projected."))}),function(a){a||(a=Error("LocateButton::please specify a geometry service on esri/config to project."));e.reject(a)})):e.resolve(a);return e.promise},_getScale:function(a){var e=this.get("scale");return a&&
a.coords?e||a.coords.accuracy||5E4:e||5E4},_createPoint:function(a){var e;a&&a.coords&&(e=new z([a.coords.longitude,a.coords.latitude],new A({wkid:4326})));return e},_setPosition:function(a){var e=new d,c,m;this._removePrivateVars();if((this._position=a)&&a.coords){if(c=this._createPoint(a))this._graphic=m=this._createGraphic(c,a);var f=this._getScale(a);this._scale=f;c?this._projectPoint(c).then(b.hitch(this,function(c){this._graphic=m=this._createGraphic(c,a);var d={graphic:m,scale:f,position:a};
this.get("setScale")&&this.get("map").setScale(f);this.get("centerAt")?this.get("map").centerAt(c).then(b.hitch(this,function(){e.resolve(d)}),b.hitch(this,function(a){a||(a=Error("LocateButton::Could not center map."));e.reject(a)})):e.resolve(d)}),b.hitch(this,function(a){a||(a=Error("LocateButton::Error projecting point."));e.reject(a)})):(c=Error("LocateButton::Invalid point"),e.reject(c))}else c=Error("LocateButton::Invalid position"),e.reject(c);return e.promise},_createGraphic:function(a,e){var c;
a&&(e={position:e},c=new B(a,this.get("symbol"),e,this.get("infoTemplate")));return c},_locateEvent:function(a){if(a.graphic){var e=this.get("highlightGraphic"),c=this.get("graphicsLayer");e?(e.setGeometry(a.graphic.geometry),e.setAttributes(a.graphic.attributes),e.setInfoTemplate(a.graphic.infoTemplate),e.setSymbol(a.graphic.symbol)):(e=a.graphic,this.get("highlightLocation")&&(c?c.add(e):this.get("map").graphics.add(e)));this.set("highlightGraphic",e)}this._hideLoading();this.emit("locate",a)},
_locateError:function(a){a={graphic:this._graphic,scale:this._scale,position:this._position,error:a};this._hideLoading();this.emit("locate",a)},_showLoading:function(){this.get("useTracking")||t.add(this._locateNode,this._css.loading)},_hideLoading:function(){this.get("useTracking")||t.remove(this._locateNode,this._css.loading)},_init:function(){this._visible();this._setTitle();this.get("tracking")&&this.get("useTracking")&&this._locate();this.set("loaded",!0);this.emit("load",{})},_updateThemeWatch:function(a,
e,c){t.remove(this.domNode,e);t.add(this.domNode,c)},_visible:function(){this.get("visible")?w.set(this.domNode,"display","block"):w.set(this.domNode,"display","none")}});k("extend-esri")&&b.setObject("dijit.LocateButton",g,l);return g})},"widgets/MyLocation/Compass":function(){define("dojo/_base/declare dojo/_base/lang jimu/BaseWidget dojo/on esri/symbols/PictureMarkerSymbol esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/graphic esri/Color esri/geometry/Circle".split(" "),function(g,
n,q,b,k,l,p,r,h,f){var c=null,d;d=g([q],{constructor:function(c,d,b){this.id="widget-myLocation-compass-"+(new Date).getTime();this.map=d;this.folderUrl=c;this.config=b;this._debug=0;this.inherited(arguments)},show:function(c,d){if(this.map.spatialReference.isWebMercator()||4326===this.map.spatialReference)!0===this.config.useCompass&&this._showDirection(d),!0===this.config.useAccCircle&&this._showAccCircle(c,d)},_showDirection:function(c){if(c.useTracking){this._destroyDirectionHandler();var d;"ondeviceorientationabsolute"in
window?d="deviceorientationabsolute":"ondeviceorientation"in window&&(d="deviceorientation");this._directionHandler=b(window,d,n.hitch(this,this._watchMobileLocation,c))}},_watchMobileLocation:function(c,d){if(d){var b;d.absolute&&null!==d.alpha&&"undefined"!==typeof d.alpha?b=d.alpha:d.webkitCompassHeading?b=360-d.webkitCompassHeading:(console.log("Could not retrieve absolute orientation"),this._debug&&(b=0));this._debug&&(document.querySelector(".jimu-title").innerText=this._flag1+this._flag2+"_alpha\x3d"+
b);"undefined"!==typeof b&&c.highlightGraphic.setSymbol(new k({url:this.folderUrl+"/images/compass.png",width:36,height:36,angle:b}))}},_showAccCircle:function(c,d){this._destroyAccCircle();if((d=d.highlightGraphic)&&d._graphicsLayer){var b=d.geometry;c=c.position.coords.accuracy/this.map.getResolution();c=new f({center:b,radius:c});c=new r(c,new l(l.STYLE_SOLID,new p(p.STYLE_SOLID,new h([94,164,255,.2]),1),new h([16,119,255,.2])));d._graphicsLayer.add(c);this._accCircle=c;this._accCircleGraphicsLayer=
d._graphicsLayer}},clean:function(){this._destroyDirectionHandler();this._destroyAccCircle()},destroy:function(){this.clean();this.inherited(arguments)},_destroyDirectionHandler:function(){this._directionHandler&&(this._directionHandler.remove&&this._directionHandler.remove(),this._directionHandler=null)},_destroyAccCircle:function(){this._accCircleGraphicsLayer&&this._accCircleGraphicsLayer.remove&&this._accCircle&&(this._accCircleGraphicsLayer.remove(this._accCircle),this._accCircle=null)}});d.getInstance=
function(b,f,g){null===c&&(c=new d(b,f,g));return c};return d})},"esri/geometry/Circle":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../kernel ./Point ./Polygon ./geodesicUtils ./webMercatorUtils ../WKIDUnitConversion ../units".split(" "),function(g,n,q,b,k,l,p,r,h,f){g=g(l,{declaredClass:"esri.geometry.Circle",_unitToMeters:{esriCentimeters:.01,esriDecimeters:.1,esriFeet:.3048,esriInches:.0254,esriKilometers:1E3,esriMeters:1,esriMiles:1609.344,esriMillimeters:.001,esriNauticalMiles:1852,
esriYards:.9144,esriDecimalDegrees:111320},constructor:function(c,d){c.center?d=c:(d=d||{},d.center=c);this.center=n.isArray(d.center)?new k(d.center[0],d.center[1]):d.center;this.radius=d.radius||1E3;this.radiusUnit=d.radiusUnit||f.METERS;this.geodesic=!0===d.geodesic?!0:!1;this.numberOfPoints=d.numberOfPoints||60;this._init()},toJson:function(){return this.inherited(arguments)},_init:function(){this.rings=[];this._ring=0;var c=this.radius*this._unitToMeters[this.radiusUnit],d=this._srType(this.center.spatialReference);
if(this.geodesic){var b;switch(d){case "webMercator":b=r.webMercatorToGeographic(this.center);break;case "projected":console.error("Creating a geodesic circle requires the center to be specified in web mercator or geographic coordinate system");break;case "geographic":b=this.center}c=this._createGeodesicCircle(b,c,this.numberOfPoints,b.spatialReference);"webMercator"===d&&(c=r.geographicToWebMercator(c))}else{var f;"webMercator"===d||"projected"===d?f=c/this._convert2Meters(1,this.center.spatialReference):
"geographic"===d&&(f=c/this._unitToMeters.esriDecimalDegrees);c=this._createPlanarCircle(this.center,f,this.numberOfPoints)}this.spatialReference=c.spatialReference;this.addRing(c.rings[0]);this.verifySR()},_createGeodesicCircle:function(c,d,b,f){for(var g=0,m=Math.PI/180,k=[],h;g<2*Math.PI;)h=p._directGeodeticSolver(c.y*m,c.x*m,g,d,f),k.push([h.x,h.y]),g+=Math.PI/(b/2);k.push(k[0]);return new l(k)},_createPlanarCircle:function(c,d,b){for(var f=0,g=[],k,h;f<2*Math.PI;)k=c.x+Math.cos(f)*d,h=c.y+Math.sin(f)*
d,g.push([k,h]),f+=Math.PI/(b/2);g.push(g[0]);c=new l(c.spatialReference);c.addRing(g);return c},_srType:function(c){return c.isWebMercator()?"webMercator":null!=h[c.wkid]||c.wkt&&0===c.wkt.indexOf("PROJCS")?"projected":"geographic"},_convert2Meters:function(c,d){if(null!=h[d.wkid])d=h.values[h[d.wkid]];else{d=d.wkt;var b=d.lastIndexOf(",")+1,f=d.lastIndexOf("]]");d=parseFloat(d.substring(b,f))}return c*d}});q("extend-esri")&&n.setObject("geometry.Circle",g,b);return g})},"widgets/MyLocation/a11y/Widget":function(){define(["dojo/_base/lang",
"dojo/on","dojo/_base/html","dijit/a11yclick"],function(g,n,q,b){return{a11y_updateLabel:function(b){b&&q.setAttr(this.domNode,"aria-label",b)},a11y_initEvents:function(){this.own(n(this.domNode,b,g.hitch(this,this.onLocationClick)))}}})},"widgets/MyLocation/_build-generate_module":function(){define(["dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:esri/dijit/templates/LocateButton.html":'\x3cdiv class\x3d"${theme}" role\x3d"presentation"\x3e\r\n    \x3cdiv class\x3d"${_css.container}"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"_locateNode" role\x3d"button" class\x3d"${_css.locate}" tabindex\x3d"0"\x3e\x3cspan\x3e${_i18n.widgets.locateButton.locate.button}\x3c/span\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/MyLocation/css/style.css":'.jimu-widget-mylocation{border-radius: 5px; background-color: #555; border: 1px solid #999;}.jimu-widget-mylocation.onCenter {background-color: #000;}.jimu-widget-mylocation .place-holder {padding: 2px; width: 30px; height: 30px; background-color: #555; -webkit-user-select: none; -moz-user-select: none; -ms-user-select: none; user-select: none; cursor: pointer; -webkit-border-radius: 5px; -moz-border-radius: 5px; -o-border-radius: 5px; border-radius: 5px; background-image: url("images/locate.png"); background-position: center center; background-repeat: no-repeat;}.jimu-widget-mylocation .place-holder.locating{background-image: url("images/loading.gif");}.jimu-widget-mylocation .place-holder.tracking{background-image: url("images/stop.png") !important; background-color: #000;}.jimu-widget-mylocation .place-holder.nohttps{background-image: url("images/locate_disabled.png") !important;}.jimu-widget-mylocation .place-holder.nohttps:hover{background-color: #555;}.jimu-widget-mylocation .place-holder.nohttps,.jimu-widget-mylocation .place-holder{background-color: #555;}.jimu-widget-mylocation.onLocate .place-holder{background-color: rgba(0,0,0,0.4);}.jimu-widget-mylocation.onCenter .place-holder{background-color: #000;}.jimu-widget-mylocation .place-holder:hover{background-color: #333;}',
"*now":function(g){g(['dojo/i18n!*preload*widgets/MyLocation/nls/Widget*["ar","bs","ca","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","hu","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","uk","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare jimu/BaseWidget esri/dijit/LocateButton dojo/_base/html dojo/on dojo/_base/lang jimu/utils ./Compass ./a11y/Widget jimu/dijit/Message dojo/touch".split(" "),function(g,n,q,b,k,l,p,r,h){g=g([n],{name:"MyLocation",baseClass:"jimu-widget-mylocation",moveTopOnActive:!1,startup:function(){this.inherited(arguments);this.a11y_updateLabel(this.nls._widgetLabel);this.placehoder=b.create("div",{"class":"place-holder",title:this.label},this.domNode);this.isNeedHttpsButNot=p.isNeedHttpsButNot();
!0===this.isNeedHttpsButNot?(console.log("LocateButton::navigator.geolocation requires a secure origin."),b.addClass(this.placehoder,"nohttps"),b.setAttr(this.placehoder,"title",this.nls.httpNotSupportError)):window.navigator.geolocation?(this.own(k(this.placehoder,"click",l.hitch(this,this.onLocationClick))),this.own(k(this.map,"zoom-end",l.hitch(this,this._scaleChangeHandler))),this.a11y_initEvents()):b.setAttr(this.placehoder,"title",this.nls.browserError)},onLocationClick:function(f){f&&f.stopPropagation&&
f.stopPropagation();b.hasClass(this.domNode,"onCenter")||b.hasClass(this.domNode,"locating")?(b.removeClass(this.domNode,"onCenter"),b.removeClass(this.placehoder,"tracking"),this._destroyGeoLocate(),this._tryToCleanCompass()):(this._createGeoLocate(),this.geoLocate.locate(),b.addClass(this.placehoder,"locating"))},_scaleChangeHandler:function(){var b=this.map.getScale();b&&this.geoLocate&&this.geoLocate.useTracking&&(this.geoLocate.scale=b)},onLocateOrError:function(b){if(b.error)this.onLocateError(b);
else this.onLocate(b)},onLocate:function(f){b.removeClass(this.placehoder,"locating");this.geoLocate.useTracking&&b.addClass(this.placehoder,"tracking");if(f.error)this.onLocateError(f);else b.addClass(this.domNode,"onCenter"),this.neverLocate=!1,this._tryToShowCompass(f)},_tryToShowCompass:function(b){!0!==this.config.locateButton.highlightLocation||!0!==this.config.locateButton.useTracking||!0!==this.config.useCompass&&!0!==this.config.useAccCircle||(this.compass=r.getInstance({folderUrl:this.folderUrl,
map:this.map,config:this.config}),this.compass.show(b,this.geoLocate))},_tryToCleanCompass:function(){this.compass&&this.compass.clean&&this.compass.clean()},_tryToDestroyCompass:function(){this.compass&&this.compass.destroy&&this.compass.destroy()},onLocateError:function(f){console.error(f.error);this._tryToCleanCompass();b.removeClass(this.placehoder,"locating");b.removeClass(this.domNode,"onCenter");b.removeClass(this.placehoder,"tracking")},_createGeoLocate:function(){var b=this.config.locateButton;
b.map=this.map;"undefined"===typeof this.config.locateButton.useTracking&&(b.useTracking=!0);b.centerAt=!0;b.setScale=!0;var c={maximumAge:0,timeout:15E3,enableHighAccuracy:!0};b.geolocationOptions&&(b.geolocationOptions=l.mixin(c,b.geolocationOptions));11===p.has("ie")&&(b.geolocationOptions.maximumAge=300,b.geolocationOptions.enableHighAccuracy=!1);this.geoLocate=new q(b);this.geoLocate.startup();this.geoLocate.own(k(this.geoLocate,"locate",l.hitch(this,this.onLocateOrError)))},_destroyGeoLocate:function(){this.geoLocate&&
(this.geoLocate.clear(),this.geoLocate.destroy());this.geoLocate=null},destroy:function(){this._tryToCleanCompass();this._tryToDestroyCompass();this._destroyGeoLocate();this.inherited(arguments)}});g.inPanel=!1;g.hasUIFile=!1;g.extend(h);return g});