// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare jimu/BaseWidget dojo/_base/lang dojo/on dojo/dom-construct dojo/_base/array jimu/symbolUtils esri/symbols/jsonUtils dijit/popup dijit/TooltipDialog dojo/_base/html dojo/keys dojo/query dijit/focus".split(" "),function(k,l,b,d,c,m,n,p,f,q,r,e,t,g){return k([l],{_tooltipDialog:null,selectedSymbol:null,symbolData:[],constructor:function(a){b.mixin(this,a)},postCreate:function(){this.symbolData||(this.symbolData=[]);this._createSelectedSymbolNode();this._hideTooltipDialog();
this.symbolData&&0<this.symbolData.length&&(this._createTooltipDialog(),this.selectSymbol(this.symbolData[0]));this.own(d(document.body,"click",b.hitch(this,function(a){this.isPartOfPopup(a.target||a.srcElement)||this._hideTooltipDialog()})))},setDefault:function(){this.selectSymbol(this.symbolData[0])},_createSelectedSymbolNode:function(){var a=c.create("div",{},this.domNode);this.selectedSymbolNode=c.create("div",{"class":"esriCTSelectedSymbol"},a)},_createTooltipDialog:function(){var a=this._createSymbolListMenu();
this._tooltipDialog=new q({content:a,"class":"esriCTSymbolPopup"});this.own(d(this.domNode,"click",b.hitch(this,function(a){a.stopPropagation();a.preventDefault();this._isTooltipDialogOpened?this._hideTooltipDialog():this._showTooltipDialog()})));this.own(d(this.domNode,"keydown",b.hitch(this,function(a){if(a.keyCode===e.ENTER||a.keyCode===e.SPACE)this._isTooltipDialogOpened?this._hideTooltipDialog():this._showTooltipDialog()})));this.own(d(document.body,"click",b.hitch(this,function(a){this.isPartOfPopup(a.target||
a.srcElement)||this._hideTooltipDialog()})))},_createSymbolListMenu:function(){var a,h;a=c.create("div",{"class":"esriCTSymbolListContainer"},null);h=c.create("div",{"class":"esriCTSymbolListContent",role:"menu"},a);m.forEach(this.symbolData,b.hitch(this,function(a){var b,d;b=c.create("div",{"class":"esriCTSymbolOption",title:a.label,tabindex:"0",role:"menuitem","aria-label":a.label},h);this._attachRowClick(b,a);d=c.create("div",{"class":"esriCTSymbolIcon"},b);c.create("div",{"class":"esriCTSymbolName",
innerHTML:a.label},b);b=c.create("div",{},d);this._createSymbol(a,b)}));return a},_attachRowClick:function(a,c){this.own(d(a,"click",b.hitch(this,function(){this.selectSymbol(c);this.hideOnSelect&&this._hideTooltipDialog()})));this.own(d(a,"keydown",b.hitch(this,function(a){if(a.keyCode===e.ENTER||a.keyCode===e.SPACE||a.keyCode===e.ESCAPE)this.selectSymbol(c),this.hideOnSelect&&(this._hideTooltipDialog(),g.focus(this.domNode))})))},_createSymbol:function(a,b){a&&(a=p.fromJson(a.symbol),(a=n.createSymbolNode(a))||
(a=c.create("div")),c.place(a,b))},selectSymbol:function(a){c.empty(this.selectedSymbolNode);this.selectedSymbol={label:a.label||a.type,type:a.type,symbol:a.symbol};this._createSymbol(this.selectedSymbol,this.selectedSymbolNode);this.onSelect(a)},destroy:function(){f.close(this._tooltipDialog);this._tooltipDialog.destroy();this.inherited(arguments)},isPartOfPopup:function(a){var b;b=this._tooltipDialog.domNode;return a===b||r.isDescendant(a,b)},onSelect:function(a){return a},_showTooltipDialog:function(){f.open({parent:this.getParent(),
popup:this._tooltipDialog,around:this.domNode,"class":"esriCTSymbolPopup"});this._isTooltipDialogOpened=!0;this.focusFirstSymbolOption()},_hideTooltipDialog:function(){f.close(this._tooltipDialog);this._isTooltipDialogOpened=!1},focusFirstSymbolOption:function(){var a=t(".esriCTSymbolOption",this._tooltipDialog.domNode);g.focus(a[0])}})});