// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/declare dojo/on dojo/when esri/dijit/geoenrichment/_Wizard esri/geometry/webMercatorUtils ./CreateBuffersPage ./NoPermissionsPage ./RunReportsPage ./SelectPointPolygonPage ./utils/GEUtil ./utils/GeocodeUtil".split(" "),function(e,l,c,d,m,f,n,p,q,r,g,h){return l([m],{selectedPoint:{tradeAreas:[]},selectedPolygon:{},selectedCountryID:"",availableCountries:[],name:"BusinessAnalystWizard",baseClass:"jimu-widget-business-analyst-wizard",postCreate:function(){this.inherited(arguments);
var a=this;d(g.hasGEPrivilege(),function(b){b?(a.pages.SELECT_POINT_POLYGON=new r({map:a.map,nls:a.nls,wizard:a,config:a.config,onNext:function(){a._loadCreateBuffersPage()}}),a.pages.CREATE_BUFFERS=new n({map:a.map,nls:a.nls,wizard:a,config:a.config,onBack:function(){a._loadSelectPointPolygonPage()},onNext:function(){a._loadRunReportsPage()}}),a.pages.CREATE_BUFFERS.startup(),a.pages.RUN_REPORTS=new q({map:a.map,nls:a.nls,wizard:a,config:a.config,onBack:function(){a.selectedPoint.geometry?a._loadCreateBuffersPage():
a._loadSelectPointPolygonPage()}}),a.loadPage("SELECT_POINT_POLYGON"),a.own(c(a.map.infoWindow,"Show",function(){a._featureSelected()})),a.own(c(a.map.infoWindow,"Hide",function(){a._featureUnselected()})),a.own(c(a.map.infoWindow,"set-features",function(){a._featureSelected()})),a.own(c(a.map.infoWindow,"selection-change",function(){a._featureSelected()})),a.selectedCountryID=a.config.defaultCountryID,d(g.getAvailableCountries(),function(b){a.availableCountries=b.countries;a.setSelectedCountry(a.selectedCountryID)}),
a.map.infoWindow&&a.map.infoWindow.features&&0<a.map.infoWindow.features.length&&a._featureSelected()):(a.pages.NO_PERMISSIONS=new p({nls:a.nls}),a.pages.NO_PERMISSIONS.startup(),a.loadPage("NO_PERMISSIONS"))})},startup:function(){},clearSelectedPointBuffers:function(){var a=this;e.forEach(this.selectedPoint.tradeAreas,function(b){b&&b.graphic&&a.map.graphics.remove(b.graphic)});this.selectedPoint.tradeAreas=[]},clearSelectedPoint:function(){this.clearSelectedPointBuffers();this.map.graphics.remove(this.selectedPoint.pointGraphic);
this.selectedPoint={tradeAreas:[]}},clearSelectedPolygon:function(){this.selectedPolygon={}},setSelectedCountry:function(a){var b=this;3==a.length?e.forEach(this.availableCountries,function(k){k.abbr3==a&&(b.selectedCountryID=k.id)}):2==a.length&&(this.selectedCountryID=a);this.pages.RUN_REPORTS.loadReportsInfographicsForCountry(this.selectedCountryID)},_loadSelectPointPolygonPage:function(){this.clearSelectedPoint();this.loadPage("SELECT_POINT_POLYGON")},_loadCreateBuffersPage:function(){this.loadPage("CREATE_BUFFERS");
this.pages.CREATE_BUFFERS.refresh()},_loadRunReportsPage:function(){this.loadPage("RUN_REPORTS");this.pages.RUN_REPORTS.refresh()},refreshPage:function(){this.currentPage&&this.currentPage.refresh&&this.currentPage.refresh()},_featureSelected:function(){this.clearSelectedPoint();this.clearSelectedPolygon();var a=this,b=-1<this.map.infoWindow.selectedIndex&&this.map.infoWindow.features&&this.map.infoWindow.features[this.map.infoWindow.selectedIndex];b&&("point"==b.geometry.type?(this.selectedPoint.geometry=
b.geometry,this.selectedPoint.locationName=this._getFeatureName(b),b=f.xyToLngLat(b.geometry.x,b.geometry.y),this.selectedPoint.long=b[0].toFixed(5),this.selectedPoint.lat=b[1].toFixed(5),d(h.reverseGeocode({x:b[0],y:b[1]}),function(b){a.setSelectedCountry(b.address.CountryCode);a._loadCreateBuffersPage()})):"polygon"==b.geometry.type?(this.selectedPolygon.geometry=b.geometry,this.selectedPolygon.locationName=this._getFeatureName(b),this.selectedPolygon.feature=b,b=b.geometry.getCentroid(),b=f.xyToLngLat(b.x,
b.y),d(h.reverseGeocode({x:b[0],y:b[1]}),function(b){a.setSelectedCountry(b.address.CountryCode);a._loadRunReportsPage()})):a._loadSelectPointPolygonPage())},_featureUnselected:function(){this.clearSelectedPoint();this.clearSelectedPolygon();this.pages.SELECT_POINT_POLYGON.search.clear();this._loadSelectPointPolygonPage()},_getFeatureName:function(a){return a.getTitle()?a.getTitle():a._layer.displayField&&a.attributes[a._layer.displayField]?a.attributes[a._layer.displayField]:""}})});