// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/ThreatAnalysis/templates/ColorPickerEditor.html":'\x3cdiv class\x3d"colorPickerEditor"\x3e\r\n  \x3cdiv class\x3d"colorPicker" data-dojo-attach-point\x3d"colorPicker"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"sliderbar" data-dojo-attach-point\x3d"sliderBar"\x3e\r\n    \x3col data-dojo-type\x3d"dijit/form/HorizontalRuleLabels" style\x3d"height:2.5em;" container\x3d"topDecoration"\x3e\r\n      \x3cli\x3e${nls.transparencyLabel}\x3c/li\x3e\r\n      \x3cli\x3e\x3c/li\x3e\r\n    \x3c/ol\x3e\r\n  \x3c/div\x3e\r\n  \x3cinput type\x3d"text" data-dojo-type\x3d"dijit/form/NumberSpinner" value\x3d"0" data-dojo-attach-point\x3d"spinner"\r\n    data-dojo-props\x3d"smallDelta:10,intermediateChanges:true,constraints: {min:0,max:100}"\x3e\r\n  \x3cdiv class\x3d\'styleSelectSection\'\x3e\r\n    \x3clabel for\x3d"${id}_select"\x3e${nls.style}\x3c/label\x3e\r\n    \x3cselect class\x3d"styleSelect" data-dojo-type\x3d"jimu/dijit/formSelect" data-dojo-attach-point\x3d"dropdown"/\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/on dojo/dom-attr dojo/query dojo/_base/html jimu/BaseWidget dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/text!../templates/ColorPickerEditor.html dijit/form/HorizontalSlider jimu/dijit/ColorPickerPopup dijit/form/NumberSpinner".split(" "),function(h,g,d,k,f,c,l,m,n,p,q,r,t,u){return h([n,p,q],{_defaultColor:"#485566",templateString:r,nls:null,postMixInProperties:function(){this.inherited(arguments);this.isRenderIdForAttrs=
!0},postCreate:function(){this.colorPicker=new u({color:this._defaultColor,tabindex:"0",role:"button"},this.colorPicker);this.colorPicker.startup();this.own(this.colorPicker.on("change",d.hitch(this,function(){this.onColorPickerEditorChanged()})));this.slider=new t({name:"slider",value:100,minimum:0,maximum:100,discreteValues:101,intermediateChanges:!0,showButtons:!1,style:"display: inline-block;"},this.sliderBar);this.slider.startup();var a=[],b,c="esriSLSDash esriSLSDashDot esriSLSDashDotDot esriSLSDot esriSLSLongDash esriSLSLongDashDot esriSLSNull esriSLSShortDash esriSLSShortDashDot esriSLSShortDashDotDot esriSLSShortDot esriSLSSolid".split(" "),
v="esriSFSBackwardDiagonal esriSFSCross esriSFSDiagonalCross esriSFSForwardDiagonal esriSFSHorizontal esriSFSNull esriSFSSolid esriSFSVertical".split(" ");"line"===this.type?g.forEach(c,d.hitch(this,function(e){b={value:e,label:this.nls.lineStyles[e]};a.push(b)})):g.forEach(v,d.hitch(this,function(e){b={value:e,label:this.nls.fillStyles[e]};a.push(b)}));this.dropdown.addOption(a);this.inherited(arguments)},startup:function(){this._setAriaLabelForEditorNodes();this.own(f(this.slider,"change",d.hitch(this,
function(a){isNaN(a)||!1!==this._isSameVal()||(a>this.spinner.maximum?(this.spinner.setValue(0),this.spinner.setValue(this.spinner.maximum)):this.spinner.setValue(a))})));this.own(f(this.spinner,"change",d.hitch(this,function(a){isNaN(a)||!1===this._isSameVal()&&a<=this.slider.maximum&&this.slider.setValue(a)})));this.own(f(this.dropdown,"change",d.hitch(this,function(){this.onColorPickerEditorChanged()})));this._stylePolyfill();this.inherited(arguments)},_setAriaLabelForEditorNodes:function(){var a;
a="fill"===this.type?this.nls.fill:this.nls.outline;c.set(this.colorPicker.domNode,"aria-label",a+" "+this.nls.colorPicker);c.set(this.slider,"aria-label",a+" "+this.nls.transparencyLabel);c.set(this.spinner,"aria-label",a+" "+this.nls.transparencyLabel);c.set(this.dropdown,"aria-label",a+" "+this.nls.style)},_isSameVal:function(){return this.slider.getValue()===this.spinner.getValue()},getValues:function(){var a=null,b=null;(b=this.colorPicker.getColor())&&b.toHex&&(a=b.toHex());b=this.spinner.getValue()/
100;return{color:a,transparency:b}},setValues:function(a){if("object"===typeof a||"string"===typeof a)this.colorPicker.setColor(new k(a.color)),a.transparency="undefined"===typeof a.transparency?0:100*a.transparency,this.slider.setValue(a.transparency),this.spinner.setValue(a.transparency)},_stylePolyfill:function(){var a=l(".dijitSliderLeftBumper",this.domNode)[0];a&&a.parentNode&&m.setStyle(a.parentNode,"background-color","#24b5cc")},onColorPickerEditorChanged:function(){},validateSpinner:function(){var a=
!0;this.spinner.isValid()||(this._shake(this.spinner.domNode,16),this.spinner.focus(),a=!1);return a},_shake:function(a,b){function d(){if(15>c){a.style.transform="translate(0px, 0px)";b-=e;var w=f(-b,b),x=f(-b,b);a.style.transform="translate("+w+"px, "+x+"px)";c+=1;requestAnimationFrame(d)}15<=c&&(a.style.transform="translate(0, 0)",g._shakingElements.splice(g._shakingElements.indexOf(a),1))}var c=1,e=b/15,f=function(a,b){return Math.floor(Math.random()*(b-a+1))+a};this._shakingElements||(this._shakingElements=
[]);if(-1===this._shakingElements.indexOf(a)){this._shakingElements.push(a);var g=this;d()}}})});