// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("esri/request dojo/json dojo/topic dojo/_base/lang dojo/_base/array esri/arcgis/Portal esri/IdentityManager esri/layers/FeatureLayer jimu/LayerInfos/LayerInfos".split(" "),function(l,q,b,c,w,r,m,t,u){return{saveToPortal:function(d,a,h,x,g,f,l){m.registerOAuthInfos();m.getCredential(h.portalUrl+"/sharing",{oAuthPopupConfirmation:!1}).then(c.hitch(this,function(){var m=new r.Portal(h.portalUrl);m.signIn().then(c.hitch(this,function(e){var n=e.credential.token,q=e.orgId,v=e.username;if("org_user"===
e.role)g.innerHTML=f.createService.format(f.userRole),b.publish("setLastFocusNode",!1);else{var r=h.portalUrl+"sharing/content/users/"+v+"/createService";this.isNameAvailable(h.portalUrl+"sharing/rest/portals/"+q+"/isServiceNameAvailable",n,d).then(c.hitch(this,function(e){e.available?(b.publish("setBusyIndicator",!0),this.createFeatureService(r,n,this.getFeatureServiceParams(d,a)).then(c.hitch(this,function(p){if(p.success){var e=p.serviceurl.replace(/rest/g,"rest/admin")+"/addToDefinition";this.addDefinitionToService(e,
n,this.getLayerParams(d,a,x,f)).then(c.hitch(this,function(k){if(k.success){k=new t(p.serviceurl+"/0?token\x3d"+n,{id:d,outFields:["*"]});k._wabProperties={itemLayerInfo:{portalUrl:h.portalUrl,itemId:p.itemId}};a.addLayer(k);var e;if(k.loaded)e=u.getInstanceSync().getLayerInfoById(d),e.enablePopup();else k.on("load",c.hitch(this,function(){e=u.getInstanceSync().getLayerInfoById(d);e.enablePopup()}));k.applyEdits(l,null,null).then(c.hitch(this,function(){b.publish("clear")})).otherwise(c.hitch(this,
function(){b.publish("clear")}));b.publish("setBusyIndicator",!1);g.innerHTML=f.successfullyPublished.format('\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+f.successfullyPublished+'" href\x3d"'+h.portalUrl+"home/item.html?id\x3d"+p.itemId+'" target\x3d"_blank"\x3e')+"\x3c/a\x3e";b.publish("setLastFocusNode",!0)}}),c.hitch(this,function(d){b.publish("setBusyIndicator",!1);g.innerHTML=f.addToDefinition.format(d.message);b.publish("setLastFocusNode",!1)}))}else b.publish("setBusyIndicator",
!1),g.innerHTML=f.unableToCreate.format(d),b.publish("setLastFocusNode",!1)}),c.hitch(this,function(d){b.publish("setBusyIndicator",!1);g.innerHTML=f.createService.format(d.message);b.publish("setLastFocusNode",!1)}))):m.queryItems({q:"name:"+d+" AND owner:"+v}).then(c.hitch(this,function(a){if(0<a.results.length){a=w.map(a.results,function(a){if(a.name===d)return a},this);var e=new t(a[0].url+"/0?token\x3d"+n,{id:d,outFields:["*"]});e._wabProperties={itemLayerInfo:{portalUrl:h.portalUrl,itemId:a[0].id}};
e.applyEdits(l,null,null).then(c.hitch(this,function(){b.publish("clear")})).otherwise(c.hitch(this,function(){b.publish("clear")}));b.publish("setBusyIndicator",!1);g.innerHTML=f.successfullyAppended.format('\x3cbr /\x3e\x3ca role\x3d"link" tabindex\x3d"0" aria-label\x3d"'+f.successfullyAppended+'" href\x3d"'+h.portalUrl+"home/item.html?id\x3d"+a[0].id+'" target\x3d"_blank"\x3e')+"\x3c/a\x3e";b.publish("setLastFocusNode",!0)}}),c.hitch(this,function(){b.publish("setBusyIndicator",!1);g.innerHTML=
f.retrieveExistingLayerError.format(d);b.publish("setLastFocusNode",!1)}))}),c.hitch(this,function(a){b.publish("setBusyIndicator",!1);g.innerHTML=f.checkService.format(a.message);b.publish("setLastFocusNode",!1)}))}}),c.hitch(this,function(a){g.innerHTML=a.message;b.publish("setLastFocusNode",!1)}))}));m.destroyCredentials()},getFeatureServiceParams:function(d,a){return{name:d,serviceDescription:"",hasStaticData:!1,maxRecordCount:1E3,supportedQueryFormats:"JSON",capabilities:"Create,Delete,Query,Update,Editing",
tags:"ThreatAnalysis",description:"",copyrightText:"",spatialReference:{wkid:102100},initialExtent:{xmin:a.extent.xmin,ymin:a.extent.ymin,xmax:a.extent.xmax,ymax:a.extent.ymax,spatialReference:{wkid:102100}},allowGeometryUpdates:!0,units:"esriMeters",xssPreventionInfo:{xssPreventionEnabled:!0,xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"}}},getLayerParams:function(d,a,b,c){return{layers:[{adminLayerInfo:{geometryField:{name:"Shape"},xssTrustedFields:""},id:0,name:d,type:"Feature Layer",
displayField:"",description:"",tags:"ThreatAnalysis",copyrightText:"",defaultVisibility:!0,ownershipBasedAccessControlForFeatures:{allowOthersToQuery:!1,allowOthersToDelete:!1,allowOthersToUpdate:!1},relationships:[],isDataVersioned:!1,supportsCalculate:!0,supportsAttachmentsByUploadId:!0,supportsRollbackOnFailureParameter:!0,supportsStatistics:!0,supportsAdvancedQueries:!0,supportsValidateSql:!0,supportsCoordinatesQuantization:!0,supportsApplyEditsWithGlobalIds:!0,advancedQueryCapabilities:{supportsPagination:!0,
supportsQueryWithDistance:!0,supportsReturningQueryExtent:!0,supportsStatistics:!0,supportsOrderBy:!0,supportsDistinct:!0,supportsQueryWithResultType:!0,supportsSqlExpression:!0,supportsReturningGeometryCentroid:!0},useStandardizedQueries:!1,geometryType:"esriGeometryPolygon",minScale:0,maxScale:0,extent:a.extent,drawingInfo:{renderer:b.toJson(),transparency:0},allowGeometryUpdates:!0,hasAttachments:!1,htmlPopupType:"esriServerHTMLPopupTypeNone",hasM:!1,hasZ:!1,objectIdField:"OBJECTID",globalIdField:"",
typeIdField:"",fields:[{name:"OBJECTID",type:"esriFieldTypeOID",actualType:"int",alias:"OBJECTID",sqlType:"sqlTypeOther",nullable:!1,editable:!1,domain:null,defaultValue:null},{name:"zone_type",type:"esriFieldTypeString",alias:c.zoneTypeLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",length:256},{name:"threat_type",type:"esriFieldTypeString",alias:c.threatType,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",
length:256},{name:"mandatory_dist",type:"esriFieldTypeDouble",alias:c.mandatoryLabel,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"safe_dist",type:"esriFieldTypeDouble",alias:c.safeLabel,actualType:"float",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeFloat"},{name:"units",type:"esriFieldTypeString",alias:c.unitsLabel,actualType:"nvarchar",nullable:!0,editable:!0,domain:null,defaultValue:null,sqlType:"sqlTypeNVarchar",
length:256}],indexes:[],types:[],templates:[{name:"New Feature",description:"",drawingTool:"esriFeatureEditToolPolygon",prototype:{attributes:{type:""}}}],supportedQueryFormats:"JSON",hasStaticData:!1,maxRecordCount:1E4,standardMaxRecordCount:4E3,tileMaxRecordCount:4E3,maxRecordCountFactor:1,exceedsLimitFactor:1,capabilities:"Query,Editing,Create,Update,Delete"}]}},isNameAvailable:function(d,a,b){return l({url:d,content:{name:b,type:"Feature Service",token:a,f:"json"},handleAs:"json",callbackParamName:"callback"},
{usePost:!0})},createFeatureService:function(b,a,c){return l({url:b,content:{f:"json",token:a,typeKeywords:"ArcGIS Server,Data,Feature Access,Feature Service,Service,Hosted Service",createParameters:q.stringify(c),outputType:"featureService"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})},addDefinitionToService:function(b,a,c){return l({url:b,content:{token:a,addToDefinition:q.stringify(c),f:"json"},handleAs:"json",callbackParamName:"callback"},{usePost:!0})}}});